### ISSUE TITLE
Certificate" in version "cert-manager.io/v1", unable to recognize

### ISSUE THREAD

**Issue by marinsagovac** [kubeshop/testkube#1071]
**Describe the bug**
I can't install using helm chart testkube to install into k8s, got cert errors. Is it possible to skip it. Older version 0.6.4 works but on latest 0.9.47 cert failed: `Certificate" in version "cert-manager.io/v1", unable to recognize`.

**To Reproduce**
```
helm pull testkube/testkube --untar

<Changing nodeport, disable dashboard, analytics and change ClusterIP to NodePort and assign IP to cluster, disable tls properties>

helm install testkube . --values values.yaml --namespace mynamespace
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"]
```

**Expected behavior**
Helm installation should be running and deployed to k8s. Working with 0.6.4 version.

**Version / Cluster**
- Which testkube version? 0.9.2
- What Kubernetes cluster? k8s
- What Kubernetes version? 1.21

**Screenshots**
No.
 
**Additional context**
With version 0.6.3 working well.

Chart.yaml:

```
apiVersion: v2
dependencies:
- name: testkube-operator
  repository: file://../testkube-operator
  version: 0.10.2-beta001
- name: mongodb
  repository: https://charts.bitnami.com/bitnami
  version: 10.0.0
- name: api-server
  repository: file://../api-server
  version: 0.9.22
- condition: testkube-dashboard.enabled
  name: testkube-dashboard
  repository: file://../testkube-dashboard
  version: 0.9.2
description: A Helm chart for testkube.
name: testkube
type: application
version: 0.9.47
```

Running ```helm install testkube . --values values.yaml --namespace mynamespace```

returns
```
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1", unable to recognize "": no matches for kind "Issuer" in version "cert-manager.io/v1"]
```
