### ISSUE TITLE
Make proposals for no direct kubectl access

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#1123]

**Comment by exu** [comment]
1. [oauth-proxy
](https://github.com/oauth2-proxy/oauth2-proxy)

**Comment by exu** [comment]
2. https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/

**Comment by exu** [comment]
3. Basic auth based on secrets?/configmaps?

**Comment by exu** [comment]
Looks like oauth2-proxy + ingress-nginx + https://kubernetes.github.io/ingress-nginx/examples/auth/external-auth/ + https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/ could do the work

**Comment by exu** [comment]
Ok, I think I was able to configure Oauth proxy in front of dashboard:
https://kube.ex00.pl/ (staging cluster) - it’s on local cert so add to whitelist in your browser if you want to play)

- We need Oauth2 proxy installed (from helm chart)
- configure provider (I’ve used our company google) add OAuth 2.0 Client IDs in google cloud console here: https://console.cloud.google.com/apis/credentials?project=testkube-328312  details here [https://console.cloud.google.com/apis/credentials/oauthclient/560938004384-t9efb15a6pjof2[…]8jo69.apps.googleusercontent.com?project=testkube-328312](https://console.cloud.google.com/apis/credentials/oauthclient/560938004384-t9efb15a6pjof24jc164f51l6q88jo69.apps.googleusercontent.com?project=testkube-328312)
- configure ingress oauth annotations 
```    
nginx.ingress.kubernetes.io/auth-signin: https://kube.ex00.pl/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://kube.ex00.pl/oauth2/auth
```
- create ingress for oauth proxy
```
spec:
  rules:
  - host: kube.ex00.pl
    http:
      paths:
      - backend:
          service:
            name: oauth-proxy-oauth2-proxy
            port:
              number: 80
        path: /oauth2
        pathType: Prefix
  tls:
  - hosts:
    - auth.ex00.pl
    secretName: ex00
```
