### ISSUE TITLE
Cypress executor - test execution is extremely slow and unstable with video recording enabled, videos are laggy and incomplete

### ISSUE THREAD

**Issue by Garvit-Jethwani** [kubeshop/testkube#1540]
**Describe the bug**
When running cypress tests using testkube inside the cluster, videos recorded are laggy and incomplete. Often stuck and freezes on tests are loading.

**To Reproduce**
1. Run Cypress tests using testkube.
2. Download artifacts generated
3. Video recorded is not proper and is incomplete.

**Expected behavior**
Cypress result video should have been clearer with video length should be equal to length seen in test execution container logs, instead they are laggy and most of the length of video is **Tests are loading**.  

**Version / Cluster**
- Testkube version - 1.1.4
- What Kubernetes cluster type - EC2 (t2.medium instance) 
- K8s version - 1.22.1
- Cypress version - 9.5.4

**Screenshots**
Attaching cypress result video -
https://user-images.githubusercontent.com/44478489/168964125-d6de4f72-ffbe-4ec6-9ac7-0a7cb8b5bfb1.mp4

**Additional context**
Can you please have a look whether this is a issue from your end.

**Comment by exu** [comment]
Hi @Garvit-Jethwani thanks for checking out Testkube. It could be some issue with Cypress, but I'll discuss ideas of solving it with team and will ping you soon.

**Comment by exu** [comment]
Hi @Garvit-Jethwani we've released new Testkube with Cypress 10.0 as default. Ping us if it work for you!

**Comment by exu** [comment]
Closing it for now as there is no feedback from user

**Comment by tkonieczny** [comment]
Reopened - I was able to reproduce this bug with the latest Testkube version.
```
Client Version 1.6.28
Server Version v1.6.28
```

**Comment by tkonieczny** [comment]
Locally (powerful Ryzen 3950x-based PC) Dashboard E2E tests take less then a minute to execute, the same tests executed with Testkube with video *disabled* take about 2m30s (including installation of dependencies), which is completely fine. But, when the video is *enabled* the whole execution is extremely slow and laggy - not only the video and processing.

Steps to reproduce:
- Run Dashboard E2E tests with video *enabled* (`dashboard-e2e-video-enabled` branch) using this CRD:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: dashboard-e2e-tests-video-enabled-example
  namespace: testkube
spec:
  type: cypress/project
  content:
    type: git-dir
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube
      branch: dashboard-e2e-video-enabled
      path: test/dashboard-e2e
  executionRequest:
    args:
      - --config
      - baseUrl=http://testkube-dashboard.testkube.svc.cluster.local:8080
      - --env
      - API_URL=http://testkube-api-server.testkube.svc.cluster.local:8088/v1
```

** Execution log: **
Execution log:
```
It looks like this is your first time using Cypress: 10.10.0

[STARTED] Task without title.
[TITLE]  Verified Cypress!       /root/.cache/Cypress/10.10.0/Cypress
[SUCCESS]  Verified Cypress!       /root/.cache/Cypress/10.10.0/Cypress

Opening Cypress...
[265:1106/145233.217797:ERROR:zygote_host_impl_linux.cc(263)] Failed to adjust OOM score of renderer with pid 431: Permission denied (13)
[431:1106/145233.261980:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.

tput: No value for $TERM and no -T specified
================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        10.10.0                                                                        │
  │ Browser:        Electron 106 (headless)                                                        │
  │ Node Version:   v17.9.1 (/usr/local/bin/node)                                                  │
  │ Specs:          2 found (create-test.cy.js, run-test.cy.js)                                    │
  │ Searched:       cypress/e2e/**/*.cy.{js,jsx,ts,tsx}                                            │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
