### ISSUE TITLE
Create GitHub Action to run Testkube command on a GKE cluster

### ISSUE THREAD

**Issue by vLia** [kubeshop/testkube#1768]
**Is your feature request related to a problem? Please describe.**
After the presentation on the kubepug executor, @olensmar brought up that there should be a GitHub action to run Testkube commands directly on GKE. The GitHub workflow that prompted this idea is https://github.com/vLia/testkube-tests/blob/main/.github/workflows/kubepug-test.yaml

**Describe the solution you'd like**
There should be a GitHub action to run a Testkube command on a GKE cluster, example:
```
      - name: Testkube test
        uses: actions/testkube-gke@v1
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER_NAME_DEV }}
          location: ${{ secrets.GKE_ZONE_DEV }}
          credentials: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}
          command: "kubectl testkube run test test-a"
```

The action would perform all necessary installs/connections in one go - instead of requiring separate actions for each corresponding steps
