### ISSUE TITLE
Add optional attributes [nodeSelector|tolerations|annotations] when creating jobs

### ISSUE THREAD

**Issue by marcportabellaclotet-mt** [kubeshop/testkube#1903]
**Describe the enhancement you'd like to see**

I would like to define job properties like nodeSelector |tolerations |annotations when k8s jobs are created. 
nodeSelector and tolerations will be helpful to allocate pods and jobs into specific nodes.
annotations will be helpful to use vault secrets

**Additional context**
- I have find a similar [issue](https://github.com/kubeshop/testkube/issues/1008) in this repo, but the solution proposed is for generating init containers.
- Using [jobTemplate](https://github.com/kubeshop/testkube/blob/main/api/v1/testkube.yaml#L2456), does not help, as metadata.name is hardcoded.
Maybe it is already possible, but I don't find the way on how to achieve it.

Thanks a lot for this amazing software!!

**Comment by vsukhin** [comment]
Hey @marcportabellaclotet-mt Thank you for using our software. Really happy to see thoughtful requests from our users. It means, that they are searching for ways to use our software in their real life scenarios. And we're always to ready to help, even if something is not supported at the moment.

Yes, we see such requests from time to time from Testkube community.
The idea is next:
We have a template for executed job in Testkube API Helm chart https://github.com/kubeshop/helm-charts/blob/main/charts/testkube-api/job-template.yml
It's used by our own executor or any executor without job tempalte defined.
All you need to do is to create a new executor copy, for exampe, called it something `mypostman-executor`, change test types to process, for example `mypostman/collection` and provide your own job template based on our job template with your annotations and lables. You can add any metadata you need. 
Do you mean, that you should define your metadata.name? Because we use for tracking results of test execution

**Comment by marcportabellaclotet-mt** [comment]
Thanks a lot for the response!
I tested defining a jobtemplate in the executor. What I am doing is define the job template as json, which works, but I have to to define the metadata name. If I don't define the metadata.name, I can not create the executor.
With builtin executors, the metadata.name is generated dynamically, and as you say, it is used for tracking results.
I am able to define a jobtemplate, and the job is created with the defined spec. However, tracking does not work, as the name defined in the job spec is hardcoded. I am sure I  am missing something, maybe you can provide a example.

I will try it again. Thanks again!!

**Comment by vsukhin** [comment]
As json, might be you can provide your sample then? 

Because original job template is yaml file. Don't change `{{ }}` parameters, because they are used by executor.
But you can add annotations like below:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Name }}
  namespace: {{ .Namespace }}
  annotations:
    imageregistry: "https://hub.docker.com/"
spec:
  template:
    spec:
      initContainers:
      - name: {{ .Name }}-init
        image: {{ .InitImage }}
        imagePullPolicy: Always
        command: 
          - "/bin/runner"
          - '{{ .Jsn }}'
        volumeMounts:
        - name: data-volume
          mountPath: /data 
      containers:
      - name: {{ .Name }}
        image: {{ .Image }}
        imagePullPolicy: Always
        command: 
          - "/bin/runner"
          - '{{ .Jsn }}'
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 0
  ttlSecondsAfterFinished: 180  
```

**Comment by marcportabellaclotet-mt** [comment]
This is a sample hardcoding the name:
```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: k6-executor-test
spec:
  image: kubeshop/testkube-k6-executor:0.0.9
  job_template: '{"apiVersion":"batch/v1","kind":"Job","metadata":{"name": "lol" },"spec":{"template":{"spec":{"containers":[{"name":"lol","image":"lol","imagePullPolicy":"Always","command":["/bin/runner","lol2"]}],"restartPolicy":"Never"}},"backoffLimit":0,"ttlSecondsAfterFinished":180}}'
  types:
  - k6/script
```

This creates the job, but fails because of tracking.

Using .name: 

```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: k6-executor-test
spec:
  image: kubeshop/testkube-k6-executor:0.0.9
  job_template: '{"apiVersion":"batch/v1","kind":"Job","metadata":{"name": {{ .name}} },"spec":{"template":{"spec":{"containers":[{"name":"lol","image":"lol","imagePullPolicy":"Always","command":["/bin/runner","lol2"]}],"restartPolicy":"Never"}},"backoffLimit":0,"ttlSecondsAfterFinished":180}}'
  types:
  - k6/script
```
When running test:

```
k testkube run test  k6-2
⨯ starting test execution testkube/k6-2 (error: api/POST-testkube.Execution returned error: api server problem: test execution failed: executing job spec template: template: job:1:61: executing "job" at <.name>: can't evaluate field name in type client.JobOptions, context: null;
resp error:an error on the server ("unknown") has prevented the request from succeeding (post services testkube-api-server:8088))
```
Probably I am not understanding how to define the job_template...

**Comment by vsukhin** [comment]
Ok, 
```kubectl testkube create executor --image kubeshop/testkube-postman-executor:1.0.2 --job-template template.yaml --types "mypostman/collection" --name mypostman-executor  --crd-only
```
Save in template.yaml my yaml above

```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: mypostman-executor
  namespace: testkube
  labels:
spec:
  types:
  - mypostman/collection  
  executor_type: job
  uri: 
  image: kubeshop/testkube-postman-executor:1.0.2
  job_template: "apiVersion: batch/v1\nkind: Job\nmetadata:\n  name: {{ .Name }}\n  namespace: {{ .Namespace }}\n  annotations:\n    imageregistry: \"https://hub.docker.com/\"\nspec:\n  template:\n    spec:\n      initContainers:\n      - name: {{ .Name }}-init\n        image: {{ .InitImage }}\n        imagePullPolicy: Always\n        command: \n          - \"/bin/runner\"\n          - '{{ .Jsn }}'\n        volumeMounts:\n        - name: data-volume\n          mountPath: /data \n      containers:\n      - name: {{ .Name }}\n        image: {{ .Image }}\n        imagePullPolicy: Always\n        command: \n          - \"/bin/runner\"\n          - '{{ .Jsn }}'\n        volumeMounts:\n        - name: data-volume\n          mountPath: /data\n      volumes:\n      - name: data-volume\n        emptyDir: {}\n      restartPolicy: Never\n  backoffLimit: 0\n  ttlSecondsAfterFinished: 180\n\n"

```
