### ISSUE TITLE
Allow to load secrets from existing references

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#2060]
**Describe the bug**

As Testkube user I want to be able to load my existing secrets reference when defining test executionRequest: 

```
---
  apiVersion: tests.testkube.io/v3
  kind: Test
  metadata:
    name: test
    namespace: testkube
  spec:
    content:
      repository:
        branch: test
        type: git-dir
        uri: https://github.com/<org>/repo
      type: git-dir
    executionRequest:
      args:
      - --config-file
      - tests/cypress/cypress.config.js
      - --spec
      - tests/cypress/e2e/bbq/bbq.cy.js
      variables:
        SECRET_KEY:
          name: SECRET_KEY
          type: secret
          valueFrom:
            secretKeyRef:
              name: test
              key: SECRET_KEY
    type: cypress/custom
  status: {}
  ---
  apiVersion: v1
  kind: Secret
  data:
    SECRET_KEY: U0VDUkVUX1ZBTFVF
  metadata:
    name: test
    namespace: testkube
  ---
```

Looks like current solution is not loading them from existing ones, just creates on new ones on execution.
