### ISSUE TITLE
When using `testkube create test` command with the --crds-only flag the output fails to apply to the cluster due to the yaml containing keys with null values

### ISSUE THREAD

**Issue by BoatPartyJesus** [kubeshop/testkube#2115]
**Describe the bug**
When generating only crds using the `--crds-only` flag, the output that is created contains additional empty keys which when running `kubectl apply -f` throw an error as they're not allowed to be null values.

**To Reproduce**
1. Run `kubectl testkube create ... --crds-only`
2. Specify the `--crds-only` flag
3. See that additional keys are specified with null values.

**Expected behavior**

**Version / Cluster**
- Which testkube version? 
```
Client Version 1.4.30
Server Version v1.4.30
Commit c91f924162ace69c4471e7741c9482f9abd9ca95
Built by goreleaser
Build date 2022-08-22T07:13:47Z
```
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
EKS
- What Kubernetes version?
1.22

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**
In my use case the following was run:
CI Script:
```
    kubectl-testkube create test \
      --label="test_type=${TEST_TYPE}" \
      --label="test_vertical=${TEST_VERTICAL}" \
      --git-uri="$CI_PROJECT_URL" \
      --git-branch="$CI_DEFAULT_BRANCH" \
      --git-path="$test" \
      --git-username-secret="git-credentials=username" \
      --git-token-secret="git-credentials=token" \
      --type="k6/script" \
      --name="$TEST_TYPE-$TEST_VERTICAL-$TEST_NAME" \
      --crd-only | sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" >$TEST_OUTPUT_FILE
 ```

CRD output:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: smoke-tests-rails-api-demo-tests
  namespace: testkube
  labels:
    test_type: smoke-tests
    test_vertical: rails-api
spec:
  type: k6/script
  content:
    type: git-dir
    repository:
      type: git
      uri: REDACTED
      branch: main
      commit:       
      path: ./scripts/smoke-tests/rails-api/demoTests.js
      usernameSecret:
        name: git-credentials
        key: username
      tokenSecret:
        name: git-credentials
        key: token
    data: 
    uri: 
  schedule: 
  executionRequest:
    name: 
    variablesFile: 
    variables:
    args:
    envs:
    secretEnvs:
    httpProxy: 
    httpsProxy: 
 ```
 
 Kubectl apply output:
 ```
 {"error":"Test.tests.testkube.io \"smoke-tests-rails-api-demo-tests\" is invalid: [spec.content.repository.commit: Invalid value: \"null\": spec.content.repository.commit in body must be of type string: \"null\", spec.content.uri:
 Invalid value: \"null\": spec.content.uri in body must be of type string: \"null\", spec.content.data: Invalid value: \"null\": spec.content.data in body must be of type string: \"null\", spec.executionRequest.envs: Invalid value
: \"null\": spec.executionRequest.envs in body must be of type object: \"null\", spec.executionRequest.variablesFile: Invalid value: \"null\": spec.executionRequest.variablesFile in body must be of type string: \"null\", spec.exec
utionRequest.secretEnvs: Invalid value: \"null\": spec.executionRequest.secretEnvs in body must be of type object: \"null\", spec.executionRequest.args: Invalid value: \"null\": spec.executionRequest.args in body must be of type a
rray: \"null\", spec.executionRequest.variables: Invalid value: \"null\": spec.executionRequest.variables in body must be of type object: \"null\", spec.executionRequest.httpsProxy: Invalid value: \"null\": spec.executionRequest.h
ttpsProxy in body must be of type string: \"null\", spec.executionRequest.httpProxy: Invalid value: \"null\": spec.executionRequest.httpProxy in body must be of type string: \"null\", spec.executionRequest.name: Invalid value: \"n
ull\": spec.executionRequest.name in body must be of type string: \"null\", spec.schedule: Invalid value: \"null\": spec.schedule in body must be of type string: \"null\"]","group":"tests.testkube.io","kind":"Test","name":"smoke-t
ests-rails-api-demo-tests","namespace":"testkube","status":"Failed","timestamp":"2022-08-22T11:35:45Z","type":"apply"}
```
