### ISSUE TITLE
Triggering test based on cluster events

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#2134]
DoD: 

Run test / test suites when resource change

We decided to go with TestTrigger CRD

```yaml
apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: deployment-test-trigger
spec:
  testName: someLoadTest
  # or
  #testSuiteName: someLoadTest
  labels:
    app: my-deployment
  event: update
```

- watch based on `labels` on given `event`
- reconcile triggers in operator/watcher
- watcher should be put it into Testkube API

----------- EDIT ----------

we was also considering labels, but they are no flexible enough.

Resource should have testkube.io/v1 annotation 

Option one: 
e.g. 
```
labels: 
     testkube.io/v1/trigger-test/name: test-name
     testkube.io/v1/trigger-test/variables: key=value,key2=value2
```
