### ISSUE TITLE
Add postman environment file support while using testkube along with argoCD

### ISSUE THREAD

**Issue by sharmajee1** [kubeshop/testkube#2164]
**Problem Statement** 

Postman tests can be executed on multiple lower environments, for example, dev, stage, uat. We can create an env JSON file dedicated to each env for example, dev_env.json uat_env.json and pass them during the run using `--variables-file` but while using argoCD we don't have such a feature.

**Describe the solution you'd like**
Ability to pass postman environment files while creating tests using argoCD

Currently argoCD usage the testkube plugin to detect test files on a given path, let's detect env files too and add to the test CRD.

We can think of something like

Postman-collection/
mytest.json dev_env_mytest.json uat_env_mytest.json

In the plugin

```
source:
   repoURL: https://github.com/kubeshop/testkube-argocd.git
   targetRevision: HEAD
   path: examples/postman-collections
   plugin:
     name: testkube
     envFiles:
        - common_env.json
        - dev_env_mytest.json
```

**Comment by exu** [comment]
-  use naming converntion 
- update docs with usage example

**Comment by sharmajee1** [comment]
@vsukhin for testkube plugin, internally `testkube generate tests-crds` command will be required `--variables-file` option support, or you are planning some different approaches?

**Comment by sharmajee1** [comment]
Can we also add secret support to the plugin?

```
source:
   repoURL: https://github.com/kubeshop/testkube-argocd.git
   targetRevision: HEAD
   path: examples/postman-collections
   plugin:
     name: testkube
     envFiles:
        - common_env.json
        - dev_env_mytest.json
     secretValues:
        - mySecret:myKey1
        - mySecret:myKey2
```
