### ISSUE TITLE
Add --executor-args support in argocd plugin

### ISSUE THREAD

**Issue by sharmajee1** [kubeshop/testkube#2223]
**Is your feature request related to a problem? Please describe.**
Currently, `testkube generate tests-crds` doesn’t have any option to pass `--executor-args` option.
Add this support so that we can use this in argocd plugin.

**Describe the solution you'd like**
```
source:
   repoURL: https://github.com/kubeshop/testkube-argocd.git
   targetRevision: HEAD
   path: examples/postman-collections
   plugin:
     name: testkube
     extraArgs:
       - '--insecure'
```
