### ISSUE TITLE
Add more flexibility to remove the completed job from cluster

### ISSUE THREAD

**Issue by abhipsnl** [kubeshop/testkube#2254]
**Describe the enhancement you'd like to see**
Currently, `cert-creation` job auto-delete from the cluster because we have this spec `ttlSecondsAfterFinished: 100`
This works perfectly, but the problem comes when we use this with ArgoCD, argocd deducted that job got deleted, and it turns the status to OutOfSync.

```
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: certificate-renewal
```

Either remove this option completely or control `ttlSecondsAfterFinished` based on the condition.
NOTE: if we remove this option, then more `cert-creation-{{ .Release.Revision }}` option will exist in the cluster. We should have some option to remove the older once
