### ISSUE TITLE
provide option to specify pod size while running test to generate specific throughput 

### ISSUE THREAD

**Issue by nizamkhazi87** [kubeshop/testkube#2309]
Testkube automatically create pod with best-effort-kube feature to run test . There is no option to specify test size for pod which we want to use to run k6 performance test . 
This will be a good feature to have to run test and to compete with other performance tool which provide these option .

Solution :

In test or Open API we can pass parameter to create pod with requested resource .

**Comment by vsukhin** [comment]
Hey, @nizamkhazi87 Technically, you can customize job-template,yaml and create a custom excutor on top of existing K6 executor. Just supplying your own job pods attributes. But might be we can allow to change only specifc part of job template

**Comment by TheBrunoLopes** [comment]
AC:
- Allow to add Job specification on the Executor Spec.

**Comment by TheBrunoLopes** [comment]
should be simple

**Comment by TheBrunoLopes** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Testkube-OSS-63739c5c134fcb8abc70c1c1/issues/kubeshop/testkube/2309?planning-poker) with Zenhub @nicufk @pavloburchak @vLia @vsukhin

**Comment by TheBrunoLopes** [comment]
AC:
- Add documentation for the full executor job spec

**Comment by chinthanep** [comment]
If we want to run the pod in another namespace/serviceaccount which is not the namespace/serviceaccount of the testkube installation, how do we do it? Is it supported now?
For example, lets say testkube is installed under testkube namespace and we want to launch a test (job/pod) in another namespace (say: testnamespace).

We tried to modify the namespace in job-template.yaml file, but that doesnt work while running the test.

Modified job-template.yaml:

`apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Name }}
  namespace: **testnamespace**
spec:
  {{- if gt .ActiveDeadlineSeconds 0}}
  activeDeadlineSeconds: {{ .ActiveDeadlineSeconds }}
  {{- end}}
  template:
    metadata:
      namespace: **testnamespace**
    spec:
      initContainers:
      - name: {{ .Name }}-init
        image: {{ .InitImage }}
        imagePullPolicy: Always
        command: 
          - "/bin/runner"
          - '{{ .Jsn }}'
        volumeMounts:
        - name: data-volume
          mountPath: /data 
      containers:
      - name: {{ .Name }}
        image: {{ .Image }}
        imagePullPolicy: Always
        command: 
          - "/bin/runner"
          - '{{ .Jsn }}'
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        emptyDir: {}
      restartPolicy: Never
      {{ if .ServiceAccountName }}
      serviceAccountName: {{ .ServiceAccountName }}
      {{ end }}
      {{- if gt (len .ImagePullSecrets) 0 }}
      imagePullSecrets:
      {{- range $secret := .ImagePullSecrets}}
      - name: {{ $secret -}}
      {{- end}}
      {{- end}}
  backoffLimit: 0
  ttlSecondsAfterFinished: 180
`

The error we get is "⨯ the namespace of the provided object does not match the namespace sent on the request"

**Comment by vsukhin** [comment]
Hey, @chinthanep Testkube doesn't support multiple namespaces at the moment But you don't need to create a test job in your app namespace, because in general case it can affect the service in this namepace. Instead, just call the service in other namespace using full qualified kubenetes name like api-server.namespace.svc.cluster.local

**Comment by chinthanep-asml** [comment]
@vsukhin Then do we have to install testkube in other namespace too? 
If possible, if you could explain that with example/manifest, it would be helpful.

**Comment by vsukhin** [comment]
No,  you don't need.
test CRD
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: testkube-postman-vars
  namespace: testkube
spec:
  type: postman/collection
  content:
    type: string
    data: "{\n\t\"info\": {\n\t\t\"_postman_id\": \"3d9a6be2-bd3e-4cf7-89ca-354103aab4a7\",\n\t\t\"name\": \"Health\",\n\t\t\"schema\": \"https://schema.getpostman.com/json/collection/v2.1.0/collection.json\"\n\t},\n\t\"item\": [\n\t\t{\n\t\t\t\"name\": \"Health\",\n\t\t\t\"event\": [\n\t\t\t\t{\n\t\t\t\t\t\"listen\": \"test\",\n\t\t\t\t\t\"script\": {\n\t\t\t\t\t\t\"exec\": [\n\t\t\t\t\t\t\t\"pm.test(\\\"Status code is 200\\\", function () {\",\n\t\t\t\t\t\t\t\"    pm.response.to.have.status(200);\",\n\t\t\t\t\t\t\t\"});\"\n\t\t\t\t\t\t],\n\t\t\t\t\t\t\"type\": \"text/javascript\"\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t],\n\t\t\t\"request\": {\n\t\t\t\t\"method\": \"GET\",\n\t\t\t\t\"header\": [],\n\t\t\t\t\"url\": {\n\t\t\t\t\t\"raw\": \"{{URI}}/health\",\n\t\t\t\t\t\"host\": [\n\t\t\t\t\t\t\"{{URI}}\"\n\t\t\t\t\t],\n\t\t\t\t\t\"path\": [\n\t\t\t\t\t\t\"health\"\n\t\t\t\t\t]\n\t\t\t\t}\n\t\t\t},\n\t\t\t\"response\": []\n\t\t}\n\t],\n\t\"event\": [\n\t\t{\n\t\t\t\"listen\": \"prerequest\",\n\t\t\t\"script\": {\n\t\t\t\t\"type\": \"text/javascript\",\n\t\t\t\t\"exec\": [\n\t\t\t\t\t\"\"\n\t\t\t\t]\n\t\t\t}\n\t\t},\n\t\t{\n\t\t\t\"listen\": \"test\",\n\t\t\t\"script\": {\n\t\t\t\t\"type\": \"text/javascript\",\n\t\t\t\t\"exec\": [\n\t\t\t\t\t\"\"\n\t\t\t\t]\n\t\t\t}\n\t\t}\n\t],\n\t\"variable\": [\n\t\t{\n\t\t\t\"key\": \"URI\",\n\t\t\t\"value\": \"http://localhost:8080\"\n\t\t}\n\t]\n}"
  executionRequest:
    variables:
      URI:
        name: URI
        value: http://api-server.mynamespace.svc.cluster.local:8080
        type: basic
```
