### ISSUE TITLE
curl executor - git-dir source

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2325]
**Describe the bug**
It's possible to create curl test with `git-dir` type (I checked both dashboard and CRD), but the execution fails with `⨯ unsupported content type use one of: file-uri, git-file, string`

**To Reproduce**
1. Create test:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: curl-healthcheck-repo
  namespace: testkube
spec:
  type: curl/test
  content:
    type: git-dir
    repository:
      type: git-dir
      uri: https://github.com/kubeshop/testkube.git
      branch: main
      path: test/curl

```
2. Run it
4. Check execution logs with both CLI and dashboard.

**Expected behavior**
It should be possible to execute curl tests from git-dir, or it should be blocked. Failure reason should be visible in dashboard (currently only `No logs` is displayed there).

**Version / Cluster**
Client Version 1.5.26
Server Version v1.5.26
