### ISSUE TITLE
"Git file" source - missing test path - inability to execute the test

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2326]
**Describe the bug**
When the test is created from Dashboard with `Git file` Source, the test path is missing.

**To Reproduce**
1. Create a new test from Dashboard
![Screenshot_20220919_222935](https://user-images.githubusercontent.com/1473096/191112274-b9a06f45-da70-4d58-b414-df9ae817b5d3.png)
2. Check test CRD - file path is missing:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: curl-git-file
  namespace: testkube
spec:
  type: curl/test
  content:
    type: git-file
    repository:
      type: git-file
      uri: https://github.com/kubeshop/testkube.git
      branch: main

```
3. Try to run the test - it will fail with:
`⨯ read /tmp/git-checkout1117300775/repo: is a directory`

**Expected behavior**
It should be possible to run the test with `Git file` source, CRD with correct file path should be created.

**Version / Cluster**
Client Version 1.5.26
Server Version v1.5.26

**Additional context**
Checked for Postman and Curl
