### ISSUE TITLE
Bug tests generated using tests-crds are unable to read value from custom secret

### ISSUE THREAD

**Issue by sharmajee1** [kubeshop/testkube#2360]
**Describe the bug**
When I'm creating tests using `tests-crds` command and custom secret, the value is not getting populated.

For example, I have the below reference in my test CRDs.

```
executionRequest:
    variables:
      keyCloakClientSecret:
        name: keyCloakClientSecret
        type: secret
        valueFrom:
          secretKeyRef:
            name: dev-api-tests-secrets
            key: keyCloakClientSecret
            
```
`dev-api-tests-secrets` secret is created manually.

But when I create these tests using normal CLI, all works fine.

```
testkube create test --name test -f postman_collection.json --type postman/collection --variables-file postman_environment.json -s keyCloakClientSecret=** --executor-args --insecure
```

**To Reproduce**
Steps to reproduce the behaviour:
Sample YAML can be downloaded from discord
https://discord.com/channels/884464549347074049/1022749733770498138/1022754677277855794
