### ISSUE TITLE
Cypress executors - ENV variables aren't set inside the containers

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2437]
**Describe the bug**
ENV variables aren't set inside the containers for cypress executors (both official image-based, and "legacy" one) 

**To Reproduce**
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: cypress-10-executor-smoke-chrome
  namespace: testkube
spec:
  type: cypress:v10/test
  content:
    type: git-dir
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube
      branch: cypress-envs
      path: test/cypress/executor-smoke/cypress-10
  executionRequest:
    variables:
      CYPRESS_CUSTOM_ENV:
        name: CYPRESS_CUSTOM_ENV
        value: CYPRESS_CUSTOM_ENV_value
        type: basic
    args:
      - run --env NON_CYPRESS_ENV=NON_CYPRESS_ENV_value
```
"CYPRESS_CUSTOM_ENV" ENV isn't set inside the container

**Additional info**
```
kubectl describe test cypress-10-executor-smoke-chrome -ntestkube
W0930 15:46:48.178375   98912 gcp.go:119] WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.26+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
Name:         cypress-10-executor-smoke-chrome
Namespace:    testkube
Labels:       <none>
Annotations:  <none>
API Version:  tests.testkube.io/v3
Kind:         Test
Metadata:
  Creation Timestamp:  2022-09-30T13:17:00Z
  Generation:          1
  Managed Fields:
    API Version:  tests.testkube.io/v3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:content:
          .:
          f:repository:
            .:
            f:branch:
            f:path:
            f:type:
            f:uri:
          f:type:
        f:executionRequest:
          .:
          f:args:
          f:variables:
            .:
            f:CYPRESS_CUSTOM_ENV:
              .:
              f:name:
              f:type:
              f:value:
        f:type:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2022-09-30T13:17:00Z
  Resource Version:  26589670
  UID:               b0f5760c-65ee-4bae-8b9d-133c0df54a8b
Spec:
  Content:
    Repository:
      Branch:  cypress-envs
      Path:    test/cypress/executor-smoke/cypress-10
      Type:    git
      Uri:     https://github.com/kubeshop/testkube
    Type:      git-dir
  Execution Request:
    Args:
      run --env NON_CYPRESS_ENV=NON_CYPRESS_ENV_value
    Variables:
      CYPRESS_CUSTOM_ENV:
        Name:   CYPRESS_CUSTOM_ENV
        Type:   basic
        Value:  CYPRESS_CUSTOM_ENV_value
  Type:         cypress:v10/test
Events:         <none>
```
kubectl exec to the pod and:
```
# printenv|grep CYPRESS
#
```

**Expected behavior**
ENVs should be correctly set inside the containers

**Version / Cluster**
```
Client Version 1.5.39
Server Version v1.5.39
```

**Comment by tkonieczny** [comment]
https://github.com/kubeshop/testkube/blob/cypress-envs/test/cypress/executor-smoke/crd/crd.yaml here is my branch with Cypress Test CRDs with both ENV variables and cypress --env params. I also updated the Cypress executor tests there, so they will validate these values

**Comment by vsukhin** [comment]
printenv will not show test vars, becuase we pass them with running cypress --env option

**Comment by vsukhin** [comment]
Would be great to see what env was passed to Cypress script

**Comment by vsukhin** [comment]
So, below test:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: cypress-executor-env-only-vars
  namespace: testkube
spec:
  type: cypress/project
  content:
    type: git-dir
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube
      branch: vsukhin/fix/cypress-env-vars
      path: test/cypress/executor-smoke/cypress-10
  executionRequest:
    variables:
      CYPRESS_CUSTOM_ENV:
        name: CYPRESS_CUSTOM_ENV
        value: CYPRESS_CUSTOM_ENV_value
        type: basic
      NON_CYPRESS_ENV:
        name: NON_CYPRESS_ENV
        value: NON_CYPRESS_ENV_value
        type: basic
```

for 
```
describe('Testkube website', () => {
  it('Open Testkube website', () => {
    cy.visit('/')
  })
  it(`Validate CYPRESS_CUSTOM_ENV ENV (${Cypress.env('CYPRESS_CUSTOM_ENV')})`, () => {
    expect('CYPRESS_CUSTOM_ENV_value').to.equal(Cypress.env('CYPRESS_CUSTOM_ENV')) //CYPRESS_CUSTOM_ENV - "cypress" prefix - auto-loaded from global ENVs
  })
  it(`Validate NON_CYPRESS_ENV ENV (${Cypress.env('NON_CYPRESS_ENV')})`, () => {
    expect('NON_CYPRESS_ENV_value').to.equal(Cypress.env('NON_CYPRESS_ENV')) //NON_CYPRESS_ENV - need to be loaded with --env parameter
  })
})

```

completed as
```

       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  dummy_test.cy.js                         00:12        3        3        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        00:12        3        3        -        -        -  


Status Test execution completed with success 🥇

```
