### ISSUE TITLE
Cypress executors (official Cypress image-based) - color codes make the output completely unreadable

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2439]
**Describe the bug**
Cypress executor output is completely unreadable in Dashboard, and with `kubectl logs`.

There is already an enhancement issue for displaying colored output in dashboard: https://github.com/kubeshop/testkube/issues/1992 But, right now this executor is almost unusable because of the color codes.

**Screenshots**
![Screenshot 2022-09-30 at 16-16-33 Testkube](https://user-images.githubusercontent.com/1473096/193290481-4556988f-cb8b-4518-ac68-5709a421e143.png)
![Screenshot_20220930_161909](https://user-images.githubusercontent.com/1473096/193290555-5f0b6a18-0092-4c76-8a9f-15a5052e2af0.png)

**To Reproduce**
1. Run any Cypress test with new, Cypress image-based executor - for example:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: cypress-10-executor-smoke-electron
  namespace: testkube
spec:
  type: cypress:v10/test
  content:
    type: git-dir
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube
      branch: cypress-envs
      path: test/cypress/executor-smoke/cypress-10
  executionRequest:
    variables:
      CYPRESS_CUSTOM_ENV:
        name: CYPRESS_CUSTOM_ENV
        value: CYPRESS_CUSTOM_ENV_value
        type: basic
    args:
      - run --env NON_CYPRESS_ENV=NON_CYPRESS_ENV_value
```
2. Check execution output with Dashboard, or with kubectl logs

**Expected behavior**
Output should be easily readable, color support is optional.

**Version / Cluster**
Client Version 1.5.39
Server Version v1.5.39
