### ISSUE TITLE
Create a ingress with single load balance while using EKS and aws ingress controller

### ISSUE THREAD

**Issue by mirwasim** [kubeshop/testkube#2448]
We are using testkube in EKS, and instead of nginx we are using aws ingress controller.
I had ingress working fine with one load balancer when you have dashboard listening at port 80, but now when you have changed port from 80 to 8080 I am not seeing the ingress working.

To resolve this we have to separate services in two ingresses, which use two load balancers and both have different health check ports , and annotation in aws doesn't allow to have 2 ports together in one ingress.

Earlier I had it working with port 80 as shown below:
````
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testkube-private-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: testkube-private-api
    alb.ingress.kubernetes.io/load-balancer-name: testkube-private-api
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: "8088"
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/tags: Environment=testkube,ManagedWith=k8-alb-controller,Name=testkube-private-api

spec:
  rules:
 - host: app-testkube.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testkube-dashboard
            port:
              number: 80
 - host: api.testkube.domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: testkube-api-server
            port:
              number: 8088
```

Now to make it work I have to create two separate ingresses with health check port 8080 and  8088  and path / and /health respectively

Expected result:

To create two ingresses with only one load balancer in single ingress.yaml  file as before and health check for both of the targets should pass, or you can create a better way to create ingress with aws ingress controller where we do not have to use more than 1 load balancer.

**Comment by ypoplavs** [comment]
Hello @mirwasim!

Could you please try to add `healthcheck-path` and `healthcheck-port` annotations to `Service` manifest and leave `Ingress` like the following:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testkube-ingress-internal
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: testkube-api-internal
    alb.ingress.kubernetes.io/load-balancer-name: testkube-api-internal
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/tags: Environment=testkube,ManagedWith=k8-alb-controller,Name=testkube-private-api

spec:
  rules:
  - host: dash-internal.aws.testkube.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: testkube-dashboard
              port:
                number: 8080
  - host: api-internal.aws.testkube.io
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: testkube-api-server
              port:
                number: 8088
```

Service for `API`:

```
apiVersion: v1
kind: Service
metadata:
  name: testkube-api-server
  labels:
    app.kubernetes.io/instance: testkube
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-server
    app.kubernetes.io/version: 1.6.9
    helm.sh/chart: testkube-api-1.6.9
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/successCodes: "200"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
    alb.ingress.kubernetes.io/healthcheck-port: "8088"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '30'
    alb.ingress.kubernetes.io/healthy-threshold-count: '5'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=300
spec:
  type: ClusterIP
  ports:
    - port: 8088
       targetPort: http
       protocol: TCP
       name: http
  selector:
    app.kubernetes.io/instance: testkube
    app.kubernetes.io/name: api-server
```

Service for `dashboard`:

```
apiVersion: v1
kind: Service
metadata:
  name: testkube-dashboard
  labels:
    app.kubernetes.io/instance: testkube
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dashboard
    app.kubernetes.io/version: 1.6.0
    helm.sh/chart: testkube-dashboard-1.6.0
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/successCodes: "200"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '60'
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '30'
    alb.ingress.kubernetes.io/healthy-threshold-count: '5'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '3'
    alb.ingress.kubernetes.io/target-group-attributes: deregistration_delay.timeout_seconds=300
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
     app.kubernetes.io/instance: testkube
     app.kubernetes.io/name: dashboard
```

This way ingress controller will create 1 Load Balancer with 2 Target Groups that will be performing checks for `api` and `dashboard` targets.

Please let us know about the results!
