### ISSUE TITLE
Dashboard - ENVs matching non-string types - incorrect Test CRDs are generated/displayed

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2451]
**Describe the bug**
ENV variables matching non-string types added through Dashboard result in incorrect CRDs

**To Reproduce**
1. Create any test
2. Go to dashboard, and add ENV variable ("Basic") matching non-string type - for example boolean - `true`, or `false`
![Screenshot_20221003_203450](https://user-images.githubusercontent.com/1473096/193654981-3ae8da52-e690-4a4b-8e44-462f3d97a589.png)

4. Go to Definition and check variables
![Screenshot_20221003_203504](https://user-images.githubusercontent.com/1473096/193655055-0dede889-c590-4939-9f93-c142900ae849.png)
5. Try to apply this definition
```
Error from server (Invalid): error when creating "test/maven/executor-smoke/crd/crd.yaml": Test.tests.testkube.io "maven-executor-smoke-jdk8" is invalid: spec.executionRequest.variables.env-name.value: Invalid value: "boolean": spec.executionRequest.variables.env-name.value in body must be of type string: "boolean"
```

**Expected behavior**
Any ENV variable should be a string - even `true`, or `false`, all (?) ENVs should be added to definition with `"` characters.

**Version / Cluster**
```
Client Version 1.5.43
Server Version v1.5.43
```

**Comment by tkonieczny** [comment]
Second case - creating a test from correct CRD:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: maven-executor-smoke-jdk8
  namespace: testkube
spec:
  type: maven:jdk8/test
  content:
    type: git-dir
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube-executor-maven.git
      branch: main
      path: examples/hello-maven
  executionRequest:
    variables:
      TESTKUBE_MAVEN:
        name: TESTKUBE_MAVEN
        value: "true"
        type: basic
```
result in displaying incorrect ENV value (without `"` characters) in CRD
