### ISSUE TITLE
SoapUI executor - git-file - `could not start process: exec: "git": executable file not found in $PATH`

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2472]
**Describe the bug**
It's not possible to run SoapUI tests from `git-file` - execution fail with `could not start process: exec: "git": executable file not found in $PATH` error.

**To Reproduce**
1. Create SoapUI test from git-file - for example using this Test CRD:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: soapui-executor-smoke
  namespace: testkube
spec:
  type: soapui/xml
  content:
    type: git-file
    repository:
      type: git-file
      uri: https://github.com/kubeshop/testkube.git
      branch: soapui-executor-tests
      path: test/soapui/executor-smoke/soapui-smoke-test.xml
```
2. Run the test
3. The test isn't executed: `could not start process: exec: "git": executable file not found in $PATH`

**Expected behavior**
The test should be run correctly.

**Version / Cluster**
Client Version 1.6.3
Server Version v1.6.3
