### ISSUE TITLE
Test CRD - outdated validation rules when combined with TestSource

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2560]
**Describe the bug**
Test CRD validation rules are outdated - Test.spec.content.repository type, and repository are required even if TestSource is used.

**To Reproduce**
1. Try to create TestSuite and Test from CRDs:
```
# cypress-default-executor-smoke-electron-testsource-git-dir - TestSource
apiVersion: tests.testkube.io/v1
kind: TestSource
metadata:
  name: testsource-cypress-default-executor-smoke-electron-testsource-git-dir
  namespace: testkube
spec:
  type: git-dir
  repository:
    type: git
    uri: https://github.com/kubeshop/testkube.git
    branch: main
---
# cypress-default-executor-smoke-electron-testsource-git-dir - Test
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: cypress-default-executor-smoke-electron-testsource-git-dir
  namespace: testkube
spec:
  type: cypress/project
  content:
    repository:
      path: test/cypress/executor-smoke/cypress-10
  source: testsource-cypress-default-executor-smoke-electron-testsource-git-dir
```
2. Test creation fails on validation:
```
testsource.tests.testkube.io/testsource-cypress-default-executor-smoke-electron-testsource-git-dir created
error: error validating "test/cypress/executor-smoke/crd/crd.yaml": error validating data: [ValidationError(Test.spec.content.repository): missing required field "type" in io.testkube.tests.v3.Test.spec.content.repository, ValidationError(Test.spec.content.repository): missing required field "uri" in io.testkube.tests.v3.Test.spec.content.repository]; if you choose to ignore these errors, turn validation off with --validate=false
```

**Expected behavior**
It should be possible to create a test without disabling validation.

**Version / Cluster**
Client Version 1.6.17
Server Version v1.6.17
