### ISSUE TITLE
workingDir not changed in container based executors

### ISSUE THREAD

**Issue by andrei-n-cosma** [kubeshop/testkube#2683]
When running a container based executor the working directory isn't changed to the one specified in test.

Having following test:

```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: testkube-action-e2e-tests
  namespace: testkube
spec:
  content:
    repository:
      type: git-dir
      uri: 'https://url-to-repo/actions.git'
      workingDir: testkube
    type: git-dir
  executionRequest:
    args:
      - '-e e2e'
  type: tox/tests
```

I expect when (custom) executor is running to have it's workingDir changed to `/data/repo/testkube`, unfortunately that's not the case. Here's the output which executor gives me:
```
{"type":"event","content":"running test [636a8f094984ee41ab5d9133]"}
{"type":"line","content":"created content path: /data/repo/"}
{"type":"result","result":{"status":"running"}}
<-- here I get the env for working directory and seems is the one set in the Dockerfile by default -->
PWD=/home/py/app

<-- of course working directory is empty ... -->
drwxrwxrwx. 2 py py  6 Sep 14 08:08 .
drwxr-xr-x. 1 py py 34 Sep 14 08:16 ..

<-- following is the list of /data/repo -->
drwxrwxrwx. 8 root root 122 Nov  8 17:16 .
drwxrwxrwx. 3 root root  18 Nov  8 17:16 ..
drwxrwxrwx. 8 root root 178 Nov  8 17:16 .git
drwxrwxrwx. 2 root root  42 Nov  8 17:16 testkube
...
```

Seems that workingDir (from the test definition) is not set as workingDir of executor container.

Testkube: 1.6.95
