### ISSUE TITLE
Container Executor: Retain full JSON-log, so I can analyse failures

### ISSUE THREAD

**Issue by TheLeanMachine** [kubeshop/testkube#2699]
**Describe the bug**
When I use a container executor, I face the problem that **the log out put** is generated but **lost when I refresh the browser** (from which I guess: the output is not persisted...).
![Screenshot_2022-11-09_at_12 42 29](https://user-images.githubusercontent.com/3470837/201113242-a66d2221-e180-4964-8353-7a07f1c23440.png)

This might prevent proper error analysis!

According to @vsukhin, this is _caused by the test process' output not being wrapped in JSON_.

But: When I do so...
![Screenshot 2022-11-10 at 14 21 20](https://user-images.githubusercontent.com/3470837/201113195-6f97d395-1eac-411d-bb28-28bd2f8baead.png)
...**the first log lines are still lost**!

**To Reproduce**
Define a container executor (for example like this):
```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: cypress-included-executor
  namespace: testkube
spec:
  image: cypress/included:9.7.0
  command: ["/bin/bash",
            "-c",
            "apt-get -y install jo &> /dev/null; function wrapInJson { while IFS= read -r inputLine || [ -n \"$inputLine\" ]; do jo type=line content=\"$inputLine\"; done < ${1:-/dev/stdin}; }; cd /data/repo &> /dev/null; npm install 2>&1 | wrapInJson; echo 'here I would call Cypress, now....'; "]
  executor_type: container
  types:
    - cypress-included/project
```

Then run the test.
Acknowledge, that the inintial log output is still lost:
![Screenshot 2022-11-10 at 14 21 20](https://user-images.githubusercontent.com/3470837/201112467-ff896c56-ce44-4192-8462-3fbaea9bcec6.png)

**Expected behavior**
When I refresh the browser **I see the full log**, not only the last N lines...

**Version / Cluster**
- Which testkube version? Client Version `1.6.30`, Server Version `v1.6.30`
- What Kubernetes cluster? AWS EKS
- What Kubernetes version? v1.22.13-eks-15b7512

**Comment by exu** [comment]
We could just fallback to `type:line` when there is no JSON output it would give us all log lines (currently only JSON output is parsed by API orchestrator).

**Comment by TensShinet** [comment]
Hi, is this problem solved? I also can't get all logs when I use `kubectl testkube get execution <execution_id>`.

**Comment by vsukhin** [comment]
Hey @TensShinet We're planning to work on it in current release

**Comment by nicufk** [comment]
Hey @TheLeanMachine, @TensShinet do you have an example that you can share where you can reproduce it with the latest version?

**Comment by TheLeanMachine** [comment]
Sorry @nicufk , not working at that company, any more.

**Comment by TensShinet** [comment]
Ok, please wait for a while. I'll try it again. If I reproduce it again, I will give you an example.

**Comment by TensShinet** [comment]
Client Version 1.9.13
Server Version v1.9.13

1. Write a simple test file in Go.:

```go
package testkube_test

import (
	"testing"
	"time"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

func TestAPIs(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Test Testkube Suite")
}

var _ = Describe("Log Length", func() {
	It("test1", func() {
		for i := 0; i < 2000; i++ {
			GinkgoWriter.Printf("test1 line i:%v \n", i)
		}
		time.Sleep(10 * time.Second)
		for i := 0; i < 2000; i++ {
			GinkgoWriter.Printf("test1 line i:%v \n", i+2000)
		}
	})
})

```

Local result:

```
  test1 line i:0
  test1 line i:1
  test1 line i:2
  test1 line i:3
  test1 line i:4
  test1 line i:5
  test1 line i:6
  test1 line i:7
  test1 line i:8
  test1 line i:9
  test1 line i:10
  test1 line i:11
  test1 line i:12
...
```
2. Write a Dockerfile for the container executor:

```dockerfile
FROM golang:1.18
RUN go install github.com/onsi/ginkgo/v2/ginkgo@v2.8.1
COPY api_test.go go.mod go.sum /app/
ENV PATH="$PATH:/usr/local/go/bin:/go/bin"
ENV CGO_ENABLED=0
WORKDIR /app
CMD ["ginkgo"]
```

3. Create an executor:

```yaml
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: testkube-test-executor
  namespace: testkube
spec:
  image: XXXXX(build from Dockerfile)
  command: ["ginkgo"]
  executor_type: container
  types:
    - testkube-test/test
```
4. Create a test:

```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: testkube-test-2699
  namespace: testkube
spec:
  type: testkube-test/test
  executionRequest:
    args:
      - run
      - --no-color
      - -vv
      - ./
```

5. Run this test in the testkube and get the result:

![image](https://user-images.githubusercontent.com/35733911/219851590-86e327f3-56a3-4d80-b5d0-39ce44b3176c.png)

The start line is `test1 line i:3910`, which means I can't get the whole log.
