### ISSUE TITLE
Ginkgo executor - `could not initialize runner: required key RUNNER_GITUSERNAME missing value`

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#2772]
**Describe the bug**
Ginkgo executor fail to start the tests with `could not initialize runner: required key RUNNER_GITUSERNAME missing value`. Git username should be optional.

**To Reproduce**
1. Create test:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: example-ginkgo-test
  namespace: testkube
spec:
  type: ginkgo/test
  content:
    type: git-file
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube.git
      branch: ginkgo-executor-tests
      path: test/ginkgo/executor-tests/ginkgo-smoke.go
```
2. Try to run the test
3.
```
Status test execution failed:

⨯ could not initialize runner: required key RUNNER_GITUSERNAME missing value
```

**Expected behavior**
The test should be started correctly even if git username isn't set

**Version / Cluster**
Client Version 1.7.5
Server Version v1.7.5
