### ISSUE TITLE
'chmod: .: Operation not permitted' running simple test on OpenShift

### ISSUE THREAD

**Issue by sebagomez** [kubeshop/testkube#2800]
I created a simple bash executor as follows:

```yaml
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: bash-executor
  namespace: ops
spec:
  image: quay.io/openshift/origin-cli:4.7
  command: ["bash"]
  executor_type: container
  types:
  - bash-origin-cli/test
```

And I have simple test

```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: simple-test
  namespace: ops
spec:
  type: bash-origin-cli/test
  executionRequest:
    args:
    - echo "hello world!"

```

The problem is, when I run the test it fails with the following output
```json
{"type":"event","content":"running test [637fb1f8de2c89f221a10eee]"}
{"type":"line","content":"chmod: .: Operation not permitted\nchmod: .: Operation not permitted\n"}
{"type":"error","content":"process error: exit status 1"}
```

For what I've seen that's a problem with the ServiceAccount used by the Job creating the Pods to run the tests.
I do have a ServiceAccount I can use, but I have changed every possible entry under the values file (I'm using Helm to deploy) but nothing seems to change. The ServiceAccount used by the Job is still `default`.

What would be the right entry on the values file?
