### ISSUE TITLE
process error: exit status 128\noutput: Cloning into 'repo'...\nwarning: url contains a newline in its username component

### ISSUE THREAD

**Issue by sebagomez** [kubeshop/testkube#2825]
I created the following test

```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: dummy-git-test
  namespace: ops
spec:
  type: git-bash-cli/test
  content:
    type: git-dir
    repository: 
      branch: main
      path: my/path
      type: git-dir
      uri: https://myrepo.url
      tokenSecret:
        name: git-token-secret
        key: token
        namespace: ops
      usernameSecret:
        name: git-user-secret
        key: user
        namespace: ops
```

The problem is, when I try to execute it I get the following error:

```json
{"type":"event","content":"running test [6387d467b6ced44205b0e273]"}
{"type":"error","content":"process error: exit status 128\noutput: Cloning into 'repo'...\nwarning: url contains a newline in its username component: https://user%0A:token%0A@myrepo.url/\nfatal: credential url cannot be parsed: https://user%0A:token%0A@myrepo.url/\n"}
```

Notice the `%0A` after the username and the token, that's NOT part of the actual username or token.

**Comment by vsukhin** [comment]
Hey, @sebagomez Not sure, how you submitted user and token values. Did you use cli or UI? Most likely UI, can you try CLI command then?

**Comment by sebagomez** [comment]
Ok, so I added fake user and token secrets so you can see what I mean. The token and the username are strings that I encoded using the mac's base64 utility.

Here are my secrets

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: git-user-secret
  namespace: ops
type: Opaque
data:
  user: dGhpcyBpcyB0aGUgdXNlcgo=
---
apiVersion: v1
kind: Secret
metadata:
  name: git-token-secret
  namespace: ops
type: Opaque
data:
  token: dGhpcyBpcyB0aGUgdG9rZW4K
```

Now this is the error I get 

```json
{"type":"event","content":"running test [6388b883b6ced44205b0e275]"}
{"type":"error","content":"process error: exit status 128\noutput: Cloning into 'repo'...\nwarning: url contains a newline in its username component: https://this%20is%20the%20user%0A:this%20is%20the%20token%0A@myrepo.url/\nfatal: credential url cannot be parsed: https://this%20is%20the%20user%0A:this%20is%20the%20token%0A@myrepo.url/\n"}
```
