### ISSUE TITLE
Scheduled tests not running at the right time

### ISSUE THREAD

**Issue by sebagomez** [kubeshop/testkube#2880]
I have tried scheduling my tests to run every 12 hours (`0 */12 * * *`) and every 6 hours (`0 */6 * * *`) and in both cases I see tests running every ten minutes.

Is there anything wrong with my cron expression or a bug in the operator?

Cron expressions were validates by https://crontab.guru/#0_*/6_*_*_*

**To Reproduce**
```yaml 
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: dummy-git-test
  namespace: ops
  labels:
    testkube.feature: test
spec:
  type: git-bash-cli/test
  schedule: 0 */6 * * *
  content:
    type: git-dir
    repository: 
      branch: main
      path: /
      type: git-dir
      uri: https://gitlab.com/yadayadayada
      tokenSecret:
        name: git-access-secret
        key: token
        namespace: ops
      usernameSecret:
        name: git-access-secret
        key: user
        namespace: ops
```

**Version / Cluster**
- Which testkube version? 1.7.28
- What Kubernetes cluster? OpenShift 4.10
- What Kubernetes version? v1.23.5+012e945

**Screenshots**
![image](https://user-images.githubusercontent.com/1637983/206558261-9f0aed55-c366-45d9-b7ba-1459fd31c50c.png)
