### ISSUE TITLE
Question: Why do the test suite crd's have a namespace option in execute if it can only execute tests within the "testkube" namespace

### ISSUE THREAD

**Issue by scott-david-walker** [kubeshop/testkube#2918]
Given this example - what's the purpose of the namespace property given that the tests can only be found in the "installed" namespace?

```yaml
spec:
  steps:
  - delay:
      duration: 15000
      
  - execute:
      namespace: testkube
      name: test1
      stopOnFailure: false
      
  - execute:
      namespace: another-namespace
      name: test2
      stopOnFailure: false
```

It would be awesome if we can actually place tests/testsuites in separate namespaces but my understanding is that this isn't currently possible. Is this on the horizon by chance?
