### ISSUE TITLE
Unable to use non-root path for dashboard

### ISSUE THREAD

**Issue by hobti01** [kubeshop/testkube#2952]
**Describe the bug**
The testkube dashboard is not available when the ingress path is not `/`

**To Reproduce**
Using the testkube Helm Chart
* Set values
```yaml
testkube-dashboard:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - myhost.example.com
    path: /test-svc
```
* Deploy the chart
* Access http://myhost.example.com/test-svc
* Observe blank page.  The app is loaded, but receives a 404 attempting to load `env-config.js` (and other files) and therefore does not recognise the non-root path.

**Expected behavior**
Expected app to load, as it does when configured for the domain root path

**Version / Cluster**
- Which testkube version? 1.8.8
- What Kubernetes cluster? EKS
- What Kubernetes version? 1.22

**Screenshots**
<img width="609" alt="image" src="https://user-images.githubusercontent.com/4631304/209360513-1e7c135d-0b0e-44fc-b99a-0405d498f702.png">
 
**Additional context**
This issue was raised previously https://github.com/kubeshop/testkube/issues/2362 and code was added, but I don't see how the code can function since it sets values in `env-config.js` which the app attempts to download from the root.

**Comment by vsukhin** [comment]
Thank yuo @hobti01 We will our frontend team @pavloburchak to check it out

**Comment by Toxer10** [comment]
@hobti01 Sorry for answer this late. We discussed the implementation of this feature, and it seems to be very complex. Just to make sure, is this still relevant to you?

**Comment by hobti01** [comment]
Hi @Toxer10 , yes - it's not as simple as it seems :)

This does remain important for us.  I'll check with our team if we have any suggestions.

**Comment by nicufk** [comment]
Hey @hobti01, can you check the testkube-dashboard deployment if it has REACT_APP_ROOT_ROUTE configured with your ingress path?

**Comment by hobti01** [comment]
Yes, it is set within the running image to the same value as `.ingress.path`

**Comment by rangoo94** [comment]
Looking at the code, adding `<base>` tag for the front-end should solve all/most of the problems.

**Comment by djonesz** [comment]
Is there any update or workaround for this? I just ran into this today.
Thanks!

**Comment by rangoo94** [comment]
Hi @djonesz! Unfortunately, we didn't touch it yet. We will discuss it today to provide some estimations.

**Comment by rangoo94** [comment]
Hi @djonesz! At the moment we've got multiple ongoing things with higher priority, but I will work on this issue in the next week. I will keep you informed there 🙂

**Comment by djonesz** [comment]
@rangoo94 much appreciated, thank you!

**Comment by rangoo94** [comment]
The fix has landed in `v1.13.0`. You may run `testkube upgrade` command to install the latest version.

**Comment by Carlosgova** [comment]
Hi,
@rangoo94 , I've updated to v1.13.0 version of testkube-dashboard but I'm still facing the issue reported. The testkube-dashboard deployment has set var REACT_APP_ROOT_ROUTE set correctly.

Thanks!

**Comment by rangoo94** [comment]
Hi @Carlosgova! Sorry, just tested it once again and it's actually not working. I should fix it shortly though 👍

**Comment by hobti01** [comment]
@rangoo94 it's the absolute links in the html which defeat the `base href`
```html
<!doctype html>
<html lang="en">
    <head>
        <base href="/test-svc">
        <meta charset="utf-8"/>
        <link rel="icon" href="/favicon.png"/> <------ 404
        <meta name="viewport" content="width=device-width,initial-scale=1"/>
        <meta name="description" content="The Kubernetes Native Test Orchestration and Execution Framework"/>
        <meta name="referrer" content="no-referrer"/>
        <meta name="app-version" content="1.13.0"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link rel="preload" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&family=Roboto+Mono&display=swap" as="style" onload='this.onload=null,this.rel="stylesheet"'/>
        <link rel="manifest" href="/manifest.json"/> <------ 404
        <title>Testkube</title>
        <script src="/env-config.js"></script> <------ 404
        <script defer="defer" src="/static/js/main.abaf16d5.js"></script> <------ 404
        <link href="/static/css/main.e325d506.css" rel="stylesheet"> <------ 404
    </head>
    <body>
        <noscript>You need to enable JavaScript to run this app.</noscript>
        <div id="root"></div>
    </body>
</html>
```

**Comment by rangoo94** [comment]
The hotfix has been released in the newest version, you may run `testkube upgrade` command to install the latest version. Sorry for the inconvenience, this time I have verified it twice 👍

**Comment by djonesz** [comment]
I had to override the REACT_APP_ROOT_ROUTE (using extraEnvVars in the helm chart), because my nginx ingress needed a rewrite rule set in place.

I also needed to force the image to use latest in my values file, since I'm using the helm chart.

But after I did that, the dashboard is working!

It might be worth looking at how redirects can work without setting REACT_APP_ROOT_ROUTE, but I'm happy for now.

Here's the example bits from testkube-dashboard:
```yaml
testkube-dashboard:
  extraEnvVars:
    - name: "REACT_APP_ROOT_ROUTE"
      value: "/my/path/"
  image:
    tag: "latest"
  ingress:
    enabled: "true"
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /my/path/(.*)
    hosts:
      - your-host.com
    tlsenabled: "false"
```

Thanks!
