### ISSUE TITLE
Outdated crd genaration forTestsuite

### ISSUE THREAD

**Issue by vsukhin** [kubeshop/testkube#2959]
**Describe the bug**
Outdated crd genaration forTestsuite

**To Reproduce**
1. Run 'kubectl testkube get testsuite <name>'
2. Specify '--crd-only'
3. See error old field stopTestOnFailure

**Expected behavior**
 stopTestOnFailure rename to stopOnFailure in CRD package for Test Suite

**Version / Cluster**
- Which testkube version? 1.8.10
- What Kubernetes cluster? local KinD
- What Kubernetes version? 1.22.3

**Comment by f-helm** [comment]
To add, from my testing just renaming it should not be enough, it has to be moved into the `execute` field, like this:
```
apiVersion: tests.testkube.io/v2
kind: TestSuite
metadata:
  name: test-testsuite
  namespace: custom-ns
spec:
  description: "some description"
  steps:
  - execute:
      namespace: custom-ns
      name: run-some-tests
      stopOnFailure: false
```
