### ISSUE TITLE
Role testkube-operator-leader-election-role is missing since testkube version 1.7

### ISSUE THREAD

**Issue by crdnb** [kubeshop/testkube#2990]
**Describe the bug**
Role "testkube-operator-leader-election-role" is missing since testkube version 1.7. It was there with version 1.6.

So the container "manager" of the pod "testkube-operator-controller-manager" is throwing an error:

`E0105 12:50:27.101292 1 leaderelection.go:334] error initially creating leader election record: leases.coordination.k8s.io is forbidden: User "system:serviceaccount:col-testkube-test:testkube-operator-controller-manager" cannot create resource "leases" in API group "coordination.k8s.io" in the namespace "col-testkube-test"`

**To Reproduce**
```
❯ helm template kubeshop/testkube --namespace col-testkube-test   --version 1.7 | grep testkube-operator-leader-election-role
  name: testkube-operator-leader-election-role

```
```
❯ helm template kubeshop/testkube --namespace col-testkube-test   --version 1.6 | grep testkube-operator-leader-election-role
  name: testkube-operator-leader-election-role
  name: testkube-operator-leader-election-rolebinding
  name: testkube-operator-leader-election-role
```

**Expected behavior**
Include it in the helm chart again.

**Version / Cluster**
- Which testkube version? all above 1.6

**Comment by ypoplavs** [comment]
Hi @crdnb, 
I went through the charts and I see that role `testkube-operator-leader-election-role` is present as well as `testkube-operator-leader-election-rolebinding`. 
Could you please update our chart version to the latest version and let me know about the results? It's `1.8.54`

**Comment by crdnb** [comment]
Hi @ypoplavs 

I guess I found the failure. Within the roleRef of the RoleBinding, the variable {{ .Release.Name }} is missing at the beginning of the Role name:

```
apiVersion: {{ include "global.capabilities.rbac.apiVersion" . }}
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-operator-leader-election-rolebinding
  labels:
  {{- if .Values.global.labels }}
  {{- include "global.tplvalues.render" ( dict "value" .Values.global.labels "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if .Values.global.annotations }}
  annotations: {{- include "global.tplvalues.render" ( dict "value" .Values.global.annotations "context" $ ) | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: testkube-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "testkube-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
```

That's why the Role is not found.
