### ISSUE TITLE
CDEvent Test Triggers

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#2991]
I would Testkube to run specific Tests or Testsuites when receiving certain CDEvents defined at https://cdevents.dev/docs/ 

For each trigger I want to configure
- `subject` - which CDEvent subject to listen for
- `predicate(s)` - which corresponding predicate(s) to listen for
- custom fields - which custom fields/values to listen for - some kind of wildcard/regex syntax should be supported
- target test/testSuite - which Test or TestSuite to run
- parameters - parameter values to pass to the target Test or TestSuite - an added bonus would be if a value could be extracted from one of the incoming fields.

For example

```yaml
cdevent-trigger:
  subject: service
  predicates:
    - deployed
  fields:
     - name: id
       value: service/petstore
```
