### ISSUE TITLE
An aws plugin used for authenticating to EKS clusters,needs to be installed into the docker image Testkube is running in.

### ISSUE THREAD

**Issue by richamishra006** [kubeshop/testkube#3004]
An aws plugin used for authenticating to EKS clusters, which needs to be installed into the docker image Testkube is running in.
getting this error with my github workflow

![image](https://user-images.githubusercontent.com/77951560/211477234-c14f63f2-71a8-4c3a-a030-ec0f57f51d15.png)

This is my github worflow
```
name: Testkube Docker Action

on:
  push:
    branches:
      - master

env:
  DEPLOYMENT_NAME: hello-kubernetes-deployment # Add your deployment name here.
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  CLUSTER_NAME: test-1
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
jobs:
  job_1:
    name: test workflow for AWS 
    runs-on: ubuntu-latest

    steps:
    - name: AWS cli install action
      uses: chrislennon/action-aws-cli@1.1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  
    - name: kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
    - name: Upload kubeconfig file
      uses: actions/upload-artifact@v3
      with: 
        name: kubeconfig
        path: /home/runner/.kube/config
    - shell: bash
      run: |
        cat $HOME/.kube/config
        
  job_2:
    name: create test using testkube
    needs: job_1
    runs-on: ubuntu-latest  
    steps:
    - name: Download kubeconfig from job 1
      uses: actions/download-artifact@v3
      with:
       name: kubeconfig
    - shell: bash
      run: |
        export KUBECONFIG=/home/runner/work/testkube-test/testkube-test/config
    - name: Create test
      id: create_test
      uses: kubeshop/testkube-docker-action@v1
      env:
        KUBECONFIG: /home/runner/work/testkube-test/testkube-test/config
        KUBERNETES_MASTER: /home/runner/work/testkube-test/testkube-test/config
      with:
        command: create
        resource: test
        namespace: testkube
        parameters: "--type k6/script --name testkube-github-action"
        stdin: "import http from 'k6/http';\nimport { sleep,check } from 'k6';\n\nexport default function () {\n  const baseURI = `${__ENV.TESTKUBE_HOMEPAGE_URI || 'https://testkube.kubeshop.io'}`\n  check(http.get(`${baseURI}/`), {\n    'check testkube homepage home page': (r) =>\n      r.body.includes('Your Friendly Cloud-Native Testing Framework for Kubernetes'),\n  });\n\n\n  sleep(1);\n}\n"
```
I have raised this issue with ref to the discussion i had with @vLia on discord. This is the discord communication [link](https://discord.com/channels/884464549347074049/1050805164090609705/1062002238236668006)
