### ISSUE TITLE
Dashboard - inability to set/edit/remove ENVs

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3097]
**Describe the bug**
It's not possible to set/edit/remove ENVs using dashboard despite the description: `Define environment variables which will be shared across your test.`. It's also not possible to view ENVs in other way than checking it directly in the Test Definition.

**To Reproduce**
1. Create a test using this CRD (or check `container-executor-curl-smoke` test at Demo or Stage)
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: container-executor-curl-smoke
  namespace: testkube
  labels:
    core-tests: executors
spec:
  type: container-executor-curl/test
  executionRequest:
    args:
    - $(URL)
    envs:
      URL: https://testkube.kubeshop.io/
```
2. Check Dashboard -> Test Settings -> Variables and Secrets
3. There are no variables defined in the Dashboard, the description suggests Variables are ENVs
![Screenshot_20230125_135914](https://user-images.githubusercontent.com/1473096/214569582-e33d1118-3901-49d3-a4a4-6a64ce77ddc4.png)

**Expected behavior**
May be considered as an additional case for https://github.com/kubeshop/testkube/issues/2540
