### ISSUE TITLE
Test Edit - pre-release tests - combined issue

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3098]
Combined issue after Test Edit pre-release tests.

- Branch is required in Dashboard, but in cas of  CLI commit can be used instead
- Empty branch input - it's possible to set empty branch input, click Save, "Test source was succesfully updated." is displayed, but it's not saved. Some error message should be displayed if it's required, and can't be empty.
- Git token can't be removed. Set Git token, Save, Check definition (it's added correctly), then go to edit - Git token input is empty (and Save button is locked), so it's not possible to remove it.
- Same case for Git username - it also can't be removed.
- Source: File - it's not possible to select any file - when File is selected with input dialog `Choose a file.` is still displayed, not file is selected, and `Required.` error message is displayed

**Comment by tkonieczny** [comment]
Test Sources:
- Incorrect values are displayed in Dashboard when TestSource values are overwritten. Example:
There is TestSource:
```
apiVersion: tests.testkube.io/v1
kind: TestSource
metadata:
  name: testsource-postman-executor-smoke-testsource-overwrite
  namespace: testkube
spec:
  type: git-file
  repository:
    type: git
    uri: https://github.com/kubeshop/testkube.git
    branch: some-random-non-existing-branch
    path: some/incorrect/random/directory/non-existing-postman-collection.json
```
And, there is a Test definition using this source, that uses this TestSource but overwrites repository - branch and path:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: postman-executor-smoke-testsource-overwrite
  namespace: testkube
spec:
  type: postman/collection
  content:
    repository:
      branch: main
      path: test/postman/executor-tests/postman-executor-smoke.postman_collection.json
  source: testsource-postman-executor-smoke-testsource-overwrite
  executionRequest:
    args:
      - "--env-var"
      - "TESTKUBE_POSTMAN_PARAM=TESTKUBE_POSTMAN_PARAM_value"
status:
  latestExecution:
    id: 63d11deab8f9a0cd88220619
    number: 12
    startTime: 2023-01-25T12:17:46Z
    endTime: 2023-01-25T12:18:04Z
    status: passed
```
So, the test should contain branch, and path values from test (`main`, and `test/postman/executor-tests/postman-executor-smoke.postman_collection.json` - not the ones from TestSource)
![Screenshot_20230125_164525](https://user-images.githubusercontent.com/1473096/214609245-b087a03f-682d-4e73-9a1d-c384d2b7435f.png)
And, if these values would be set already in TestSource (nothing would overwritten) I guess they shouldn't be displayed on this view.
