### ISSUE TITLE
Test Source - ability to view/set/edit branch and path with Dashboard (to match CLI/CRD)

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3101]
Currently only name, repo url, and authentication (username/token) can be viewed/set in Dashboard for a TestSource - branch and path aren't displayed/can't be edited. Example: `testsource-postman-executor-smoke-testsource-git-file`:
```
apiVersion: tests.testkube.io/v1
kind: TestSource
metadata:
  name: testsource-postman-executor-smoke-testsource-git-file
  namespace: testkube
spec:
  type: git-file
  repository:
    type: git
    uri: https://github.com/kubeshop/testkube.git
    branch: main
    path: test/postman/executor-tests/postman-executor-smoke.postman_collection.json
```
![Screenshot_20230125_165348](https://user-images.githubusercontent.com/1473096/214610899-572515f7-d47e-4afc-b85a-8e7ac7df956a.png)

**Describe the enhancement you'd like to see**
Allowing to view/set/edit these in Dashboard
