### ISSUE TITLE
Container executor - negative test result isn't reversed

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3109]
**Describe the bug**
Negative test result isn't reversed in case of Container executor.

**To Reproduce**
container-executor-curl:
```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: container-executor-curl
  namespace: testkube
spec:
  image: curlimages/curl:latest
  command: ["curl"]
  executor_type: container
  types:
  - container-executor-curl/test
```
Test - container-executor-curl-smoke-negative:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: container-executor-curl-smoke-negative
  namespace: testkube
  labels:
    core-tests: executors-negative
spec:
  type: container-executor-curl/test
  executionRequest:
    args:
    - $(URL)
    envs:
      URL: https://testkube.non.existing.url.example
    negativeTest: true
```

**Expected behavior**
Curl exited with exit code 6, so the test should be considered as failure, and then reversed because of negativeTest. So, the execution should marked as success.

**Screenshots**
![Screenshot_20230126_171351](https://user-images.githubusercontent.com/1473096/214888756-cbc7fe6b-1f4e-416c-954e-2673a7fd4372.png)
