### ISSUE TITLE
API Server not reachable from UI with Nginx Ingress & Keycloak OIDC

### ISSUE THREAD

**Issue by s-baier** [kubeshop/testkube#3141]
**Describe the bug**

The API Server endpoint ist not reachable from the UI when exposed using a nginx Ingress-Controller and Keycloak for AuthN.
While we're redirection and authentication via Keycloak works fine, the communiation with the API Server does not.

When setting the "Testkube API Endpoint" from the UI to `https://$HOST/results/v1` (see below vor full configuration), the UI pops up an error with "Could not receive data from the specified api endpoint".

You can see, that the request to `https://$HOST/results/v1/info` returns "Request Header Fields Too Large"
Also from the nginx-ingress logs, you can see, that the request gets directed to the correct pod:

```log
10.1.0.3 - - [03/Feb/2023:17:18:52 +0000] "GET /results/v1/info HTTP/2.0" 202 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" 0 0.014 [testkube-testkube-api-server-8088] [] 34.140.182.63:443 0 0.006 202
10.1.0.3 - - [03/Feb/2023:17:18:52 +0000] "GET /results/v1/info HTTP/2.0" 431 31 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" 3666 0.016 [testkube-testkube-api-server-8088] [] 10.108.3.129:8088 31 0.003 431
```

The testkube-api-server Pod itself does work:

```sh
/ # curl testkube-api-server:8088/v1/info
{"version":"v1.9.1","commit":"a550c12553af288c4de3bdc98f01cf72ae7d5ae3","namespace":"testkube"}/ #
/ # curl testkube-api-server:8088/results/v1/info
{"version":"v1.9.1","commit":"a550c12553af288c4de3bdc98f01cf72ae7d5ae3","namespace":"testkube"}/ #
/ # curl testkube-api-server:8088/results/v1/executions
{"totals":{"results":0,"passed":0,"failed":0,"queued":0,"running":0},"filtered":{"results":0,"passed":0,"failed":0,"queued":0,"running":0},"results":[]}/
```

**To Reproduce**

The kubeshop/testkube chart is installed in v1.9.4 with the following parameters (unnecessary specifics redacted).

```yaml
testkube-api:
  uiIngress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
      nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
      nginx.ingress.kubernetes.io/cors-allow-methods: GET
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    enabled: true
    hosts:
    - $HOST
    path: /results/v\d.*
    tls:
    - hosts:
      - $HOST
      secretName: tls
    tlsenabled: true
testkube-dashboard:
  apiServerEndpoint: https://$HOST/results/v1
  enabled: true
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/access-control-allow-origin: "*"
      nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
      nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
      nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
      nginx.ingress.kubernetes.io/cors-allow-methods: GET
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    enabled: true
    hosts:
    - $HOST
    path: /
    tls:
    - hosts:
      - $HOST
      secretName: tls
    tlsenabled: true
  oauth2:
    args:
    - --provider=keycloak-oidc
    - --client-id=$CLIENT
    - --client-secret=$CLIENT_SECRET
    - --redirect-url=https://$HOST/oauth2/callback
    - --oidc-issuer-url=$OIDC_ISSUER_URL
    - --email-domain="*"
    enabled: true
    env:
      cookieSecret: $COOKIE_SECRET
    path: /oauth2
```

Those are in line with the documented ones:

* https://kubeshop.github.io/testkube/authentication/oauth-ui
* https://github.com/kubeshop/helm-charts/blob/main/charts/testkube/values.yaml

**Expected behavior**

The provided API server FQDN should be accepted & in return making the UI usabel.

**Version / Cluster**

- Testkube version: kubeshop/testkube-1.9.4
- K8s cluster flavor: GKE
- K8s version: v1.25.4-gke.2100

**Comment by vsukhin** [comment]
thank you @s-baier we will try to reproduce it

**Comment by ypoplavs** [comment]
Hello @s-baier,
Can you please try adding this annotation to `oauth2` dashboard configuration and check the Ingress resource by describing it: `kubectl describe ingress oauth2-proxy -n testkube`?
```
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
```

**Comment by s-baier** [comment]
Hi, 

I just redeployed our testkube instance with the above mentioned annotation.
Here is the output of `kubectl describe ingress oauth2-proxy -n testkube`:

```yaml
Name:             oauth2-proxy
Labels:           app.kubernetes.io/managed-by=Helm
Namespace:        testkube
Address:          LB_IP
Ingress Class:    <none>
Default backend:  <default>
TLS:
  tls terminates t testkube.myorg.com
Rules:
  Host                              Path  Backends
  ----                              ----  --------
  testkube.myorg.com
                                    /oauth2   oauth2-proxy:4180 (10.108.7.179:4180)
Annotations:                        kubernetes.io/ingress.class: nginx-tk
                                    meta.helm.sh/release-name: testkube
                                    meta.helm.sh/release-namespace: testkube
Events:
  Type    Reason  Age                From                      Message
  ----    ------  ----               ----                      -------
  Normal  Sync    15m (x2 over 15m)  nginx-ingress-controller  Scheduled for sync
```

**Comment by s-baier** [comment]
Addendum: I just checked the cookie on requests towards the dashboard alone: no issue there, though its the same.

**Comment by ypoplavs** [comment]
I will try it on my end and let you know.

**Comment by s-baier** [comment]
You mean when I have `testkube-dashboard.oauth2.enabled` set to false?

**Comment by s-baier** [comment]
Just checked with the following config:

```yaml
testkube-api:
  uiIngress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
      nginx.ingress.kubernetes.io/cors-allow-methods: GET
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      nginx.ingress.kubernetes.io/rewrite-target: /$1
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    enabled: true
    hosts:
    - $HOST
    path: /results/v\d.*
    tls:
    - hosts:
      - $HOST
      secretName: tls
    tlsenabled: true
testkube-dashboard:
  apiServerEndpoint: https://$HOST/results/v1
  enabled: true
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/access-control-allow-origin: "*"
      nginx.ingress.kubernetes.io/cors-allow-credentials: "false"
      nginx.ingress.kubernetes.io/cors-allow-methods: GET
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    enabled: true
    hosts:
    - $HOST
    path: /
    tls:
    - hosts:
      - $HOST
      secretName: tls
    tlsenabled: true
  oauth2:
    enabled: false
```

But no change in behaviour.
