### ISSUE TITLE
test error: could not start process: chdir /data/repo: no such file or directory

### ISSUE THREAD

**Issue by chooco13** [kubeshop/testkube#3198]
**Describe the bug**
`playwright test error: could not start process: chdir /data/repo: no such file or directory`

**To Reproduce**
I created all resources using the testkube dashboard.
An error occurs when trying to test through a registered TestSource.

Test Definition
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: test
  namespace: testkube
spec:
  type: playwright/test
  content:
    repository:
      branch: master
  source: test-project
```

TestSource Definition
```
apiVersion: tests.testkube.io/v1
kind: TestSource
metadata:
  name: test-project
  namespace: testkube
spec:
  repository:
    type: git
    uri: {git_url}
```

Log Output
```
running test [63ec96cc1bc6bbb3804f6d5a]
🚚 Initializing...
🌍 Reading environment variables...
✅ Environment variables read successfully
RUNNER_ENDPOINT="testkube-minio-service-testkube:9000"
RUNNER_ACCESSKEYID="********"
RUNNER_SECRETACCESSKEY="********"
RUNNER_LOCATION=""
RUNNER_TOKEN=""
RUNNER_BUCKET="testkube-artifacts"
RUNNER_SSL=false
RUNNER_SCRAPPERENABLED="true"
RUNNER_GITUSERNAME=""
RUNNER_GITTOKEN=""
RUNNER_DATADIR="/data"
📦 Fetching test content from ...
📂 Fetching uploads from object store testkube-minio-service-testkube:9000...
📂 Placing files from buckets into /data/uploads/ []
📂 Getting the contents of bucket folders [test-test]
📂 Bucket testkube-artifacts does not exist
🚨 Could not place files: bucket testkube-artifacts does not exist
📂 Setting up access to files in /data
🔬 Executing in directory /data: 
 $ chmod 
✅ Execution succeeded
✅ Access to files enabled
✅ Initialization successful
0x400135bc20
running test [63ec96cc1bc6bbb3804f6d5a]
playwright test error: could not start process: chdir /data/repo: no such file or directory
```

**Expected behavior**
However, if I register the git address directly in Test, the test succeeds without any problems.

Test Definition
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: test
  namespace: testkube
spec:
  type: playwright/test
  content:
    type: git-dir
    repository:
      type: git-dir
      uri: {git_url}
      branch: master
```

Log Output
```
running test [63ec95f41bc6bbb3804f6d53]
🚚 Initializing...
🌍 Reading environment variables...
✅ Environment variables read successfully
RUNNER_ENDPOINT="testkube-minio-service-testkube:9000"
RUNNER_ACCESSKEYID="********"
RUNNER_SECRETACCESSKEY="********"
RUNNER_LOCATION=""
RUNNER_TOKEN=""
RUNNER_BUCKET="testkube-artifacts"
RUNNER_SSL=false
RUNNER_SCRAPPERENABLED="true"
RUNNER_GITUSERNAME=""
RUNNER_GITTOKEN=""
RUNNER_DATADIR="/data"
📦 Fetching test content from git-dir...
✅ Test content fetched to path /data/repo/
📂 Fetching uploads from object store testkube-minio-service-testkube:9000...
📂 Placing files from buckets into /data/uploads/ []
📂 Getting the contents of bucket folders [test-test]
📂 Bucket testkube-artifacts does not exist
🚨 Could not place files: bucket testkube-artifacts does not exist
📂 Setting up access to files in /data
🔬 Executing in directory /data: 
 $ chmod 
✅ Execution succeeded
✅ Access to files enabled
✅ Initialization successful
0x400354d990
running test [63ec95f41bc6bbb3804f6d53]
```
and start testing

**Version / Cluster**
- Which testkube version? 
v1.9.12
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
local minikube
- What Kubernetes version?
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/arm64"}

**Comment by vLia** [comment]
Hello @chooco13 , thanks for reporting this error, I am looking into it

**Comment by vLia** [comment]
Update: I managed to reproduce this issue on both Playwright and Cypress. It seems to be a problem with Test Sources not being fetched properly. Will update you as soon as a fix is out.

**Comment by vLia** [comment]
This was fixed in v1.9.14

**Comment by chooco13** [comment]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/7044743/220507262-7283f128-757a-4628-8682-e88419166b07.png">

After updating to version 1.9.15
I created a new source and a new test and tested the same, but the same error came out.

![image](https://user-images.githubusercontent.com/7044743/220507663-9274e7b6-bc41-4e6f-877a-ec2b9de8561a.png)

am i missing something?

**Comment by chooco13** [comment]
```
apiVersion: tests.testkube.io/v1
kind: TestSource
metadata:
  name: test-project-230222
  namespace: testkube
spec:
  repository:
    type: git
    uri: {git_url}
```

```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: test-230222
  namespace: testkube
spec:
  type: playwright/test
  content:
    repository:
  source: test-project-230222
```
