### ISSUE TITLE
UI: Support job-template argument for test creation.

### ISSUE THREAD

**Issue by Sonlis** [kubeshop/testkube#3211]
**Is your feature request related to a problem? Please describe.**
Related to this: https://github.com/kubeshop/testkube/issues/3209, it is for now impossible to specify a job template from the UI. This is useful for us as we can parameter env variables, service account, etc from the test CRD job-template's field.

**Describe the solution you'd like**
To have a field in the UI test creation step, where one can input a YAML of the job template.

**Describe alternatives you've considered**
This is doable with the CLI. What we thought of doing is having a pipeline, which has testkube-CLI installed, that would create tests instead of the test UI.

**Comment by TheBrunoLopes** [comment]
@fivenp do we need figma mockups for this ?

**Comment by cedricmckinnie** [comment]
Another issue related to jobTemplate is not being able to deploy it via GitOps. Perhaps it can be established as a ConfigMap and then assigned to a Test through the UI or in the Test CR by setting the ConfigMap name/key to `.spec.executionRequest.jobTemplate`?

**Comment by cedricmckinnie** [comment]
Nevermind, realizing now that the Test CR allows for defining `.spec.executionRequest.jobTemplate` as a multi-line string which gets merged into the dynamically-generated test runner pod's spec. i.e.
```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: gingko-test
...
spec:
...
  executionRequest:
    jobTemplate: |
      spec:
        template:
          spec:
            serviceAccountName: my-service-account
            containers:
            - name: {{ .Name }}
```

Smart API and very clean solution. Might be a good thing to throw in the docs somewhere 😅
