### ISSUE TITLE
Artillery executor - Test execution stuck because of artillery bug

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3217]
**Describe the bug**
Artillery 2.0.0-28 and newer versions (including the recent 2.0.0-30) hang during the execution (https://github.com/artilleryio/artillery/pull/1827). Testkube artillery executor uses the latest one (affected by this bug) which result in tests being stuck at `running` state forever. Cron-triggered artillery tests can quickly use-up all resources.

**To Reproduce**
1. Create Artillery Test using up to date artillery executor image:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: artillery-executor-smoke
  namespace: testkube
  labels:
    core-tests: executors
spec:
  type: artillery/test
  content:
    type: git-file
    repository:
      type: git-file
      uri: https://github.com/kubeshop/testkube.git
      branch: main
      path: test/artillery/executor-smoke/artillery-smoke-test.yaml
```
2. Run this tests
3. The tests is stuck at `running` forever.

**Expected behavior**
Artillery bug isn't fixed yet - I think we should downgrade the executor to `artillery@2.0.0-27`.
