### ISSUE TITLE
workingDir don't affect the directory where binary is executed

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3246]
**Describe the bug**
Despite setting workingDir, the directory still need to be additionally set in arguments.

So, this test fails:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: k6-test
  namespace: testkube
spec:
  type: k6/script
  content:
    type: git-dir
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube.git
      branch: main
      # path: test/k6/executor-tests
      workingDir: test/k6/executor-tests
  executionRequest:
    args:
      - k6-smoke-test-without-envs.js
```
And, this one (with full path provided to k6 binary) passed:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: k6-test
  namespace: testkube
spec:
  type: k6/script
  content:
    type: git-dir
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube.git
      branch: main
      workingDir: test/k6/executor-tests
  executionRequest:
    args:
      - test/k6/executor-tests/k6-smoke-test-without-envs.js
```
