### ISSUE TITLE
Playwright executor fails to run the browsers in case of any Playwright version mismatch

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3256]
**Describe the bug**
Playwright executor fails to run the browsers and start the test because of missing browser binaries in case of *any* playwright version mismatch. 
```It is recommended to always pin your Docker image to a specific version if possible. If the Playwright version in your Docker image does not match the version in your project/tests, Playwright will be unable to locate browser executables.```
Browser download is disabled (`PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=true`), but downloading it for every single execution is probably not an option. 

**To Reproduce**
1. Create the test:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: playwright-test
  namespace: testkube
spec:
  type: playwright/test
  content:
    type: git-dir
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube
      branch: main
      path: test/playwright/executor-tests/playwright-project
```
2. Run it
3. The test fails:
```
) [chromium] › smoke.spec.js:4:1 › has title ────────────────────────────────────────────────────

    browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1048/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.31.1. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.30.0-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.31.1-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝





  2) [firefox] › smoke.spec.js:4:1 › has title ─────────────────────────────────────────────────────

    browserType.launch: Executable doesn't exist at /ms-playwright/firefox-1378/firefox/firefox
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.31.1. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.30.0-focal               ║
    ║ - required: mcr.microsoft.com/playwright:v1.31.1-focal               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝




  2 failed
    [chromium] › smoke.spec.js:4:1 › has title ─────────────────────────────────────────────────────
    [firefox] › smoke.spec.js:4:1 › has title ──────────────────────────────────────────────────────
```
