### ISSUE TITLE
Container executor - pod StartError - incorrect/inconsistent error messages

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3276]
**Describe the bug**
Error messages are incomplete/inconsistent in case of pod start failure

The pod failed to start because of incorrect command (based on kubectl describe):
```
State:        Terminated
Reason:       StartError
Message:      failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "npx playwright test": executable file not found in $PATH: unknown]
```

CLI:
The CLI incorrectly suggests that's a problem with checkout.
```
Test execution failed:

⨯ could not fetch test content: failed to do partial checkout on git dir: process error: exit status 128
output: Cloning into 'repo'...
warning: Could not find remote branch playwright-executor-tests to clone.
fatal: Remote branch playwright-executor-tests not found in upstream origin
```

Dashboard:
But, based on Dashboard everything is fine (despite the test failing for no reason)
```
{"type":"event","content":"running test [63fcc5c6c6ab94845bed8365]","time":"2023-02-27T15:01:27.857222567Z"}
{"type":"line","content":"🚚 Initializing...","time":"2023-02-27T15:01:27.857263027Z"}
{"type":"line","content":"🌍 Reading environment variables...","time":"2023-02-27T15:01:27.857267507Z"}
{"type":"line","content":"✅ Environment variables read successfully","time":"2023-02-27T15:01:27.857295417Z"}
{"type":"line","content":"RUNNER_ENDPOINT=\"testkube-minio-service-testkube:9000\"","time":"2023-02-27T15:01:27.857305907Z"}
{"type":"line","content":"RUNNER_ACCESSKEYID=\"********\"","time":"2023-02-27T15:01:27.857313427Z"}
{"type":"line","content":"RUNNER_SECRETACCESSKEY=\"********\"","time":"2023-02-27T15:01:27.857322857Z"}
{"type":"line","content":"RUNNER_LOCATION=\"\"","time":"2023-02-27T15:01:27.857325137Z"}
{"type":"line","content":"RUNNER_TOKEN=\"\"","time":"2023-02-27T15:01:27.857327197Z"}
{"type":"line","content":"RUNNER_BUCKET=\"testkube-artifacts\"","time":"2023-02-27T15:01:27.857331107Z"}
{"type":"line","content":"RUNNER_SSL=false","time":"2023-02-27T15:01:27.857333467Z"}
{"type":"line","content":"RUNNER_SCRAPPERENABLED=\"true\"","time":"2023-02-27T15:01:27.857338257Z"}
{"type":"line","content":"RUNNER_GITUSERNAME=\"\"","time":"2023-02-27T15:01:27.857349607Z"}
{"type":"line","content":"RUNNER_GITTOKEN=\"\"","time":"2023-02-27T15:01:27.857351967Z"}
{"type":"line","content":"RUNNER_DATADIR=\"/data\"","time":"2023-02-27T15:01:27.857353887Z"}
{"type":"line","content":"📦 Fetching test content from git-dir...","time":"2023-02-27T15:01:27.857358427Z"}
{"type":"line","content":"✅ Test content fetched to path /data/repo/test/playwright/executor-tests/playwright-project","time":"2023-02-27T15:01:28.983028345Z"}
{"type":"line","content":"📂 Fetching uploads from object store testkube-minio-service-testkube:9000...","time":"2023-02-27T15:01:28.983062975Z"}
{"type":"event","content":"📂 Placing files from buckets into /data/uploads/ []","time":"2023-02-27T15:01:28.983069125Z"}
{"type":"line","content":"📂 Getting the contents of bucket folders [test-container-executor-playwright-smoke]","time":"2023-02-27T15:01:28.983075425Z"}
{"level":"info","ts":1677510088.9860883,"caller":"minio/minio.go:157","msg":"listing files","bucket":"testkube-artifacts","bucketFolder":"test-container-executor-playwright-smoke"}
{"type":"line","content":"📂 Setting up access to files in /data","time":"2023-02-27T15:01:28.989089034Z"}
{"type":"line","content":"🔬 Executing in directory /data: \n $ chmod ","time":"2023-02-27T15:01:28.989107204Z"}
{"type":"line","content":"✅ Execution succeeded","time":"2023-02-27T15:01:28.990013344Z"}
{"type":"line","content":"✅ Access to files enabled","time":"2023-02-27T15:01:28.990026473Z"}
{"type":"line","content":"✅ Initialization successful","time":"2023-02-27T15:01:28.990029393Z"}
{"type":"result","result":{"status":"running"},"time":"2023-02-27T15:01:28.990031944Z"}
```

**To Reproduce**
Executor:
```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: container-executor-playwright-v1.31.1
  namespace: testkube
spec:
  image: mcr.microsoft.com/playwright:v1.31.1-focal
  command: ["npx playwright test"]
  executor_type: container
  types:
  - container-executor-playwright-v1.31.1/test
```
Test:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: container-executor-playwright-smoke
  namespace: testkube
  labels:
    core-tests: executors
spec:
  type: container-executor-playwright-v1.31.1/test
  content:
    type: git-dir
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube
      branch: main
      path: test/playwright/executor-tests/playwright-project
```
