### ISSUE TITLE
Container executor - `InvalidImageName` - Test marked as `running`

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3300]
**Describe the bug**
When the incorrect image name is used the pod fails to start because of `InvalidImageName` error, but the test is still marked as `Running` - without any error message, or clue what happened.
```
testkube get execution 63ff5267a862384f8f9592e8
ID:         63ff5267a862384f8f9592e8
Name:       container-executor-k6-smoke-1
Number:            1
Test name:         container-executor-k6-smoke
Type:              container-executor-k6-0.43.1/test
Status:            running
Start time:        2023-03-01 13:25:59.841 +0000 UTC
End time:          0001-01-01 00:00:00 +0000 UTC
Duration:          
Labels:            core-tests=executors
Args:     k6-smoke-test-without-envs.js
Repository parameters:
  Branch:          main
  Commit:          
  Path:            test/k6/executor-tests
  Working dir:     test/k6/executor-tests
  Certificate:     

Test execution started
```

```
63ff5267a862384f8f9592e8-fcq26                          0/1     InvalidImageName   0              6m5s
```

**To Reproduce**
1. Create container executor with incorrect image (in this case typo in tag separator):
```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: container-executor-k6-0.43.1
  namespace: testkube
spec:
  image: grafana/k6@0.43.1
  command: ["k6"]
  executor_type: container
  types:
  - container-executor-k6-0.43.1/test
``` 
2. Create a test based on it and run it - for example:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: container-executor-k6-smoke
  namespace: testkube
  labels:
    core-tests: executors
spec:
  type: container-executor-k6-0.43.1/test
  content:
    type: git-file
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube
      branch: main
      path: test/k6/executor-tests
      workingDir: test/k6/executor-tests 
  executionRequest:
    args:
      - k6-smoke-test-without-envs.js
```

**Expected behavior**
Test should be marked as failed, an error message should be displayed.
