### ISSUE TITLE
Ginkgo executor fails to check out - `Failed to do partial checkout on git`

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3399]
Test execution fails on checkout:

```
❌ Failed to do partial checkout on git: process error: exit status 128
output: fatal: 'test/ginkgo/executor-tests/ginkgo-smoke.go' is not a directory; to treat it as a directory anyway, rerun with --skip-checks
```

Example Test:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: ginkgo-executor-smoke
  namespace: testkube
  labels:
    core-tests: executors
spec:
  type: ginkgo/test
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube.git
      branch: ginkgo-executor-tests # TODO: update before merge
      path: test/ginkgo/executor-tests/ginkgo-smoke.go
```
