### ISSUE TITLE
Use only init container data for all pre-built executors

### ISSUE THREAD

**Issue by vsukhin** [kubeshop/testkube#3405]
**Why should it be implemented?**
Some of our pre-built executors still have its own git checkout and don't use init container data

**Describe the improvement**
Start using init container data for all pre-built executors

**Comment by tkonieczny** [comment]
- SoapUI (https://integration.testkube.io/tests/executions/soapui-executor-smoke/execution/64773fb4f0a92ef6340cf026)
```
🔬 Executing in directory /data/repo: 
 $ /bin/sh /usr/local/SmartBear/EntryPoint.sh /data/repo/test/soapui/executor-smoke/soapui-smoke-test.xml
❌ Execution failed: could not start process with command: /bin/sh /usr/local/SmartBear/EntryPoint.sh  error: fork/exec /bin/sh /usr/local/SmartBear/EntryPoint.sh: no such file or directory
output: 
Scraping directories: [/home/soapui/.soapuios/logs]
could not start process with command: /bin/sh /usr/local/SmartBear/EntryPoint.sh  error: fork/exec /bin/sh /usr/local/SmartBear/EntryPoint.sh: no such file or directory
output: 
```

- JMeter, directory (https://integration.testkube.io/tests/executions/jmeter-executor-smoke-directory/execution/64774012f0a92ef6340cf028)
```
running test [64774012f0a92ef6340cf028]
🚚 Running with config [scraperEnabled true dataDir /data SSL false endpoint testkube-minio-service-testkube:9000]
🌍 It is a directory test - trying to find file from the last executor argument test/jmeter/executor-tests/jmeter-executor-smoke.jmx in directory /data/repo
❌ Could not find file test/jmeter/executor-tests/jmeter-executor-smoke.jmx in the directory, error: stat /data/repo/data/repo/test/jmeter/executor-tests/jmeter-executor-smoke.jmx: no such file or directory
could not find file test/jmeter/executor-tests/jmeter-executor-smoke.jmx in the directory: stat /data/repo/data/repo/test/jmeter/executor-tests/jmeter-executor-smoke.jmx: no such file or directory
```

```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: jmeter-executor-smoke-directory
  namespace: testkube
  labels:
    core-tests: executors
    executor: jmeter-executor
    test-type: jmeter-test
spec:
  type: jmeter/test
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube.git
      branch: main
      path: test/jmeter/executor-tests
  executionRequest:
    args:
      - "jmeter-executor-smoke.jmx"
```

- K6, directory is now consistent with other executors - duplicated path isn't needed anymore :heavy_check_mark:
