### ISSUE TITLE
Multiline args in Test CRD fail to deserialize 

### ISSUE THREAD

**Issue by gberche-orange** [kubeshop/testkube#3510]
**Describe the bug**

Multiline args in Test CRD fail to deserialize 

**To Reproduce**

Given the following two resources are defined
```yaml
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: kuttl-container-executor
spec:
  image: ghcr.io/orange-cloudfoundry/kuttl-enriched-image:latest
  command: ["kubectl"]
  # kuttl", "test", "--config",  path
  executor_type: container
  types:
    - kuttl-container/test
```

```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: test-kuttl-data
spec:
  type: kuttl-container/test
  executionRequest:
    command:
      - bash
    args:
      - "-c"
      - | 
        mv /data/test-content /data/01-test-content.yaml
        mkdir -p /tmp/test-suite/test-case; cp /data/01-test-content.yaml /tmp/test-suite/test-case/; cd /tmp/test-suite/; kubectl-kuttl test . --namespace 02-testkube
  content:
    type: string
    data: |
      apiVersion: kuttl.dev/v1beta1
      kind: TestStep
      commands:
      - command: "echo hello world from kuttl command"
```

When launching the following command
```
$ testkube run test test-kuttl-data

starting test execution 02-testkube/test-kuttl-data (error: api/POST-testkube.Execution returned error: api server problem: test execution failed: decoding executor job spec error: error converting YAML to JSON: yaml: line 30: could not find expected ':', context: null;
resp error:an error on the server ("unknown") has prevented the request from succeeding (post services testkube-api-server:8088))
```

**Expected behavior**

No error is produced

**Workaround**

Remove multi lines in args strings

```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: test-kuttl-data
spec:
  type: kuttl-container/test
  executionRequest:
    command:
      - bash
    args:
      - "-c"
      - | 
        mv /data/test-content /data/01-test-content.yaml; mkdir -p /tmp/test-suite/test-case; cp /data/01-test-content.yaml /tmp/test-suite/test-case/; cd /tmp/test-suite/; kubectl-kuttl test . --namespace 02-testkube
  content:
    type: string
    data: |
      apiVersion: kuttl.dev/v1beta1
      kind: TestStep
      commands:
      - command: "echo hello world from kuttl command"
```

**Version / Cluster**
- Which testkube version? 
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**
