### ISSUE TITLE
Unable to set custom jobTemplate for Test

### ISSUE THREAD

**Issue by AndrewUnderwoodAtFanatics** [kubeshop/testkube#3562]
**Describe the bug**
I'm attempting to follow the [docs on how to change the job template for a test](https://docs.testkube.io/concepts/tests/tests-creating#changing-the-default-job-template-used-for-test-execution) to create a Test in my cluster with a custom jobTemplate.  Ultimately I want to do this so I can get an idea of what my Test CRD should look like in order to set a custom jobTemplate with higher memory limits for the Job pod.

I've followed the doc to create the provided cypress Test, here is the CRD the cli command has created in my cluster:

```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: template-test
  namespace: testkube
spec:
  type: cypress/project
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube-example-cypress-project.git
      branch: main
      path: cypress
  executionRequest:
    jobTemplate: "apiVersion: batch/v1\nkind: Job\nspec:\n  template:\n    spec:\n      containers:\n        - name: { { .Name } }\n          image: { { .Image } }\n          imagePullPolicy: Always\n          command:\n            - \"/bin/runner\"\n            - \"{{ .Jsn }}\"\n          volumeMounts:\n            - name: data-volume\n              mountPath: /data\n          resources:\n            limits:\n              memory: 128Mi\n"
```

However, when I execute this Test through the webUI, dashboard gets the following 500 error back from the testkube API server:

```
test execution failed: merging job spec templates: yaml: line 10: did not find expected '-' indicator, context: null
```

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/110694107/228750723-92b0e304-5d1a-4fe4-9254-8ed82c9cec9d.png">

In the testkube-api-server logs I see the following stacktrace:

```
github.com/kubeshop/testkube/pkg/server.(*HTTPServer).Error
	/build/pkg/server/httpserver.go:76
github.com/kubeshop/testkube/internal/app/api/v1.(*TestkubeAPI).ExecuteTestsHandler.func1
	/build/internal/app/api/v1/executions.go:96
github.com/gofiber/fiber/v2.(*App).next
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:132
github.com/gofiber/fiber/v2.(*Ctx).Next
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:945
github.com/kubeshop/testkube/internal/app/api/v1.(*TestkubeAPI).AuthHandler.func1
	/build/internal/app/api/v1/handlers.go:47
github.com/gofiber/fiber/v2.(*Ctx).Next
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:942
github.com/gofiber/fiber/v2/middleware/cors.New.func1
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/middleware/cors/cors.go:141
github.com/gofiber/fiber/v2.(*App).next
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:132
github.com/gofiber/fiber/v2.(*Ctx).Next
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:945
github.com/gofiber/fiber/v2/middleware/pprof.New.func1
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/middleware/pprof/pprof.go:41
github.com/gofiber/fiber/v2.(*Ctx).Next
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:942
github.com/kubeshop/testkube/pkg/server.(*HTTPServer).Init.func1
	/build/pkg/server/httpserver.go:46
github.com/gofiber/fiber/v2.(*App).next
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:132
github.com/gofiber/fiber/v2.(*Ctx).Next
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:945
github.com/gofiber/fiber/v2/middleware/pprof.New.func1
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/middleware/pprof/pprof.go:41
github.com/gofiber/fiber/v2.(*Ctx).Next
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/ctx.go:942
github.com/kubeshop/testkube/pkg/server.(*HTTPServer).Init.func1
	/build/pkg/server/httpserver.go:46
github.com/gofiber/fiber/v2.(*App).next
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:132
github.com/gofiber/fiber/v2.(*App).handler
	/go/pkg/mod/github.com/gofiber/fiber/v2@v2.39.0/router.go:159
github.com/valyala/fasthttp.(*Server).serveConn
	/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/server.go:2372
github.com/valyala/fasthttp.(*workerPool).workerFunc
	/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/workerpool.go:224
github.com/valyala/fasthttp.(*workerPool).getCh.func1
	/go/pkg/mod/github.com/valyala/fasthttp@v1.44.0/workerpool.go:196
```

**To Reproduce**
1. Insert the above Test CRD into a cluster
2. Run the test
3. See error

**Expected behavior**
Is there a more correct syntax for specifying a custom jobTemplate in a Test CRD or is there a bug at play here?

**Version / Cluster**
I'm running version `1.9.231` of the testkube helm chart
