### ISSUE TITLE
Triggers - nothing is executed on action

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3571]
Nothing is triggered on action from other namespaces than `testkube`. Checked with Kind and then GCP cluster.

To reproduce:
- create trigger - for example:
![Screenshot_20230330_183416](https://user-images.githubusercontent.com/1473096/228904312-a1438999-067a-47b4-9708-eccccb3b41da.png)

- execute action that should trigger it: `kubectl create deployment nginx --image=nginx`
- nothing happens - test isn't triggered, nothing in API-server logs

**Versions**
Client Version 1.10.23
Server Version v1.10.23

**Comment by vsukhin** [comment]
triggers work in general, not sure, what are conditions for this issue

```
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```


```
apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: testtrigger-conditions
  namespace: testkube
spec:
  resource: deployment
  resourceSelector:
    labelSelector:
      matchLabels:
       app: nginx
  event: created
  conditionSpec:
    timeout: 100
    conditions:
    - type: Progressing
      status: "True"
      reason: NewReplicaSetAvailable
    - type: Available
      status: "True"
  action: run
  execution: test
  testSelector:
    name: cli-test
    namespace: testkube
```
