### ISSUE TITLE
testkube-api is not honoring https_proxy env var when validating github oauth

### ISSUE THREAD

**Issue by gberche-orange** [kubeshop/testkube#3585]
**Describe the bug**

As a testkube user,
In order to configure api-server oauth in an installation running behind a corporate firewall,
I need testkube-api process to honor  https_proxy environment variable when validating github oauth

**To Reproduce**

Set the following entries in values.yaml to declare the http proxy in the helm-based installation

```yaml
    testkube-api:
      # Direct to internet proxy to validate github oauth token usinug the token validation endpoint
      extraEnvVars:
      - name: HTTPS_PROXY
        value: http://system-internet-http-proxy.internal.paas:3128
      - name: NO_PROXY
        value: 127.0.0.1,localhost,169.254.0.0/16,192.168.0.0/16,172.17.11.0/24,...
```

the proxy is properly defined within the api server pod:

```
<<K9s-Shell>> Pod: 02-testkube/testkube-api-server-86b686b485-j8nbl | Container: testkube-api 
/root $ env | grep PROXY
HTTPS_PROXY=http://system-internet-http-proxy.internal.paas:3128
```

And the container is able to reach github.com

```
export http_proxy=$HTTPS_PROXY
export https_proxy=$HTTPS_PROXY
wget -Y on  https://api.github.com/applications/35b8e4eec818ea4492ee/token
get: error getting response: Invalid argument
```

Currently the `testkube config oauth ...\ config fails as the browser window is displaying github OIDC consent screen is redirecting to 

https://testkube-api-00-core-connectivity-k8s.mydomain.org/api/v1/oauth/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=...
with json content

```json
{"type":"about:blank","title":"Unauthorized","status":401,"detail":"Post \"https://35b8e4eec818ea4492ee:***@api.github.com/applications/35b8e4eec818ea4492ee/token\": dial tcp: lookup api.github.com on 10.43.0.10:53: no such host, context: null"}
```

**Expected behavior**

The Oauth cli validation should go through the http proxy

**Version / Cluster**
- Which testkube version? helm chart version: 1.10.101
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version? 

**Screenshots**

See testkube-api error logs at https://gist.github.com/gberche-orange/aab2590cc922baedab7c2ed8afc17f3e#file-testkube-api-server-proxy-error-log-txt
 
**Additional context**

See related support track at https://discord.com/channels/884464549347074049/885185660808474664/1088040873465487390
