### ISSUE TITLE
Dynamic Slack configuration instead of editing JSON file

### ISSUE THREAD

**Issue by michal-jagiello-tmpl** [kubeshop/testkube#3630]
**Why should it be implemented?**
Instead of editing config map user would be interested in configuring things like Slack configuration using helm values. It's especially important if we are using Argo with auto-sync option on (and we wouldn't like to edit config maps because we are lazy and really like automation).
That would be even easier to maintain in case we are going to use same testsuite on many different environment:
* several developers envs
* pre-prod
So right now if we want to run testsuites and have slack notifications on N slack channels (if N is equal to number of environments) -- each env has own slack channel -- we probably need to provide:
- N testsuites,
- N slack configurations -- each for environment.
That would be hard to maintain.

**Describe the improvement**
By default slack notifications can be configured using file -- when it's empty. Or if user want to later edit by hand that should be also possible. But if user want to modify that using helm values I'd recommend to provide a feature to allow user to modify that during helm chart deployment. I see that could be:
```
...
slackConfigurations:
- channelId: C01234567
  selector:
  - label1: value1
  testname:
  - sanity
  - testName2
  testSuiteName:
  - test-suite1
  - test-suite2
  events:
  - end-test-failed
  - end-test-timeout
  - end-testsuite-failed
  - end-testsuite-timeout
- channelId: C07654342
  selector:
  - label3: value4
  testname:
  - integration-test1
  - integration-test2
  testSuiteName:
  - integration-test-suite1
  - integration-test-suite2
  events:
  -  start-test
  - end-test-success
  - end-test-failed
  - end-test-aborted
  - end-test-timeout
  - start-testsuite
  - end-testsuite-success
  - end-testsuite-failed
  - end-testsuite-aborted
  - end-testsuite-timeout
...
```
And that can be transformed into JSON (what I used above it's just an example from https://docs.testkube.io/guides/slack-integration#adjust-slack-config-file but written in YAML
