### ISSUE TITLE
In Test defeinition executionRequest.variables name is not use as variable name

### ISSUE THREAD

**Issue by Moser-ss** [kubeshop/testkube#3656]
**Describe the bug**
In the Test kind, we have the property spec.executionRequest.variables.FOO.name. When I am using that property, I expect to be the variable name that will be set using the value in that property. Instead, is the value FOO that is being used.

**To Reproduce**
1. Apply the following Test definition:
```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  labels:
    executor: cypress-executor
    test-type: cypress-project
  name: testkube-cypress
spec:
  content:
    repository:
      branch: master
      type: git
      uri: https://github.com/Moser-ss/testkube-poc.git
    type: git
  executionRequest:
    variables:
      SPEC_VAR_NAME:
        name: env_var_name
        type: basic
        value: foo
  type: cypress/project

```
3. Run testkube run test testkube-cypress
4. Check the pod env vars in the k8s cluster
![image](https://user-images.githubusercontent.com/14796637/231112953-8f0a1e24-a204-46f3-a7a3-c5e86275c620.png)

**Expected behavior**
I am expecting the environment variable set in the POD uses the name value not the spec key

**Version / Cluster**

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**
