### ISSUE TITLE
FluxCD integration idea: allow TestTriggers to execute tests on CustomResource Conditions

### ISSUE THREAD

**Issue by cedricmckinnie** [kubeshop/testkube#3712]
**Describe the enhancement you'd like to see**

To summarize, I would love to see the ability of `TestTriggers` to execute Tests based on Name, Selectors and Conditions of `CustomResource` objects. This would allow `TestTriggers` to run Tests for more advanced operator configuration rollouts i.e. Flux.

I also want to resurface [my previous comment ](https://github.com/kubeshop/testkube/issues/3026#issuecomment-1517246790) on this as a new thread as I see this as more of an enhancement to `TestTriggers` rather than a new feature-request. I think this will provide a relatively quick and simple path to better `FluxCD` integration (and likely other advanced operators) without having to re-architect much if at all.

**Additional context**

`FluxCD` controllers wait for resources that are being synced to complete reconciliation whether that attempt succeeds or fails. The controllers then write to the Status Conditions of the respective `HelmRelease` or `Kustomization` object once the whole set of resources that is managed by that HR or KS has attempted to deploy rather than just a `Pod`, `Deployment`, `DaemonSet` etc. within it. This would be powerful because:
- It would allow for you to capture a whole group of resources without having to write granular triggers for each native k8s object.
- You can leverage existing Testkube functionality to implement it.
- It could open the door for testing other advance operators aside from `FluxCD`

Example usage would not require any change to the CRD or CLI inputs other than expanding the list of accepted resource values to include CustomResources i.e.

```yaml
apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: testtrigger-example
spec:
  resource: <HelmRelease|Kustomization> or perhaps any CR object
  resourceSelector:
    namespace: foo-ns
    name: my-helmrelease
  event: <created|modified|deleted>
  conditionSpec:
    timeout: 100
    conditions:
    - reason: ReconciliationSucceeded
      status: "True"
      type: Ready
    - reason: UpgradeSucceeded
      status: "True"
      type: Released
  action: run
  execution: test
  testSelector:
    name: test-to-run
    namespace: testkube
```

Many thanks for the consideration!
