### ISSUE TITLE
Add trigger that waits until all pods are new and ready

### ISSUE THREAD

**Issue by jan-mrm** [kubeshop/testkube#3740]
**Describe the enhancement you'd like to see**
I'd like my test to be triggered after I have changed e.g. an image of a deployment and all pods of that deployment are new and ready (so all pods are replaced with the new version -> the deployment it done and finished successfully).

I've seen #2905 and #3092 and setup a trigger as follows:
```yaml
apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: test-trigger-1
  namespace: testkube
spec:
  action: run
  event: deployment-image-update
  execution: test
  resource: deployment
  resourceSelector:
    labelSelector:
      matchLabels:
        app: exampleapp
  testSelector:
    name: curl-test-1
  delay: 10s
  conditionSpec:
    timeout: 60
    conditions:
      - type: Progressing
        status: "True"
        reason: "NewReplicaSetAvailable"
      - type: Available
        status: "True"
```
I've also seen the possibility to add a delay. 
But when I understand it correctly (and it also seems that way from testing) the delay is applied after the trigger has been matched and just delays the test execution itself.

I guess my observation is that the status of my deployment starts with this status (when updating the image)
```
  "reason": "NewReplicaSetAvailable",
  "status": "True",
  "type": "Progressing"
```
and thus directly triggers the (delayed, when setup with a `delay`) test.

My example application which is tested by the curl test starts slower than the 10 seconds delay, so that the test currently tests the old version. I would not like to rely on some hardcoded delay if possible (just increasing the delay to for example 60).

Am I missing something to get the desired behavior by changing configuration?
If not: Could that behavior be implemented / archived in any way?

**Additional context**

*(Just became aware of this awesome project at kubecon :) 👍 )*

**Comment by on-delete** [comment]
I have the same issue with the test trigger. I monitored the status changes of the deployment and found out, that upon modification of the deployment, a status for the old replica set is issued by kubernetes, therefor the test is triggered immediately and not after the deployment has finished. So the test is triggered for the old replica-set, not for the new one.

```
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-04-02T06:43:27Z"
    lastUpdateTime: "2023-04-02T06:43:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-03-28T10:34:12Z"
    lastUpdateTime: "2023-05-03T05:59:39Z"
    message: ReplicaSet "service-75475bddd7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-04-02T06:43:27Z"
    lastUpdateTime: "2023-04-02T06:43:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-03-28T10:34:12Z"
    lastUpdateTime: "2023-05-03T05:59:39Z"
    message: ReplicaSet "service-75475bddd7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-04-02T06:43:27Z"
    lastUpdateTime: "2023-04-02T06:43:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-03-28T10:34:12Z"
    lastUpdateTime: "2023-05-03T06:15:04Z"
    message: Created new replica set "service-797744cbfc"
    reason: NewReplicaSetCreated
    status: "True"
    type: Progressing
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-04-02T06:43:27Z"
    lastUpdateTime: "2023-04-02T06:43:27Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-03-28T10:34:12Z"
    lastUpdateTime: "2023-05-03T06:18:25Z"
    message: ReplicaSet "service-797744cbfc" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
```

Maybe it would be a good idea, to set the conditions on their sequence. Or if we could skip some events.
