### ISSUE TITLE
Testkube run test command not able to find test resource. (EKS platform)

### ISSUE THREAD

**Issue by sambeet99** [kubeshop/testkube#3820]
**What is the issue**
I create k3d cluster on Aws with Kong reverse proxy. I did all setup testkube and deployed a service "keycloak" for testing. Created test resource with Postman executor type to hit API endpoint (internal API i.e.  <service_name.nsamespace:port>) of keycloak. Upon running testkube run test keycloak-test , I got below error - 

![image](https://github.com/kubeshop/testkube/assets/42390504/8594f7e9-2953-4dab-8afc-9410e669dfc9)

Test resource is created and available on cluster but Testkube not able to find it.

![image](https://github.com/kubeshop/testkube/assets/42390504/f783d995-6ffb-4ccd-94b5-571ca3e6ac8c)

**To Reproduce**
1. Deploy a k3d cluster on AWS (ubuntu)  -  
2. Install Testkube cli - 
> wget -qO - https://repo.testkube.io/key.pub | sudo apt-key add - && echo "deb https://repo.testkube.io/linux linux main" | sudo tee -a /etc/apt/sources.list && sudo apt-get update && sudo apt-get install -y testkube
3. Install testkube helmchart of version: 1.11.189
    *changes in values.yaml* -
  ```yaml    
 mongodb.global.storageClass: "local-path"          
 testkube-api.minio.enabled: false
```
4. Deployed a service to test i.e. Keycloak
5. Created postman executor type test resource -
```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: keycloak-test
  namespace: testkube
spec:
  type: postman/collection
  content:
    type: string
    data: "{\r\n    \"info\": {\r\n      \"_postman_id\": \"8af42c21-3e31-49c1-8b27-d6e60623a180\",\r\n      \"name\": \"Kubeshop\",\r\n      \"schema\": \"https://schema.getpostman.com/json/collection/v2.1.0/collection.json\"\r\n    },\r\n    \"item\": [\r\n      {\r\n          \"name\": \"keycloak-test\",\r\n          \"request\": {\r\n              \"method\": \"GET\",\r\n              \"header\": [],\r\n              \"url\": {\r\n                \"raw\": \"http://keycloak-discovery.core:8080/\",\r\n                \"protocol\": \"http\",\r\n                \"host\": [\"keycloak-discovery.core\"],\r\n                \"port\": 8080\r\n              }\r\n          },\r\n          \"response\": []\r\n      }\r\n    ]\r\n  }"

```

test resource created in testkube.

6. verified all created setup-

![image](https://github.com/kubeshop/testkube/assets/42390504/a134f53f-df72-4bc9-9a51-5a9e584420ba)

testkube dashboard- 
![image](https://github.com/kubeshop/testkube/assets/42390504/fc51ebd8-21d7-4c61-8e3e-e2607cc9b3de)

								
							    
								  

**Expected behavior**
testkube should be able to run available test on cluster

**Version / Cluster**
- Which testkube version? 
```text
Client Version 1.11.7
Server Version  api/GET-testkube.ServerInfo returned error: api server response: '{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"error trying to reach service: dial tcp 10.46.31.186:8088: connect: connection timed out","reason":"ServiceUnavailable","code":503}
'
error: error trying to reach service: dial tcp 10.46.31.186:8088: connect: connection timed out
Commit c30d3514e2c2cf1ba041e592855d0cbd06fb450c
Built by goreleaser
```
- What Kubernetes cluster? (EKS)
- What Kubernetes version? K8s Rev: v1.24.13
 
**Additional context**

- Multiple storageClass are avialble on my EKS, hence selected **local-path**
- **Same testkube setup on my local cluster working fine**, only EKS is having issue.
- Seems testkube command not able to fetch Server version also 
- I am not trying to access any testkube resource from outside cluster. hence no ingress or LB setup done for testkube
- Api server logs
![image](https://github.com/kubeshop/testkube/assets/42390504/5e21383f-edb2-422a-8cd5-3e14cb1d3d5d)

**Comment by vsukhin** [comment]
hey, @sambeet99 Looks very interesting. Let us think about

**Comment by vsukhin** [comment]
Sounds like a permission issue. Can you try to run `testkube get test keyloak-test` 
And check api server logs, might be it will contain more error details?

**Comment by vsukhin** [comment]
ok, thank you. then it makes more clear. client can't reach api server, most likely becuase of mesh or security policies, so the request is timed out

**Comment by sambeet99** [comment]
So any specific config or rule we need to include for CLI to interact with server running on EKS ?

**Comment by vsukhin** [comment]
No, but if I remember it well, in EKS some ports can't be accessible by default by policies, @ypoplavs ?

**Comment by sambeet99** [comment]
HI @vsukhin any input from your team ? Like any specific port change or security policy change , route table update.. It has been a blocker for me.

**Comment by vsukhin** [comment]
hey, @sambeet99 Let us check it out

**Comment by ypoplavs** [comment]
Hello @sambeet99, can you please try opening port 8080 on your Security group? Also how did you manage to create a test since it also requires accessing TK API?

**Comment by sambeet99** [comment]
locally also I have deployed testkube..there I created yamls. I tested locally , all working fine. 
I applied same yaml on EKS using kubectl apply command that created the test resource.
```yaml

apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: keycloak-test
  namespace: testkube
spec:
  type: postman/collection
  content:
    type: string
    data: "{\r\n    \"info\": {\r\n      \"_postman_id\": \"8af42c21-3e31-49c1-8b27-d6e60623a180\",\r\n      \"name\": \"Kubeshop\",\r\n      \"schema\": \"https://schema.getpostman.com/json/collection/v2.1.0/collection.json\"\r\n    },\r\n    \"item\": [\r\n      {\r\n          \"name\": \"keycloak-test\",\r\n          \"request\": {\r\n              \"method\": \"GET\",\r\n              \"header\": [],\r\n              \"url\": {\r\n                \"raw\": \"http://keycloak-discovery.core:8080/\",\r\n                \"protocol\": \"http\",\r\n                \"host\": [\"keycloak-discovery.core\"],\r\n                \"port\": 8080\r\n              }\r\n          },\r\n          \"response\": []\r\n      }\r\n    ]\r\n  }"

```
