### ISSUE TITLE
testkube api-server telemetry does not honor HTTPS_PROXY env and fails to connect to upstream analytics server

### ISSUE THREAD

**Issue by gberche-orange** [kubeshop/testkube#3869]
**Describe the bug**

testkube api-server telemetry does not honor HTTPS_PROXY env and fails to connect to upstream analytics server

**To Reproduce**


```yaml
   testkube-api:                                                                                                                                                                                                  
      extraEnvVars:                                                                                                                                                                                                
      - name: DEBUG                                                                                                                                                                                                
        value: "true"                                                                                                                                                                                              
      - name: HTTPS_PROXY                                                                                                                                                                                          
        value: http://system-internet-http-proxy.internal.paas:3128                                                                                                                                                
      - name: https_proxy
        value: http://system-internet-http-proxy.internal.paas:3128
      - name: HTTP_PROXY
        value: http://system-internet-http-proxy.internal.paas:3128
      - name: http_proxy
        value: http://system-internet-http-proxy.internal.paas:3128
      - name: NO_PROXY                                                                                                                                                                                             
        value: 127.0.0.1,localhost,10.0.0.0/8,169.254.0.0/16,192.168.0.0/16,172.16.0.0/12,.domain.org
```




**Expected behavior**

Telemetry sent upstream.

Might be related to #3585

**Version / Cluster**
- Which testkube version? 
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
- What Kubernetes version?

**Screenshots**

`
testkube-api-server-d7996d6c-ggzsx {"level":"debug","ts":1684739485.0613174,"caller":"telemetry/generators.go:18","msg":"error while generating machines protected id","error":"machineid: machineid: open /etc/machine-id: no such file or directory"}
testkube-api-server-d7996d6c-ggzsx {"level":"debug","ts":1684739485.0615244,"caller":"telemetry/sender_ga4.go:52","msg":"sending ga payload to validate","payload":{"user_id":"clusterea657a8fe947e0ce8d0a97170e3cbe04","client_id":"clusterea657a8fe947e0ce8d0a97170e3cbe04","events":[{"name":"testkube_api_start","params":{"event_count":1,"event_category":"api","app_version":"1.11.22","app_name":"testkube-api-server","host":"external","machine_id":"0f7ed7580df009b09283b510d802c25c","cluster_id":"clusterea657a8fe947e0ce8d0a97170e3cbe04","operating_system":"linux","architecture":"amd64","context":{"Type":"","OrganizationId":"","EnvironmentId":""},"cluster_type":"others"}}]}}
testkube-api-server-d7996d6c-ggzsx {"level":"debug","ts":1684739485.1308434,"caller":"telemetry/telemetry.go:81","msg":"sending telemetry data error","payload":{"user_id":"clusterea657a8fe947e0ce8d0a97170e3cbe04","client_id":"clusterea657a8fe947e0ce8d0a97170e3cbe04","events":[{"name":"testkube_api_start","params":{"event_count":1,"event_category":"api","app_version":"1.11.22","app_name":"testkube-api-server","host":"external","machine_id":"0f7ed7580df009b09283b510d802c25c","cluster_id":"clusterea657a8fe947e0ce8d0a97170e3cbe04","operating_system":"linux","architecture":"amd64","context":{"Type":"","OrganizationId":"","EnvironmentId":""},"cluster_type":"others"}}]},"error":"Post \"https://analytics.testkube.io\": dial tcp: lookup analytics.testkube.io on 10.43.0.10:53: no such host"}
testkube-api-server-d7996d6c-ggzsx {"level":"debug","ts":1684739485.195414,"caller":"telemetry/telemetry.go:81","msg":"sending telemetry data error","payload":{"user_id":"clusterea657a8fe947e0ce8d0a97170e3cbe04","client_id":"clusterea657a8fe947e0ce8d0a97170e3cbe04","events":[{"name":"testkube_api_start","params":{"event_count":1,"event_category":"api","app_version":"1.11.22","app_name":"testkube-api-server","host":"external","machine_id":"0f7ed7580df009b09283b510d802c25c","cluster_id":"clusterea657a8fe947e0ce8d0a97170e3cbe04","operating_system":"linux","architecture":"amd64","context":{"Type":"","OrganizationId":"","EnvironmentId":""},"cluster_type":"others"}}]},"error":"Post \"https://www.google-analytics.com/mp/collect?measurement_id=G-KFQXSNKNV4&api_secret=[...]\": dial tcp: lookup https://www.google-analytics.com on 10.43.0.10:53: no such host"}
`
 
**Additional context**
