### ISSUE TITLE
Container executor - artifacts - default directory (`/data/artifacts`)

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#3870]
**Describe the enhancement you'd like to see**
Introducing default artifacts directory (`/data/artifacts`) for custom container executor. Repository is already checked out to `/data/repo`, so setting artifacts to `/data/artifacts` is in my opinion the best option. It will simplify test creation, and using custom container executors - user won't need to set:
```
    artifactRequest:
      storageClassName: standard
      volumeMountPath: /data/artifacts
      dirs:
        - ./
```
for every single test, and will still be able to overwrite it if needed.
