### ISSUE TITLE
Include the cluster name/URL in notifications and such

### ISSUE THREAD

**Issue by spkane** [kubeshop/testkube#3899]
**Is your feature request related to a problem? Please describe.**

For folks with more than one K8s server, including the K8s cluster name and/or the API server URL in the Slack notification template would be advantageous.

Including this data in any recorded or sent data would generally be helpful.

**Describe the solution you'd like**

Make it easy to template the cluster name and/or API server into these notifications and maybe other data. Ideally just making it possible to pass the slack template in as text would be a plus (and then have helm do the base64 encoding), but there are many ways I could see solving this using the Helm values.

With Helm, it would be possible to pass the cluster name in via the values file since this information is likely difficult to determine otherwise.

**Describe alternatives you've considered**

Using `kustomize`, but the fact that the slackTemplate value is supposed to already be base64 encoded, this is a lot more difficult than it should be.

**Additional context**

The specific use case/problem is that we have many servers, and I'd like it to be very clear in these Slack notifications which server experienced the test failure.

We are using the most recent Helm Chart (1.11.221).

It appears that it expects the values to be already base64 encoded. It would be much easier to template random data into this if instead of this:

```yaml
testkube-api:
  slackToken:  'REDACTED'
  slackConfig: 'base64-encoded-json-config'
  slackTemplate: 'base64-encoded-template'
```

I could do this:

```yaml
testkube-api:
  slackToken:  'REDACTED'
  slackConfig: |
    - ChannelID: "C123456789"
      selector: 
        tester: "platform"
      events:
        - "end-test-failed"
        - "end-test-timeout"
        - "end-testsuite-failed"
        - "end-testsuite-aborted"
  slackTemplate: |
    {
      "blocks": [
        {
          "type": "section",
          "text": {
            "type": "plain_text",
            "emoji": true,
            "text": "Execution {{ .ExecutionName }} of {{ .TestName }} status {{ .Status }}"
          }
        },
    ...
```

I can probably override the ConfigMap, if required, but it would be much cleaner to manage this via the values file.
