### ISSUE TITLE
Secret Vars are not passed to Postman env

### ISSUE THREAD

**Issue by vsukhin** [kubeshop/testkube#3907]
**Describe the bug**
Secrets  vars are not passed  to Postman env

**To Reproduce**
1. Create a postman test containing secret vars and global variable in the postman test
```
variables:
  apiPassword:
    name: apiPassword
      type: secret
      valueFrom:
        secretKeyRef:
          name: postman-create-user-testvars
          key: apiPassword
```
2. Run above test
3. Check if global variable in the postman test is set from secret var

**Expected behavior**
Secret vars should be passed to Postman env
