### ISSUE TITLE
Bug: Tests list is empty on testsuite

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#3940]
**Describe the bug**

Example Test Suite: 
https://integration.testkube.io/test-suites/executions/jacek-ts

<img width="1618" alt="image" src="https://github.com/kubeshop/testkube/assets/30776/dee3294e-2966-415d-ab06-e1319f5de485">

My test suite definition looks like below: 

```
apiVersion: tests.testkube.io/v2
kind: TestSuite
metadata:
  name: jacek-ts
  namespace: testkube
spec:
  description: "Jaceks CDEvents testing"
  steps:
  - execute:
      stopOnFailure: false
      name: jacek-cypress-failed
  - execute:
      stopOnFailure: false
      name: jacek-cypress-failed
  - execute:
      stopOnFailure: false
      name: jacek-cypress-failed
  - execute:
      stopOnFailure: false
      name: jacek-cypress-failed
  - execute:
      stopOnFailure: false
      name: jacek-cypress-failed
  - execute:
      stopOnFailure: false
      name: jacek-cypress-failed
  - execute:
      stopOnFailure: false
      name: jacek-cypress-failed
  - execute:
      stopOnFailure: false
      name: jacek-cypress-failed
  - execute:
      stopOnFailure: false
      name: jacek-cypress-failed
  - execute:
      stopOnFailure: false
      name: jacek-cypress-failed
  - execute:
      stopOnFailure: false
      name: jacek-cypress-failed
status:
  latestExecution:
    id: 64772e01f0a92ef6340cefa5
    startTime: 2023-05-31T11:22:41Z
    endTime: 2023-05-31T11:57:37Z
    status: failed
```
