### ISSUE TITLE
AWS S3 Bucket can't be accessed by IAM role

### ISSUE THREAD

**Issue by bkomraz1** [kubeshop/testkube#3965]
**Describe the bug**
It is impossible to configure S3 bucket access on base of IAM assume role without AWS access key specified in configuration

**To Reproduce**
1. Configure to use AWS S3 Bucket with accessKey

- Follow S3 and IAM configuration https://docs.testkube.io/articles/common-issues/#installation-with-s3-storage-and-iam-authentication

- create IAM role and SA

- configure  testkube-api to use AWS S3 Bucket and **specify accessKey**

```
testkube-api:

  jobServiceAccountName: testkube

  logs:
    bucket: xxxx-testkube

  minio:
    minioRootPassword:
    minioRootUser:
    serviceAccountName: testkube

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::11111111111:role/xxxx--testkube


  storage:
    endpoint: s3.amazonaws.com
    endpoint_port:
    accessKeyId:  XXXXXXXXXXX
    accessKey: xxxxxxxxxxxx
    bucket: "xxxx-testkube"
```
- logs and artefacts are stored in AWS S3 Bucket

2. Now configure to use AWS S3 Bucket **WITHOUT** accessKey by IAM assume role

```
testkube-api:

  jobServiceAccountName: testkube

  logs:
    bucket: xxxx-testkube

  minio:
    minioRootPassword:
    minioRootUser:
    serviceAccountName: testkube

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::11111111111:role/xxxx--testkube


  storage:
    endpoint: s3.amazonaws.com
    endpoint_port:
    accessKeyId: <------- EMPTY 
    accessKey: <------- EMPTY
    bucket: "xxxx-testkube"
```

All required environment variables are injected to testkube-api-server according to role-arn annotation:

```
k exec -it testkube-api-server-77ccd8c544-bczzf -- env | grep AWS
AWS_ROLE_ARN=arn:aws:iam::11111111:role/xxxxxx--testkube
AWS_REGION=us-east-1
AWS_STS_REGIONAL_ENDPOINTS=regional
AWS_DEFAULT_REGION=us-east-1
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

3. But testkube api process is not able access AWS S3 Bucket and raises error related to lack of AWS Access Key configuration

```
testkube-api-server-65c6f95586-hrx7z testkube-api {"level":"info","ts":1685973542.6289227,"caller":"api-server/main.go:223","msg":"minio is not available, using default logs storage","error":"The AWS Access Key Id you provided does not exist in our records."}
```

Test executor fails to upload artefacts because it also based on AWS Access Key Id that is not provided

```
{"type":"line","content":"✅ Execution succeeded","time":"2023-06-05T14:52:15.201492292Z"}
{"type":"line","content":"Scraping directories: [/data/repo/sanity/playwright/playwright-report-zip]","time":"2023-06-05T14:52:15.201518082Z"} {"level":"info","ts":1685976735.2015347,"caller":"scraper/filesystem_extractor.go:50","msg":"scraping artifacts in directory: /data/repo/sanity/playwright/playwright-report-zip"}
{"level":"info","ts":1685976735.2033796,"caller":"scraper/filesystem_extractor.go:96","msg":"creating artifacts tarball with 1 files"}
{"level":"info","ts":1685976735.2311497,"caller":"scraper/minio_uploader.go:47","msg":"MinIO loader is uploading file","file":"artifacts.tar.gz","folder":"647df68deaf6fd9a2c94bf94","size":1021321}
{"type":"error","content":"error scraping artifacts: error processing object artifacts.tar.gz: error saving file artifacts.tar.gz: error checking does bucket xxxx-testkube exists: The AWS Access Key Id you provided does not exist in our records.","time":"2023-06-05T14:52:15.246394925Z"}
```

In dashboard test output shows:

```
error scraping artifacts: error processing object artifacts.tar.gz: error saving file artifacts.tar.gz: error checking does bucket xxxx-testkube exists: The AWS Access Key Id you provided does not exist in our records.
```

**Expected behavior**
If testkube is configured to use AWS S3 Bucket and accessKeyID is not specified in helm chart values testkube-api and testkube jobs should use AWS_ROLE_ARN environment variable injected by AWS EKS controller.

**Version / Cluster**
- Which testkube version?
 1.12.5 

- Which helm chart verion?

- name: testkube
    version: 1.12.5
    repository: https://kubeshop.github.io/helm-charts

- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
EKS

- What Kubernetes version?
Server Version: v1.23.17-eks-0a21954

**Additional context**
May be related to [#3960](https://github.com/kubeshop/testkube/issues/3960)

**Comment by vsukhin** [comment]
thank you @bkomraz1 interesting case, we need to check it out

**Comment by bkomraz1** [comment]
For make above environment variables empty helm values should be defined as empty string and not as empty. 
I originally configured according to documentation. Now I configured those values as empty string:

```
testkube-api:

  jobServiceAccountName: testkube

  logs:
    bucket: xxxx-testkube

  minio:
    minioRootPassword: "" <------- EMPTY STRING
    minioRootUser: "" <------- EMPTY STRING
    serviceAccountName: testkube

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::11111111111:role/xxxx--testkube


  storage:
    endpoint: s3.amazonaws.com
    endpoint_port: 443
    accessKeyId: "" <------- EMPTY STRING
    accessKey: ""    <------- EMPTYSTRING
    bucket: "xxxx-testkube"
```

Now storage works and artefacts are saved in s3 bucket.

However testkube-api-server still can't save logs in S3 bucket:

```
k logs -f testkube-api-server-755fc75fdb-d5r22
{"level":"info","ts":1687696354.2396634,"caller":"api-server/main.go:223","msg":"minio is not available, using default logs storage","error":"Access Denied"}
```

k get po -o yaml testkube-api-server-755fc75fdb-d5r22
```
...
  - env:
    - name: APISERVER_PORT
      value: "8088"
    - name: API_MONGO_DSN
      valueFrom:
        secretKeyRef:
          key: mongo-dsn
          name: testkube
    - name: API_MONGO_ALLOW_DISK_USE
      value: "false"
    - name: NATS_URI
      value: nats://testkube-nats
    - name: POSTMANEXECUTOR_URI
    - name: TESTKUBE_ANALYTICS_ENABLED
      value: "true"
    - name: SLACK_TOKEN
      valueFrom:
        secretKeyRef:
          key: SLACK_TOKEN
          name: testkube
    - name: STORAGE_ENDPOINT
      value: s3.amazonaws.com
    - name: STORAGE_BUCKET
      value: xxxx-testkube
    - name: STORAGE_EXPIRATION
      value: "0"
    - name: STORAGE_ACCESSKEYID
    - name: STORAGE_SECRETACCESSKEY
    - name: STORAGE_REGION
    - name: STORAGE_TOKEN
    - name: STORAGE_SSL
      value: "false"
    - name: SCRAPPERENABLED
      value: "true"
    - name: LOGS_BUCKET
      value: xxxx-testkube
    - name: LOGS_STORAGE
      value: minio
    - name: TESTKUBE_NAMESPACE
      value: testkube
    - name: JOB_SERVICE_ACCOUNT_NAME
      value: testkube
    - name: APISERVER_FULLNAME
      value: testkube-api-server
    - name: APISERVER_CONFIG
      value: testkube-api-server-config-testkube
    - name: APISERVER_HTTP_READBUFFERSIZE
      value: "8192"
    - name: TESTKUBE_OAUTH_CLIENTID
    - name: TESTKUBE_OAUTH_CLIENTSECRET
    - name: TESTKUBE_OAUTH_PROVIDER
      value: github
    - name: TESTKUBE_OAUTH_SCOPES
    - name: TESTKUBE_CLOUD_URL
      value: agent.testkube.io:443
    - name: TESTKUBE_WATCHER_NAMESPACES
    - name: TESTKUBE_CONFIG_DIR
      value: /app/config
    - name: TESTKUBE_REGISTRY
    - name: TESTKUBE_POD_START_TIMEOUT
      value: 30m
    - name: CDEVENTS_TARGET
    - name: TESTKUBE_DASHBOARD_URI
    - name: AWS_STS_REGIONAL_ENDPOINTS
      value: regional
    - name: AWS_DEFAULT_REGION
      value: us-east-1
    - name: AWS_REGION
      value: us-east-1
    - name: AWS_ROLE_ARN
      value: arn:aws:iam::11111:role/xxxx--testkube
    - name: AWS_WEB_IDENTITY_TOKEN_FILE
      value: /var/run/secrets/eks.amazonaws.com/serviceaccount/token
...
```

**Comment by bkomraz1** [comment]
Hi @nicufk , @vsukhin , Do you have any news about the issue?

**Comment by nicufk** [comment]
hey @bkomraz1, I found the cause, we were using list buckets as a test to see if the connection to the storage is possible, but as you can see from the logs it is "Access denied", probably you didn't provide this config for the IAM role, there is a PR with the fix

**Comment by kmannuz** [comment]
> hey @bkomraz1, I found the cause, we were using list buckets as a test to see if the connection to the storage is possible, but as you can see from the logs it is "Access denied", probably you didn't provide this config for the IAM role, there is a PR with the fix

Not the OP but struggling with an attempt at a very similar configuration. Is the list of necessary IAM actions documented anywhere?

**Comment by nicufk** [comment]
Hey @kmannuz, the permissions needed are described in the docs now, see the PR from above, additionally you will need also `s3:ListAllMyBuckets` as a workaround for the issue described above because it will take some time until the fix is getting into the release.

**Comment by ypoplavs** [comment]
hi @bkomraz1!
We have changed the logic for the secrets and it all should be working now. Please upgrade and let us know about the results.

**Comment by davidB** [comment]
FYI, I also have to add the permission "s3:GetBucketLocation". 

----

I share the fragment of my setup, for future readers who prefer an explicit total sample (like the one above) than the current doc about how to set up. Feel free to complete the existing doc (I don't you if I can do a PR)

AWS permission (in hcl/terraform format, it can be converted into JSON), for one bucket per env/workspace.

```hcl
data "aws_iam_policy_document" "testkube" {
  statement {
    sid    = "S3Buckets"
    effect = "Allow"
    actions = [
      "s3:ListAllMyBuckets", # see https://github.com/kubeshop/testkube/issues/3965
    ]
    resources = [
      "arn:aws:s3:::*",
    ]
  }
  statement {
    sid    = "S3Bucket"
    effect = "Allow"
    actions = [
      "s3:ListBucket",
      "s3:GetBucketLocation",
    ]
    resources = [
      "arn:aws:s3:::*-testkube-${terraform.workspace}",
    ]
  }
  statement {
    sid    = "S3Object"
    effect = "Allow"
    actions = [
      "s3:GetObject*",
      "s3:PutObject*",
      "s3:DeleteObject",
    ]
    resources = [
      "arn:aws:s3:::*-testkube-${terraform.workspace}/*",
    ]
  }
```

And from helm configuration

```yaml
  testkube-api:
    jobServiceAccountName: testkube-api-server # reuse the service-account from testkube-api
    minio:
      enabled: true # required to be able to access AWS S3 (minio is used as a proxy)
      minioRootUser: ""
      minioRootPassword: ""
      serviceAccountName: testkube-api-server # reuse the service-account from testkube-api
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::111111111111:role/my-dev-testkube
    storage:
      endpoint: s3.amazonaws.com
      accessKeyId: ""
      accessKey: ""
      location: eu-central-1
      bucket: my-testkube-dev
      SSL: true
      endpoint_port: ""
    logs:
      storage: "minio"
      bucket: my-testkube-dev
```
