### ISSUE TITLE
Frontend: support new TestSuite format

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3976]
## Acceptance Criteria:
 
- Submitting V2 version to API should work
- V2 version will be automatically converted to V3 from API (which means API is always sending V3 format)

New format: 

```yaml
apiVersion: tests.testkube.io/v3
kind: TestSuite
spec:
  description: Example simple tests orchestration
  steps:
    - execute:
        # test1 and test2 will be executed in parallel, 
        # but it will run a minimum of 50ms
        - test: test1
        - test: test2
        - delay: 50ms
    - execute:
        - delay: 1m
    - execute:
        - testSuite: test-suite-1
        - test: test3
    - execute:
        - test: test4
```

## Testing Criteria
- Given that we're going to change UI soon, we'd prefer to wait on automated tests and  just check if it works manually
