### ISSUE TITLE
CLI: support new TestSuite format

### ISSUE THREAD

**Issue by aabedraba** [kubeshop/testkube#3977]
## Acceptance Criteria 
cli should support new format of TestSuite

```yaml 
apiVersion: tests.testkube.io/v2
kind: TestSuite
spec:
  description: Example simple tests orchestration
  steps:
    - execute:
        # test1 and test2 will be executed in parallel, 
        # but it will run a minimum of 50ms
        - test: test1
        - test: test2
        - delay: 50ms
    - execute:
        - delay: 1m
    - execute:
        - testSuite: test-suite-1
        - test: test3
    - execute:
        - test: test4
```

## Testing Criteria
- Currently CLI is used to apply testsuite in our CI pipeline, so this will ensure that we're not breaking anything
