### ISSUE TITLE
Cypress executors - version tagged images fail with `Execution failed: could not start process with command:   error: exec: no command output`

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4028]
**Describe the bug**
Version-tagged Cypress executor images (`:cypress10`, `:cypress11`, etc.) fail with
```
Execution failed: could not start process with command:   error: exec: no command output` while trying to execute the test with latest versions.
```
Example:
https://dev.testkube.io/tests/executions/cypress-12-executor-smoke-electron/execution/648822b66d99ce17d11665d6

Everything is fine for the default one:
https://dev.testkube.io/tests/executions/cypress-default-executor-smoke-electron

**To Reproduce**
Executor:
```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: cypress-v12-executor
  namespace: testkube
spec:
  image: kubeshop/testkube-cypress-executor:cypress12
  types:
    - cypress:v12/test
  features:
    - artifacts
```
Test:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: cypress-12-executor-smoke-electron
  namespace: testkube
  labels:
    core-tests: executors
spec:
  type: cypress:v12/test
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube
      branch: main
      path: test/cypress/executor-tests/cypress-12
  executionRequest:
    variables:
      CYPRESS_CUSTOM_ENV:
        name: CYPRESS_CUSTOM_ENV
        value: CYPRESS_CUSTOM_ENV_value
        type: basic
    args:
      - --env
      - NON_CYPRESS_ENV=NON_CYPRESS_ENV_value
      - --config
      - video=false
```
