### ISSUE TITLE
Namespace cannot be set for tokenSecret and usernameSecret

### ISSUE THREAD

**Issue by jaxels10** [kubeshop/testkube#4038]
**Describe the bug**
When creating a `Test` using apiVersion `tests.testkube.io/v3`, it is according to the [CRD](https://github.com/kubeshop/helm-charts/blob/develop/charts/testkube-operator/templates/tests.testkube.io_tests.yaml#LL391C32-L391C32) possible to look for a git auth secret in a different namespace than the one used to install testkube.
This can be done like so:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: test
  namespace: testkube
spec:
  content:
    repository:
      tokenSecret:
        name: secret-name
        key: secret-name-key
        namespace: secret-namespace
      usernameSecret:
        name: secret-name
        key: secret-name-key
        namespace: secret-namespace
```
However, when this namespace key is used, the pod created by the job from the test has the following environment variables:
```
- name: RUNNER_GITUSERNAME
  valueFrom:
  secretKeyRef:
  key: secret-name-key
  name: secret-name
- name: RUNNER_GITTOKEN
  valueFrom:
  secretKeyRef:
  key: secret-name-key
  name: secret-name
```

As far as I know, a pod cannot use a secret from a different namespace as an envvar, which makes the namespace key redundant.

**To Reproduce**
1. Run a test referring to a git repo that needs authentications
2. Create test with reference to secret in a different namespace holding the username and token
3. Run test and see that pod created by job fails

**Expected behavior**
CRD should not specify a key that is impossible to use

**Version / Cluster**
- Which testkube version? 1.12.1
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) AKS
- What Kubernetes version? v1.25.5
