### ISSUE TITLE
xk6-browser executor

### ISSUE THREAD

**Issue by HeinzMayer** [kubeshop/testkube#4121]
**Is your feature request related to a problem? Please describe.**
I would like to create tests with xk6-browser. xk6-browser uses a similar syntax as playwrigh. With xk6-browser i could use the same prometheus dashboards as with the k6 executor

**Describe the solution you'd like**
xk6-browser executor

**Describe alternatives you've considered**
I can create a custom executor, but I think this feature is also interesting for others

**Comment by HeinzMayer** [comment]
I have already cretaed a custom xk6-browser executor

Dockerfile
```
FROM kubeshop/testkube-k6-executor:1.12.11 as k6

FROM golang:1.19-bullseye as builder

RUN go install -trimpath go.k6.io/xk6/cmd/xk6@latest
RUN  xk6 build --output "/tmp/k6" --with github.com/grafana/xk6-browser --with github.com/grafana/xk6-output-prometheus-remote@latest

FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y chromium
COPY --from=builder /tmp/k6 /usr/bin/k6
COPY --from=k6 /bin/runner /bin/runner
ENV K6_BROWSER_HEADLESS=true
ENTRYPOINT ["/bin/runner"]
```

Executor

```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: k6-browser-executor
spec:
  args:
    - <k6Command>
    - <envVars>
    - <runPath>
  command:
    - k6
  content_types:
    - string
    - file-uri
    - git-file
    - git-dir
    - git
  executor_type: job
  features:
    - artifacts
  image: harbor.shared.miccust.dev/tools/xk6-browser:1.12.11
  meta:
    docsURI: https://kubeshop.github.io/testkube/test-types/executor-k6
    iconURI: k6
  types:
    - k6-browser/script
```

Test

```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: k6-browser
spec:
  content:
    data: |
      import { chromium } from 'k6/experimental/browser';
      import { check, fail } from 'k6';

      export default async function () {
        const browser = chromium.launch({
          args: ["no-sandbox"],
          headless: true,
          timeout: '60s', 
        });
        const page = browser.newPage();

        try {
          await page.goto('https://test.k6.io/my_messages.php');

          page.locator('input[name="login"]').type('admin');
          page.locator('input[name="password"]').type('123');

          const submitButton = page.locator('input[type="submit"]');

          page.screenshot({ path: 'screenshot.png' });

          await Promise.all([page.waitForNavigation(), submitButton.click()]);
          check(page, {
              header: page.locator('h2').textContent() == 'Welcome1, admin!',
            });

        } finally {
           page.close();
           browser.close();
        }
      }
    repository: {}
    type: string
  executionRequest:
    args:
      - '--out'
      - json=test.json
      - '--out'
      - experimental-prometheus-rw
      - '--tag'
      - testid=k6-browser-test
    artifactRequest:
      dirs:
      - /data
    variables:
      K6_BROWSER_ENABLED:
        name: K6_BROWSER_ENABLED
        type: basic
        value: 'true'
        valueFrom: {}
      K6_PROMETHEUS_RW_SERVER_URL:
        name: K6_PROMETHEUS_RW_SERVER_URL
        type: basic
        value: http://10.228.0.173:9090/api/v1/write
        valueFrom: {}
  type: k6-browser/script
```
