### ISSUE TITLE
Dashboard - testsuite with stopOnFailure enabled - links to non-existing executions

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4139]
**Describe the bug**
If stopOnFailure is enabled for testsuite and one of the tests fails the rest of the tests is marked as failed (expected result). But, it's still possible to go to non-existing executions in Dashboard.

Example:

![Screenshot from 2023-07-05 17-42-16](https://github.com/kubeshop/testkube/assets/1473096/20c6c2f1-2cf0-4889-bf29-d729cc35e6ad)
`k6-executor-smoke-directory` test failed

```
apiVersion: tests.testkube.io/v3
kind: TestSuite
metadata:
  name: example-testsuite-stopOnFailure
  namespace: testkube
spec:
  description: standard
  steps:
  - stopOnFailure: true
    execute:
    - test: test-1
    - test: test-2-that-fails
  - stopOnFailure: false
    execute:
    - test: test-3
```

**Expected behavior**
Links to skipped executions should be disabled (inactive icon).
