### ISSUE TITLE
Add documentation or sample for `iconURI`

### ISSUE THREAD

**Issue by davidBernardWefox** [kubeshop/testkube#4166]
**Describe the enhancement you'd like to see**
Can you add sample for the format of `iconURI` field ? and what format are supported, constraints, ...

**Additional context**
I try to add an icon to a container Executor, but none of the URL I tries works. Using a single name like `postman` as in helm chart definition works. The executor I tried to enhance:

```yaml
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: httpyac-container-executor
spec:
  image: ghcr.io/anweber/httpyac:6.5.1
  executor_type: container
  types:
    - httpyac/test
  args:
    - "--all"
  meta:
   # iconURI: https://httpyac.github.io/favicon.png
    iconURI: https://raw.githubusercontent.com/AnWeber/vscode-httpyac/main/icon.svg # try with a svg as inline svg are used
    docsURI: https://httpyac.github.io/
```
