### ISSUE TITLE
Dashboard - TestSuite - opening non-existing test execution details - no clear error message

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4182]
**Describe the bug**

**To Reproduce**
1. Test with non-existing test is created
```
apiVersion: tests.testkube.io/v3
kind: TestSuite
metadata:
  name: parallel-testsuite-example
  namespace: testkube
spec:
  description: "standard"
  steps:
  - stopOnFailure: true
    execute:
    - test: artillery-executor-smoke
    - test: k6-executor-smoke-directory
  - stopOnFailure: true
    execute:
    - test: k6-executor-smoke-git
  - stopOnFailure: false
    execute:
    - test: artillery-executor-smoke-negative
    - test: container-executor-curl-smoke
```
`k6-executor-smoke-git` is a non-existing test here
2. run this testsuite
3. Check test suite execution in dashboard:
![Screenshot from 2023-07-17 15-56-46](https://github.com/kubeshop/testkube/assets/1473096/e8e757ba-4b33-4b11-847b-90f6ff8ff02c)

- It's possible to open execution details for non-existing test:
![Screenshot from 2023-07-17 15-56-55](https://github.com/kubeshop/testkube/assets/1473096/f648291b-3984-488c-b885-ef12cc24f475)
- No clear message is displayed in Dashboard that the test isn't found
![Screenshot from 2023-07-17 16-02-53](https://github.com/kubeshop/testkube/assets/1473096/a35acd25-70e7-4f34-aa50-4814630dcb96)

**Expected behavior**
- Clear message that the test is missing
- It shouldn't be possible to open execution details for non-existing test
