### ISSUE TITLE
TestSuite with custom image

### ISSUE THREAD

**Issue by jerem0808** [kubeshop/testkube#4236]
**Describe the enhancement you'd like to see**
When we describe a testsuite we should be able to give a custom image repo or an executor.

**Additional context**
We're running testkube in a airgap env. Therefore we should use our own repository. 
The job for a test is using our own repo but the job for a test suite is using the docker hub repo. Maybe i'm missing something in the values.yaml but i don't see where.
TestKube helm chart version
1.13.28

Thanks

``` 
---
global:
  imageRegistry: 5gdmc-docker-virtual.artifactory.swisscom.com

mongodb:
  persistence:
    size: 32Gi
testkube-api:
  mongodb:
    allowDiskUse: true
    dsn: mongodb://testkube-mongodb:27017
  multinamespace:
    enabled: true
  prometheus:
    enabled: false
    monitoringLabels: {}
    interval: 15s
  minio:
    enabled: false
  logs:
    storage: "mongo"
  storage:
    endpoint: "ds11s3-scs.swisscom.com"
    SSL: true
testkube-dashboard:
  enabled: true
  fullnameOverride: testkube-dashboard
  ingress:
    hosts:
      - testkube.ccd801.sharedtcs.net
nats:
  nats:
    image:
      repository: 5gdmc-docker-virtual.artifactory.swisscom.com/nats
  natsbox:
    image:
      repository: 5gdmc-docker-virtual.artifactory.swisscom.com/natsio/nats-box
  bootconfig:
    image:
      repository: 5gdmc-docker-virtual.artifactory.swisscom.com/natsio/nats-boot-config
  reloader:
    image:
      repository: 5gdmc-docker-virtual.artifactory.swisscom.com/natsio/nats-server-config-reloader
  exporter:
    image:
      repository: 5gdmc-docker-virtual.artifactory.swisscom.com/natsio/prometheus-nats-exporter
testkube-operator:
  proxy:
    image:
      registry: gcr-docker-remote.artifactory.swisscom.com
```

**Comment by vsukhin** [comment]
hey @jerem0808 testsuite doesn't have a job, it's running a fe test jobs. We take imageRegistry from helm and pass it as env var tto testkube-api-server

**Comment by jerem0808** [comment]
Hi @vsukhin 
we've created the following testsuite
```
---
apiVersion: tests.testkube.io/v2
kind: TestSuite
metadata:
  name: hourly-e2e
  namespace: testkube
spec:
  description: This test suite contains e2e tests executed every hour
  # execute every hour
  schedule: 0 * * * *
  steps:
    - execute:
    [...]
```
and i can see the following job being executed
```
  Containers:                                                                                                                                
   curlimage:                                                                                                                                
    Image:      curlimages/curl                                                                                                              
    Port:       <none>                                                                                                                       
    Host Port:  <none>                                                                                                                       
    Command:                                                                                                                                 
      sh                                                                                                                                     
      -c                                                                                                                                     
    Args:                                                                                                                                    
      curl -X POST -H "Content-Type: application/json" -d '{"runningContext":{"type":"scheduler","context":"0 * * * *"}}' "http://testkube-ap
i-server:8088/v1/test-suites/hourly-e2e/executions"                                                                                          
    Environment:  <none>                                                                                                                     
    Mounts:       <none>                                                                                                                     
  Volumes:        <none>                                                                                                                     
```
