### ISSUE TITLE
testkube generate tests-crds command contains header in yaml output

### ISSUE THREAD

**Issue by 3keyroman** [kubeshop/testkube#4237]
**Describe the bug**
The generated `yaml` output from `testkube generate tests-crds` command contains header and other characters that should not be present for proper k8s manifest application.

**To Reproduce**
This is my test curl.json test:
```json
{
  "command": [
    "curl",
    "https://jsonplaceholder.typicode.com/todos/1",
    "-H",
    "'Accept: application/json'"
  ],
  "expected_status": "200"
}
```

I run `testkube generate tests-crds curl.json > curl-test.yaml`, expecting it will create manifest that can be applied. However, the `kubectl apply -f curl-test.yaml` gives error: `error parsing test.yaml: invalid Yaml document separator: --------------------------------------`, because of the header in the output from the testkube generate:
```yaml
Context:  (1.13.11)   Namespace: testkube
-----------------------------------------
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: curl
  namespace: testkube
spec:
  type: curl/test
  content:
    type: string
    data: "{\n  \"command\": [\n    \"curl\",\n    \"https://jsonplaceholder.typicode.com/todos/1\",\n    \"-H\",\n    \"'Accept: application/json'\"\n  ],\n  \"expected_status\": \"200\"\n}\n\n"

---
```

**Expected behavior**
The generate `yaml` manifest should be:
```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: curl
  namespace: testkube
spec:
  type: curl/test
  content:
    type: string
    data: "{\n  \"command\": [\n    \"curl\",\n    \"https://jsonplaceholder.typicode.com/todos/1\",\n    \"-H\",\n    \"'Accept: application/json'\"\n  ],\n  \"expected_status\": \"200\"\n}\n\n"

---
```

**Version / Cluster**
testkube:
```
Client Version 1.13.11
Server Version 1.13.11
Commit ef5b1b8ab56d2795cfd67844e77dc08f26bef3cb
Built by goreleaser
Build date 2023-08-02T09:09:37Z
```

k8s:
```
rke2 version v1.25.10+rke2r1 (e0c376c606754f1ae6a1c2401f4f6e9146bda0f3)
go version go1.19.9 X:boringcrypto
```
