### ISSUE TITLE
Webhook not triggered from test suite

### ISSUE THREAD

**Issue by jerem0808** [kubeshop/testkube#4280]
**Describe the bug**
The webhook is not triggered when the test suite trigger a test case and the webhook is configured with the event "end-test-failed"

**To Reproduce**
1. configure the webhook to listen on end-test-failed
``` 
kind: Webhook
metadata:
  name: opsgenie-webhook
  namespace: testkube
spec:
  uri: <<<< URI >>>>
  events:
    - end-test-failed
    - end-testsuite-failed
  selector: ""
[...]
```
2. trigger a test case from a test suite based on a cronjob (if it matters)
3. Check the logs

{"level":"info","ts":1692611737.2253666,"caller":"event/emitter.go:179","msg":"**dropping event not matching selector or type**","**listen-on":["end-test-failed"**],"queue-group":"testkube.opsgeniewebhook","selector":"","metadata":{"**events":"[end-test-failed]**", .....
The two events should match but testkube is dropping the event notheless. 
The difference i see in the logs is that the event is a list of string
["end-test-failed"]
but the event is a string "[end-test-failed]"

**Expected behavior**
I expect that the end-test-failed is trigger even when it is called form a test suite

**Version / Cluster**
- Which testkube version? testkube-1.13.28
- Local kubernetes
- What Kubernetes version? 1.24.2
