### ISSUE TITLE
Template CRD for Job Templates

### ISSUE THREAD

**Issue by dejanzele** [kubeshop/testkube#4292]
**Is your feature request related to a problem? Please describe.**
Currently, Testkube utilizes job templates in the form of yaml files with Go Templating for dynamic parameters within Kubernetes Jobs. However, managing these templates becomes a pain if you have different tests with different scheduling requirements, and it has a lot of overhead to edit the templates in the ConfigMap.

**Describe the solution you'd like**
I propose the introduction of a new Kubernetes Custom Resource Definition (CRD) for these templates, let's call it `Template`. By representing each template as a CRD, we can leverage Kubernetes' native abilities for versioning, watching, and validating these resources. Here's a brief outline of the potential solution:

```
apiVersion: config.testkube.io/v1alpha1
kind: Template
metadata:
  name: job-template-1
spec:
  type: job|container|scraper
  body: <could be a multi-line yaml string>
```

And then we can add a `templateRef` field in the `Test` and `TestSuite` CRDs:
```
apiVersion: tests.testkube.io/v1
kind: Test
metadata:
  name: kubeshop-cypress
spec:
  templateRef: job-template-1
  repository:
    branch: main
    path: examples
    type: git
    uri: https://github.com/kubeshop/testkube-executor-cypress.git
  type: cypress/project
```

**Describe alternatives you've considered**
Testkube already has support for this but the support has a lot of overhead and is quite limited.
Current support:
* https://docs.testkube.io/articles/creating-tests/#changing-the-default-job-template-used-for-test-execution
* https://docs.testkube.io/articles/creating-tests/#changing-the-default-cronjob-template-used-for-scheduled-test-execution

**Additional context**
By moving the templates to a dedicated CRD, we not only make the system more Kubernetes-native but also provide a more organized and scalable approach to handle dynamic test templates. This would be in line with Kubernetes' extensibility principles and would simplify the operational complexity associated with template management. Moreover, integrating RBAC, validation, and versioning on these templates would be more straightforward.
