### ISSUE TITLE
Test timeout - no execution logs (`pods "64edeb25878e28a344c7140c-s8s49" not found` error)

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4303]
**Describe the bug**
Execution logs are missing if the test timed out - they are visible during execution, but after timeout only message like `pods "64edeb25878e28a344c7140c-s8s49" not found` is displayed.
![Screenshot from 2023-08-29 14-58-19](https://github.com/kubeshop/testkube/assets/1473096/691fb538-e726-4b2f-b1dc-f37aa8c551f7)
![Screenshot from 2023-08-29 15-00-04](https://github.com/kubeshop/testkube/assets/1473096/4c5276eb-7528-4fdb-867f-282bf2b520d7)

**To Reproduce**
1. Example test (https://dev.testkube.io/tests/timeout-test/) which will be timed out:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: timeout-test
  namespace: testkube
  labels:
    executor: cypress-executor
    test-type: cypress-project
spec:
  type: cypress/project
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube.git
      branch: main
      path: test/cypress/executor-tests/cypress-without-envs
  executionRequest:
    activeDeadlineSeconds: 20
```
2. Run test, wait for timeout
3. Execution logs are missing

**Expected behavior**
 Clear message that the test has been timed out should be displayed. Additionally, execution logs should be available - both during, and after (timed out) execution.
