### ISSUE TITLE
Testkube execution failed: `no logs` and `selector` not auto-generated 

### ISSUE THREAD

**Issue by quanglee** [kubeshop/testkube#4309]
**Describe the bug**
Currently, I am using Postman as my main executor. Running postman on my local computer is completely OK.

```
newman run ./postman/collections/Postman_API_QA.json -e API_QA_env.json -d API_QA_data.json --reporters cli,json --reporter-json-export
```

But I am unable to run the testkube object on my cluster as it always through these errors (Actually I have 2 tests)

**To Reproduce**
1. Create testkube with my Postman collection, env and data files as needed
2. Port-forward to Testkube, then trigger the run
3. See error

**Expected behavior**
As I am able to run the test on Postman, it should be able to run the test on Testkube

**Version / Cluster**
- testkube version: 1.13.3 
- Kubernetes cluster: GKE
- Kubernetes version: 1.27.3-gke.100

**Screenshots**
Job.batch "64f0fb55f8482d28f957c68b" is invalid: [spec.template.metadata.labels[controller-uid]: Invalid value: map[string]string{"batch.kubernetes.io/controller-uid":"7d0cc5a9-18aa-4e4e-abd4-d3899ec9a1d7", "batch.kubernetes.io/job-name":"64f0fb55f8482d28f957c68b", "controller-uid":"7d0cc5a9-18aa-4e4e-abd4-d3899ec9a1d7", "executor":"postman-executor", "job-name":"64f0fb55f8482d28f957c68b", "test-name":"test-postman-api-ede1cb5", "test-type":"postman-collection"}: must be 'a2fa5d10-7f94-4cc4-919b-f02f7715efd2', spec.template.metadata.labels[batch.kubernetes.io/controller-uid]: Invalid value: map[string]string{"batch.kubernetes.io/controller-uid":"7d0cc5a9-18aa-4e4e-abd4-d3899ec9a1d7", "batch.kubernetes.io/job-name":"64f0fb55f8482d28f957c68b", "controller-uid":"7d0cc5a9-18aa-4e4e-abd4-d3899ec9a1d7", "executor":"postman-executor", "job-name":"64f0fb55f8482d28f957c68b", "test-name":"test-postman-api-ede1cb5", "test-type":"postman-collection"}: must be 'a2fa5d10-7f94-4cc4-919b-f02f7715efd2', spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"batch.kubernetes.io/controller-uid":"7d0cc5a9-18aa-4e4e-abd4-d3899ec9a1d7"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: `selector` not auto-generated]

 
**Additional context**
I ran successfully 2 weeks ago, then my team added more test cases on Postman. It might break the testkube. However, it ran successfully on my local by using newman command.

Please do let me know if you need any further clarifications

Thank you so much for your support

**Comment by vsukhin** [comment]
thank you. something with label names, will  check it out

**Comment by vsukhin** [comment]
I tried to check lables, but it work fine on my side. Can you provide your test CRD:
kubectl testkube get test postman-test --crd-only

**Comment by quanglee** [comment]
```yaml

apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: my-app-api-f6411c7
  namespace: testkube
  labels:
    executor: postman-executor
    service: my-app
    test-type: postman-collection
    tier: be
    type: postman
spec:
  type: postman/collection
  content:
    type: string
    data: "<my-data-content-for-iteration-and-format-is-not-displayed-correctly>"
  executionRequest:
    variablesFile: "{\n\t\"id\": \"6c335ca0-e6cf-42cb-aa7a-1d26dfae93ee\",\n\t\"name\": \n\t\"_postman_exported_using\": \"Postman/10.15.1\"\n}"
    args:
      - "-d"
      - "/data/Myapp_API_QA_data.json"
    preRunScript: "# !/bin/bash\nwget -P /data https://storage.googleapis.com/abcxyz/Myapp_API_QA_data.json"
status:
  latestExecution:
    id: 64f11084f8482d28f957c695
    number: 1
    startTime: 2023-08-31T22:13:24Z
    endTime: 2023-08-31T22:13:27Z
    status: failed
```

Sorry I can't give you the variable and data file. However, I noticed the yaml format is not displayed properly at the `spec content.data` so it could break the the testkube 

But I am able to run `newman` with the same env and data files on my local machine

It seems like the data file is the root cause.
