### ISSUE TITLE
Dashboard - Variables name

### ISSUE THREAD

**Issue by michaelsatish** [kubeshop/testkube#4365]
**Describe the bug**
I have a Test with a variable "REPO_NAME" and I use Flux to reconcile the tests. 

When I run the kubectl describe command, I see the variable as defined in my Git Repo.

```sh
kubectl describe test api-smoke -n testkube
```
```yaml
variables:
  REPO_NAME:
    name: PTK_REPO_NAME
    type: basic
     value: api-automation
``` 

However in the dashboard, I see the "PTK_" is removed from the name. 

![image](https://github.com/kubeshop/testkube/assets/77417037/3a856edc-d7fd-4fb0-af13-0f8dd5edb859)

**Testkube Api and Dashboard version: 1.14.0**
