### ISSUE TITLE
GCP - Empty artifacts tar.gz file retreived from Testkube

### ISSUE THREAD

**Issue by swacongne** [kubeshop/testkube#4396]
**Describe the bug**
When Testkube is configured to export artifacts in a Google Cloud bucket the retrieve from the Testkube UI does not work. It outputs an empty file instead of the entire file (note that we only tested with tar.gz files as we do not have tests outputing anything else).

**To Reproduce**
1. Create 2 GCP buckets with HMAC keys: testkube and testkube-logs
2. Use the following in the `values.yaml` file

```yaml
testkube-api:
  minio:
    # -- disable minio in case a google storage bucket is used instead
    enabled: false
    serviceAccountName: cloud-storage-access
    minioRootUser: ""
    minioRootPassword: ""

  storage:
    endpoint: "storage.googleapis.com"
    endpoint_port: ""
    accessKeyId: "ACCESSKEYIDVALUE"
    accessKey: "ACCESSKEYVALUE"
    token: ""
    SSL: true
    region: "europe-west3"
    bucket: "testkube"
  
  logs:
    storage: "minio"
    bucket: "testkube-logs"
```

3. Testkube deployment works, artifacts and logs are stored in the buckets
4. In `test execution > artifacts` try to download a file: it downloads a valid empty tar.gz zip file
5. When trying to retreive the file directly from the bucket the file is NOT empty

**Expected behavior**
The file retreived should not be empty. It should contain the same content as what's available in the GCP Bucket.

**Version / Cluster**
- Which testkube version? 1.14.7
- What Kubernetes cluster? GKE
- What Kubernetes version? 1.26.6-gke.1700

**Screenshots**
N/A
 
**Additional context**
N/A
