### ISSUE TITLE
Dashboard - Run Now with overrides

### ISSUE THREAD

**Issue by michaelsatish** [kubeshop/testkube#4433]
**Describe the enhancement you'd like to see**
It'd great if there is a way to override the execution request variables.  Let say I have two variables "Branch" and "Release" with default or empty values. 

```yaml
executionRequest:
  variables:
    Branch:
      name: Branch
      value: "main"
      type: basic
    Release:
      name: Release
      type: basic
```

After clicking "Run now" or a different button/layout opens a model window for the user to override variables.

This will be helpful if the user wants to pass a value to the downstream framework that changes for each run.

![image](https://github.com/kubeshop/testkube/assets/20645040/a8ed9079-aeea-4120-b5d8-7e0285d15bfd)
