### ISSUE TITLE
Allow to use env variables in command arguments

### ISSUE THREAD

**Issue by jmorante-ks** [kubeshop/testkube#4475]
**Describe the enhancement you'd like to see**
It is currently not possible to use env variables in command arguments.

**Comment by smals-vinve** [comment]
For what it's worth, it **is** possible to do this in Testkube, since we're actually using a similar mechanism:

```yaml
[...]
  args:
  - "echo \"${MY_VAR}\""
  command:
  - "/bin/sh"
  - "-c"
```

Where **MY_VAR** is an env var (e.g. set via Testkube Dashboard).
