### ISSUE TITLE
Doc: Example Template Custom Resource Name

### ISSUE THREAD

**Issue by michaelsatish** [kubeshop/testkube#4517]
**Describe the bug**
I noticed the example Template CRD name provided for  is `example-webhook`. Renaming to `job-template` will align with the test example provided.

https://docs.testkube.io/articles/templates

```yaml
apiVersion: tests.testkube.io/v1
kind: Template
metadata:
  name: example-webhook # job-template
  namespace: testkube
spec:
  type: job
  body: <YOUR_TEMPLATE_BODY>
```

```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: template-test
  namespace: testkube
spec:
  type: k6/script
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube.git
      branch: main
      path: test/k6/executor-tests/k6-smoke-test.js
      authType: basic
  executionRequest:
    jobTemplateReference: job-template # Match this
```
