### ISSUE TITLE
Run image override (container executor) - the default image is used

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4609]
**Describe the bug**
Image isn't overridden if specified on test run with --image.

**To Reproduce**
Run command: `testkube run test container-executor-cypress-v12.7.0-smoke-git-dir --image cypress/included:13.5.0`
Based on `kubectl describe`, the default image is still used: `Image:         cypress/included:12.7.0`

Executor:
```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: container-executor-cypress-v12.7.0
spec:
  image: cypress/included:12.7.0
  executor_type: container
  types:
  - container-executor-cypress-v12.7.0/test
  features:
  - artifacts
```

Test:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: container-executor-cypress-v12.7.0-smoke
  labels:
    core-tests: executors
spec:
  type: container-executor-cypress-v12.7.0/test
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube
      branch: main
      path: test/cypress/executor-tests/cypress-12
      workingDir: test/cypress/executor-tests/cypress-12
  executionRequest:
    variables:
      CYPRESS_CUSTOM_ENV:
        name: CYPRESS_CUSTOM_ENV
        value: CYPRESS_CUSTOM_ENV_value
        type: basic
    args:
      - --env
      - NON_CYPRESS_ENV=NON_CYPRESS_ENV_value
      - --config
      - '{"screenshotsFolder":"/data/artifacts/screenshots","videosFolder":"/data/artifacts/videos"}'
    artifactRequest:
      storageClassName: standard
      volumeMountPath: /data/artifacts
      dirs:
        - ./
    jobTemplate: "apiVersion: batch/v1\nkind: Job\nspec:\n  template:\n    spec:\n      containers:\n        - name: \"{{ .Name }}\"\n          image: {{ .Image }}\n          resources:\n            requests:\n              memory: 2Gi\n              cpu: 2\n"
    activeDeadlineSeconds: 600
```
