### ISSUE TITLE
Dashboard Pod keeps crashing on OpenShift

### ISSUE THREAD

**Issue by christianknell** [kubeshop/testkube#4690]
**Describe the bug**

When installing the latest version of the `testkube` [Helm Chart](https://artifacthub.io/packages/helm/kubeshop/testkube) on OpenShift I am unable to get the Dashboard Pod up and running. It crashes with the error shown below.

**To Reproduce**

1. Define `values.yaml` like following:
```yaml
  mongodb:
    containerSecurityContext:
      enabled: true
      runAsUser: 1000756001
      runAsNonRoot: true
    podSecurityContext:
      enabled: false
    securityContext:
      enabled: true
      fsGroup: 1000756001
      runAsUser: 1000756001
    volumePermissions:
      enabled: false
  testkube-api:
    cliIngress:
      enabled: true
      hosts:
        - <REMOVED>
    clusterName: <REMOVED>
    uiIngress:
      enabled: true
      hosts:
        - <REMOVED>
  testkube-dashboard:
    ingress:
      enabled: true
      hosts:
        - <REMOVED>
  testkube-operator:
    webhook:
      migrate:
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      patch:
        enabled: true
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000756000
          fsGroup: 1000756000
```

2. Run:

```bash
helm repo add kubeshop https://kubeshop.github.io/helm-charts
helm install testkube kubeshop/testkube --version 1.16.8 -f values.yaml
```

3. See error

![grafik](https://github.com/kubeshop/testkube/assets/12433010/a4e26691-c68c-4818-a4e1-f0c17a9d8fc6)

**Expected behavior**

The Dashboard Pod should be up and running.

**Version / Cluster**
- Which testkube version?
  - testkube-api-server: 1.16.8
  - testkube-dashboard: 1.16.0
  - testkube-operator: 1.16.0
- Which testkube Helm Chart version? 1.16.8
- What Kubernetes cluster? OpenShift
- What OpenShift version? 4.12.36
- What Kubernetes version? 1.25.12

**Additional Context**

The errors seems to be related to this line in the [Dockerfile](https://github.com/kubeshop/testkube-dashboard/blob/develop/Dockerfile#L42):

```Dockerfile
CMD [ \
  "/bin/sh", \
  "-c", \
  "cp -R /app/build/. /usr/share/nginx/html && \
   cp -R /app/nginx/. /etc/nginx && \
   sh /app/init/env.sh env-config.js && \
   sh /app/init/inject-base-href.sh && \
   export DISABLE_IPV6=\"$([[ \"$ENABLE_IPV6\" = \"true\" ]] && echo \"false\" || echo \"true\")\" && \
   envsubst '$DISABLE_IPV6' < /etc/nginx/nginx.conf.tmpl | sed -e '1h;2,$H;$!d;g' -e 's/# cut true.*# end//g' > /etc/nginx/nginx.conf && \
   nginx -g \"daemon off;\"" ]
```

The change to the line in the Dockerfile happened in this [Commit](https://github.com/kubeshop/testkube-dashboard/commit/eb9fd2566d64da57a7b84121a636c53ac2e33b7b#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557).
