### ISSUE TITLE
Postman executor should support test via Postman URL (API)

### ISSUE THREAD

**Issue by krokofant** [kubeshop/testkube#4692]
**Is your feature request related to a problem? Please describe.**
We have collections in Postman workspaces which we can to run, and the simplest thing is to run newman with the link to the Postman collection. This does not seem possible with the postman executor.

**Describe the solution you'd like**
Support passing in [collection URL using Postman API](https://learning.postman.com/docs/collections/using-newman-cli/continuous-integration/#run-newman-and-use-the-postman-api) as an alternative to using it from file or git file.
```bash
$ newman run "https://api.getpostman.com/collections/collection-id?apikey=postman-api-key"
```
```bash
$ newman run "https://api.getpostman.com/collections/collection-id?apikey=postman-api-key"
--environment "https://api.getpostman.com/environments/environment-id?apikey=postman-api-key"
```

**Describe alternatives you've considered**
1. Exporting to git via some automation and use git as a source.
2. Using our own custom executor to run newman.

**Additional context**

**Comment by vsukhin** [comment]
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: postman-executor-url
  namespace: testkube
spec:
  type: postman/collection
  content:
   type: string
  executionRequest:
    argsMode: override
    args:
      - run
      - "https://api.getpostman.com/collections/collection-id?apikey=postman-api-key"
      - --environment
      - "https://api.getpostman.com/environments/environment-id?apikey=postman-api-key"
```
