### ISSUE TITLE
Could not get Newman result

### ISSUE THREAD

**Issue by guiyomh** [kubeshop/testkube#4694]
**Describe the bug**

I provision a postman test and overload the execution arguments like this:

```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: my-smoke-test
  namespace: my-namespace
  labels:
    type: ms
    version: feat-testkube-newman-5eb99672
spec:
  type: postman/collection
  content:
    repository:
      branch: feat/testkube-newman
      path: tests/newman/smoke-test.postman_collection.json
  source: ms-test
  executionRequest:
    variables:
      BASE_URL:
        name: BASE_URL
        value: "https://blabla.com"
        type: basic
      NODE_ENV:
        name: NODE_ENV
        value: "production"
        type: basic
    args:
      - "--reporters"
      - "cli,json,junit"
      - "--reporter-json-export"
      - "/data/artifacts/report.json"
      - "--reporter-junit-export"
      - "/data/artifacts/junit.xml"
    artifactRequest:
      storageClassName: ebs-gp3
      volumeMountPath: /share/
      dirs:
      - /data/artifacts/
    executePostRunScriptBeforeScraping: false
```

When I run the test, I can see that the executor generates this command line for me:
`newman run /data/repo/tests/newman/smoke-test.postman_collection.json -e /tmp/testkube-tmp4270038816 --reporters cli,json --reporter-json-export /tmp/testkube-tmp1625347806.json --reporters cli,json,junit --reporter-json-export /data/artifacts/report.json --reporter-junit-export /data/artifacts/junit.xml`

It's not a problem for newman, it takes into account the last arguments and generates the reports at the desired location.

<img width="573" alt="Capture d’écran 2023-11-28 à 17 45 07" src="https://github.com/kubeshop/testkube/assets/363162/e2e8b1a0-28a5-48f8-b3dc-ebabd61e9471">

Tests run successfully, but the runner tries to read another result file, which has not been generated.
<img width="633" alt="Capture d’écran 2023-11-28 à 17 46 29" src="https://github.com/kubeshop/testkube/assets/363162/60dfceee-897f-4358-94b4-dd7e27e96c7e">

I think it's because the arguments are duplicated in the command line. There are the default ones and the ones I added thinking I was overloading them.
