### ISSUE TITLE
Allow Slack config and template to be passed through as a simple inline multi-line JSON document

### ISSUE THREAD

**Issue by spkane** [kubeshop/testkube#4699]
# Is your feature request related to a problem? Please describe.

At the moment, the `slackConfig` and `slackTemplate` values under `testkube-api` must be a plain or base64 encoded string.

```yaml
testkube-api:
  slackToken:  'REDACTED'
  slackConfig: "W3sgIkNoYW5uZWxJRCI6..."
  slackTemplate: "W3maWNhdGlvbi10YXJiOiAi..."
```

Although you can pass a plain string in (versus a base64 string), the way the chart template is setup, it does not appear to be easy/possible to pass in a JSON string enclosed in single quotes, in a way that it is escaped correctly in the resulting k8s YAML.

# Describe the solution you'd like

Passing in an inline JSON document would be generally more straightforward and flexible. This would allow better templating (before handing the values file to helm) and would also allow helm to escape the document correctly.

```yaml
testkube-api:
  slackToken:  'REDACTED'
  slackConfig: |
    [
      {
        "ChannelID": "CXXXXXXXXX",
        "events": [
          "end-test-failed",
          "end-test-timeout",
          "end-testsuite-failed",
          "end-testsuite-timeout"
        ],
        "selector": {
          "notification-target": "ME"
        }
      }
    ]
  slackTemplate: |
    {
      "blocks": [
        {
          "type": "section",
          "text": {
            "type": "plain_text",
            "emoji": true,
            "text": "Execution {{ .ExecutionName }} of {{ .TestName }} status {{ .Status }}"
          }
        },
    ...
```

This makes the Slack JSON accessible and easy to edit while allowing the helm template to prepare the JSON appropriately and embed it into the k8s manifest.

# Describe alternatives you've considered

Loading a JSON file from the file system is another approach, but generally, an inline JSON document seems most straightforward and flexible.

# Additional context

In our environment, we use `kustomize` with helm support enabled to render the manifests for Testkube.

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

helmCharts:
  - name: testkube
    repo: https://kubeshop.github.io/helm-charts
    releaseName: testkube
    namespace: testkube
    version: 1.16.9
    valuesFile: helm-values.yaml
```
