### ISSUE TITLE
Execution failed: could not start process with command:   error: exec: no command

### ISSUE THREAD

**Issue by rr-jino-jose** [kubeshop/testkube#4703]
**Describe the bug**
hello, I am using testkube helm chart version 1.14.11. And caught up with this issue.

```
✅ Ginkgo parameters from variables set: map[]
🌍 Building Ginkgo arguments from params
✅ Ginkgo arguments from params built: [--trace -p -r --junit-report report.xml --randomize-all --randomize-suites --keep-going]
🚚 Checking Ginkgo CLI version
could not start process with command:   error: exec: no command
output: 
🔬 Executing in directory /data/repo/internal/ginkgo/ekops/prisma: 
 $  version
❌ Execution failed: could not start process with command:   error: exec: no command
output: 
❌ error checking Ginkgo CLI version: could not start process with command:   error: exec: no command
output: 
```

This is my test yaml

```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  labels:
    executor: ginkgo-executor
    test-type: ginkgo-test
  name: ekops-component-prisma
  namespace: testkube
spec:
  content:
    repository:
      authType: basic
      branch: main
      path: internal/ginkgo/ekops/prisma
      type: git
      uri: XXX.git
    type: git-file
  executionRequest:
    args:
    - --trace
    - -p
    - -r
    - --junit-report
    - report.xml
    - --randomize-all
    - --randomize-suites
    - --keep-going
    command:
    - ginkgo
  source: devops-bot
  type: ginkgo/test
```

And this is my executor yaml

```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  creationTimestamp: "2023-11-29T20:20:52Z"
  generation: 1
  name: ginkgo-executor
  namespace: testkube
  resourceVersion: "4509968"
  uid: c8e01701-2c8d-4e97-b2e2-410013a4e8e4
spec:
  content_types:
  - string
  - file-uri
  - git-file
  - git-dir
  - git
  executor_type: job
  features:
  - artifacts
  - junit-report
  image: kubeshop/testkube-ginkgo-executor:1.14.7
  meta:
    docsURI: https://kubeshop.github.io/testkube/test-types/executor-ginkgo
    iconURI: ginkgo
  types:
  - ginkgo/test
```

I did some code search and looks like its not able to get Execution.command value
`https://github.com/kubeshop/testkube/blob/v1.14.7/contrib/executor/ginkgo/pkg/runner/runner.go#L118`

**Version / Cluster**
- Which testkube version? 
```
 Client Version 1.16.9
Server Version 1.11.22
```
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
  EKS
- What Kubernetes version?
   1.28,1.27

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**
