### ISSUE TITLE
UI: when displaying arguments in textarea with spaces, these should be escaped

### ISSUE THREAD

**Issue by rangoo94** [kubeshop/testkube#4728]
**Describe the bug**

When there is a test that has an argument with spaces, like:

```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: some-test
spec:
  type: cypress/project
  content:
  executionRequest:
    args:
      - "--testSuitePath=Test Suites/FOLDER/mytest"
```

It should correctly escape it on Test Details > Settings > Variables page.

**To Reproduce**

1. Create such test ([**example**](https://demo.testkube.dev/tests/temp-e2e-cypress-git-created-28f089f43dad45d2b740448c5c1d53ec/settings/variables))
2. Go to its "Variables & Secrets" configuration
3. Arguments textarea has `--testSuitePath=Test Suites/FOLDER/mytest` content

**Expected behavior**

The textarea should have escaped that argument from YAML spec, either with quotes or backslash:

```
"--testSuitePath=Test Suites/FOLDER/mytest"
'--testSuitePath=Test Suites/FOLDER/mytest'
--testSuitePath=Test\ Suites/FOLDER/mytest
```
