### ISSUE TITLE
TestSuite - labels aren't applied from CRD

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4740]
**Describe the bug**
Testsuite labels aren't set if it's created using CRD - `app: testkube` is always set.

**To Reproduce**
```
apiVersion: tests.testkube.io/v3
kind: TestSuite
metadata:
  name: executor-jmeter-other-tests
  labels:
    core-tests: executors
spec:
  description: "jmeter and jmeterd executor - other tests and edge-cases"
  steps:
  - stopOnFailure: false
    execute:
    - test: jmeter-executor-smoke-incorrect-url-assertion-negative
  - stopOnFailure: false
    execute:
    - test: jmeterd-executor-smoke-incorrect-url-assertion-negative
  - stopOnFailure: false
    execute:
    - test: jmeterd-executor-smoke-incorrect-url-assertion-slaves-negative
  - stopOnFailure: false
    execute:
    - test: jmeterd-executor-smoke-correct-url-failed-assertion-negative
  - stopOnFailure: false
    execute:
    - test: jmeterd-executor-smoke-failed-assertion-slaves-negative
  - stopOnFailure: false
    execute:
    - test: jmeterd-executor-smoke-failure-exit-code-0-negative
```

![Screenshot from 2023-12-08 11-17-08](https://github.com/kubeshop/testkube/assets/1473096/890d355d-ff22-404d-ba59-11f63c44fef2)

**Expected result**
Labels should be set according to definition (in this example `core-tests: executors`)

**Comment by vsukhin** [comment]
kubectl apply -f testsuite-labels.yaml

```
kubectl testkube get testsuite executor-jmeter-other-tests

Context:  (999.0.0-dev)   Namespace: testkube
---------------------------------------------

Test Suite:
Name:      executor-jmeter-other-tests
Namespace: testkube

Description:  jmeter and jmeterd executor - other tests and edge-cases

Labels:    core-tests=executors

Test batches: 6
  Names                                                            | Stop on failure | Download artifacts  
  [jmeter-executor-smoke-incorrect-url-assertion-negative]         | false           |                     
  [jmeterd-executor-smoke-incorrect-url-assertion-negative]        | false           |                     
  [jmeterd-executor-smoke-incorrect-url-assertion-slaves-negative] | false           |                     
  [jmeterd-executor-smoke-correct-url-failed-assertion-negative]   | false           |                     
  [jmeterd-executor-smoke-failed-assertion-slaves-negative]        | false           |                     
  [jmeterd-executor-smoke-failure-exit-code-0-negative]            | false           |   
```

```
kubectl testkube get testsuite executor-jmeter-other-tests --crd-only
Context:  (999.0.0-dev)   Namespace: testkube
---------------------------------------------

apiVersion: tests.testkube.io/v3
kind: TestSuite
metadata:
  name: executor-jmeter-other-tests
  namespace: testkube
  labels:
    core-tests: executors
spec:
  description: "jmeter and jmeterd executor - other tests and edge-cases"
  steps:
  - stopOnFailure: false
    execute:
    - test: jmeter-executor-smoke-incorrect-url-assertion-negative
  - stopOnFailure: false
    execute:
    - test: jmeterd-executor-smoke-incorrect-url-assertion-negative
  - stopOnFailure: false
    execute:
    - test: jmeterd-executor-smoke-incorrect-url-assertion-slaves-negative
  - stopOnFailure: false
    execute:
    - test: jmeterd-executor-smoke-correct-url-failed-assertion-negative
  - stopOnFailure: false
    execute:
    - test: jmeterd-executor-smoke-failed-assertion-slaves-negative
  - stopOnFailure: false
    execute:
    - test: jmeterd-executor-smoke-failure-exit-code-0-negative
```
