### ISSUE TITLE
K6 executor is ignoring the last argument passed

### ISSUE THREAD

**Issue by rangoo94** [kubeshop/testkube#4821]
**Describe the bug**

When overriding arguments passed for K6 executor, it's still following the regular logic, so when `repository.path` is leading to directory, it will [**delete the last argument**](https://github.com/kubeshop/testkube/blame/develop/contrib/executor/k6/pkg/runner/runner.go#L130-L136).

**To Reproduce**

```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: ms.cart
  namespace: qraft
spec:
  type: k6/script
  content:
    repository:
      branch: feat/testkube-k6
  source: ms-cart
  executionRequest:
    variables:
      NODE_ENV:
        name: NODE_ENV
        value: "production"
        type: basic
    args:
      - "run"
      - "--config"
      - "infra/load-tests/cart/config.json"
      - "<envVars>"
      - "infra/load-tests/cart/index.js"
    argsMode: override
    executePostRunScriptBeforeScraping: false
```

**Expected behavior**

It should keep arguments untouched.

**Additional context**

* It's a [**Discord report**](https://discord.com/channels/884464549347074049/885185707419770930/1187034585545064448). 
* [**Log from the Test**](https://github.com/kubeshop/testkube/files/13728611/k6-log.txt)
