### ISSUE TITLE
container executor - pre/post-run scripts - command isn't executed

### ISSUE THREAD

**Issue by tkonieczny** [kubeshop/testkube#4828]
**Describe the bug**
Container executor and pre/post-run scripts - command isn't executed, test is marked as passed just after pre-run.

https://demo.testkube.dev/tests/container-executor-postman-smoke/executions/658436af3e18ce9cee6da375 without pre/post-run scripts

https://demo.testkube.dev/tests/container-executor-postman-smoke/executions/6584381d3e18ce9cee6da381 with pre/post-run scripts

**To Reproduce**
1. Definitions:

Executor:
```
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: container-executor-postman-newman-6-alpine
spec:
  image: postman/newman:6-alpine
  executor_type: container
  types:
  - container-executor-postman-newman-6-alpine/test
```

Test:
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: container-executor-postman-smoke
  labels:
    core-tests: executors
spec:
  type: container-executor-postman-newman-6-alpine/test
  content:
    type: git
    repository:
      type: git
      uri: https://github.com/kubeshop/testkube
      branch: main
      path: test/postman/executor-tests/postman-executor-smoke.postman_collection.json
      workingDir: test/postman/executor-tests
  executionRequest:
    args: ["run", "postman-executor-smoke.postman_collection.json", "--env-var", "TESTKUBE_POSTMAN_PARAM=TESTKUBE_POSTMAN_PARAM_value"]
    preRunScript: "echo \"===== pre-run script\""
    postRunScript: "echo \"===== post-run script\""
    jobTemplate: "apiVersion: batch/v1\nkind: Job\nspec:\n  template:\n    spec:\n      containers:\n        - name: \"{{ .Name }}\"\n          image: {{ .Image }}\n          resources:\n            requests:\n              memory: 128Mi\n              cpu: 256m\n"
    activeDeadlineSeconds: 180
```
2. Run test
3. Pre-run script is executed 3 times, actual command isn't executed at all (and also post-run script), test is marked as *passed*.
```
$ k logs 6584381d3e18ce9cee6da381-b82vl -ntestkube
Defaulted container "6584381d3e18ce9cee6da381" out of: 6584381d3e18ce9cee6da381, 6584381d3e18ce9cee6da381-init (init)
===== pre-run script
===== pre-run script
===== pre-run script
```
