### ISSUE TITLE
error during trigger creation

### ISSUE THREAD

**Issue by fvogl** [kubeshop/testkube#4880]
Getting the same error when trying to create a trigger (would be my first one) using the GUI or by sending a manifest to the K8s API

```yaml
apiVersion: tests.testkube.io/v1
kind: TestTrigger
metadata:
  name: brix-account-ui
  namespace: brix-testkube
spec:
  action: run
  event: modified
  execution: testsuite
  resource: deployment
  resourceSelector:
    name: brix-account-ui
    namespace: brix-development
  testSelector:
    name: account-ui
```

>Bad Gateway
>failed to create test trigger brix-account-ui: client could not create test trigger: Internal error occurred: failed calling webhook >"vtesttrigger.kb.io": failed to call webhook: Post "https://testkube-operator-webhook-service.brix-testkube.svc:443/validate-tests->testkube-io-v1-testtrigger?timeout=10s": context deadline exceeded, context: null

I use the latest testkube version 1.16.22 on RedHat Openshift 4.13.25.
