### ISSUE TITLE
There is no GRADLE_USER_HOME env set in JDK17 build gradle executor.

### ISSUE THREAD

**Issue by exu** [kubeshop/testkube#4901]
**Describe the bug**

User on Discord have issue with setting Artifactory repo for Gradle:

I'm trying to configure my gradle artifactory using a script mounted via a configMap:
```
    envConfigMaps:
    - mount: true
      mountPath: /tmp/gradle
      mapToVariables: false
      reference: 
        name: ms-pact-consumer-example-for-kotlin-configure-gradle
```
My script attempt to create a directory $HOME/.gradle, i.e in the root user home, but fails due to permissions issue:
```
+ mkdir -p /.gradle/ro-caches/modules-2

mkdir: cannot create directory ‘/.gradle’
: Permission denied
```

More details in Discord thread: 
https://discord.com/channels/884464549347074049/1196858096702726254
