### ISSUE TITLE
can't execute test which use artifactRequest

### ISSUE THREAD

**Issue by HenryGuo1019** [kubeshop/testkube#4953]
**Describe the bug**
I can't run test which use artifactRequest to upload a artifact to a s3 bucket. Are you guys change the definition of the test in version 1.16.25?

**To Reproduce**
test.yaml
```
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  name: prepare-kylinv10-x86-single-rollback
  namespace: testkube
  labels:
    executor: script-executor
    test-type: script-test
spec:
  type: script/test
  content:
    repository:
      branch: f_testkube_01
      path: testkube-script
  source: yg-build
  executionRequest:
    variables:
      REMOTE_HOST:
        name: REMOTE_HOST
        value: "10.57.132.11"
        type: basic
      REMOTE_HOST_NAME:
        name: REMOTE_HOST_NAME
        value: "yg-build-kylin10-single"
        type: basic
      SNAP_NAME:
        name: SNAP_NAME
        value: "yg-build-kylin10-single-init"
        type: basic
    args:
      - "/data/repo/testkube-script/rollback_host.sh"
    activeDeadlineSeconds: 1800
    artifactRequest:
      storageClassName: csi-rbd-sc
      volumeMountPath: /share
      dirs:
      - kubeconfig
    executePostRunScriptBeforeScraping: false

```

api-server ERROR:
```
{"level":"error","ts":1706509628.821808,"caller":"server/httpserver.go:76","msg":"failed to execute test: execution failed: test execution failed: decoding pvc spec error: EOF","status":500,"stacktrace":"github.com/kubeshop/testkube/pkg/server.(*HTTPServer).Error\n\t/home/runner/work/testkube/testkube/pkg/server/httpserver.go:76\ngithub.com/kubeshop/testkube/internal/app/api/v1.(*TestkubeAPI).InitRoutes.(*TestkubeAPI).ExecuteTestsHandler.func33\n\t/home/runner/work/testkube/testkube/internal/app/api/v1/executions.go:108\ngithub.com/gofiber/fiber/v2.(*App).next\n\t/home/runner/go/pkg/mod/github.com/gofiber/fiber/v2@v2.51.0/router.go:145\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/home/runner/go/pkg/mod/github.com/gofiber/fiber/v2@v2.51.0/ctx.go:1030\ngithub.com/kubeshop/testkube/internal/app/api/v1.(*TestkubeAPI).InitRoutes.(*TestkubeAPI).AuthHandler.func2\n\t/home/runner/work/testkube/testkube/internal/app/api/v1/handlers.go:53\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/home/runner/go/pkg/mod/github.com/gofiber/fiber/v2@v2.51.0/ctx.go:1027\ngithub.com/gofiber/fiber/v2/middleware/cors.New.func1\n\t/home/runner/go/pkg/mod/github.com/gofiber/fiber/v2@v2.51.0/middleware/cors/cors.go:165\ngithub.com/gofiber/fiber/v2.(*App).next\n\t/home/runner/go/pkg/mod/github.com/gofiber/fiber/v2@v2.51.0/router.go:145\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/home/runner/go/pkg/mod/github.com/gofiber/fiber/v2@v2.51.0/ctx.go:1030\ngithub.com/gofiber/fiber/v2/middleware/pprof.New.func1\n\t/home/runner/go/pkg/mod/github.com/gofiber/fiber/v2@v2.51.0/middleware/pprof/pprof.go:46\ngithub.com/gofiber/fiber/v2.(*Ctx).Next\n\t/home/runner/go/pkg/mod/github.com/gofiber/fiber/v2@v2.51.0/ctx.go:1027\ngithub.com/kubeshop/testkube/pkg/server.(*HTTPServer).Init.func1\n\t/home/runner/work/testkube/testkube/pkg/server/httpserver.go:46\ngithub.com/gofiber/fiber/v2.(*App).next\n\t/home/runner/go/pkg/mod/github.com/gofiber/fiber/v2@v2.51.0/router.go:145\ngithub.com/gofiber/fiber/v2.(*App).handler\n\t/home/runner/go/pkg/mod/github.com/gofiber/fiber/v2@v2.51.0/router.go:172\ngithub.com/valyala/fasthttp.(*Server).serveConn\n\t/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.50.0/server.go:2359\ngithub.com/valyala/fasthttp.(*workerPool).workerFunc\n\t/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.50.0/workerpool.go:224\ngithub.com/valyala/fasthttp.(*workerPool).getCh.func1\n\t/home/runner/go/pkg/mod/github.com/valyala/fasthttp@v1.50.0/workerpool.go:196"}

```
