### ISSUE TITLE
Duplicate args in test job

### ISSUE THREAD

**Issue by mgazza** [kubeshop/testkube#5130]
**Describe the bug**
TestKube generates jobs with duplicate args.

**To Reproduce**

Kubectl apply the following resources (i've cut them down from the actual real examples).
essentially a string script with no content and an executor with args.

```yaml
apiVersion: tests.testkube.io/v3
kind: Test
metadata:
  labels:
    executor: example
    test-type: example-script
  name: example
  namespace: testkube
spec:
  content:
    data: ' '
    type: string
  type: example/script
```
```yaml
apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: example
  namespace: testkube
spec:
  args:
  - should-only-appear-once
  executor_type: container
  image: example
  types:
  - example/script
```
**Expected behavior**
A job created with the args specified only once.

**Version / Cluster**
- Which testkube version? 1.16.34
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube) ALL
- What Kubernetes version? 1.26.9

**Screenshots**
If applicable, add CLI commands/output to help explain your problem.
 
**Additional context**
