### ISSUE TITLE
--watch flag: `Read long line error: unexpected EOF`

### ISSUE THREAD

**Issue by david-polak-ataccama** [kubeshop/testkube#5945]
**Describe the bug**
Running a testworkflow with `--client direct` and `--watch` which does not produce any log output for a long time dies with `Read long line error: unexpected EOF'`.

**To Reproduce**
1. Define a long running TestWorkflow which does not produce any output

```yaml
kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: mocktests-eof
  namespace: testkube
spec:
  container:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
  steps:
    - name: Test EOF
      run:
        image: curlimages/curl:latest
        shell: |
          echo "Started"
          sleep 1200
          echo "Woken up"
```

2. Run the TestWorkflow using `--client direct` and `--watch`.

```
testkube --client direct \
  run testworkflow mocktests-eof \
  --watch
```

3. See error `Read long line error: unexpected EOF'` being thrown.

```
Context:  (2.1.36)   Namespace: testkube
----------------------------------------
Test Workflow Execution:
Name:                 mocktests-eof
Execution ID:         67121ba1122c8cc629d6718d
Execution name:       mocktests-eof-2
Execution namespace:  testkube
Execution number:     2
Requested at:         2024-10-18 08:26:09.392604571 +0000 UTC
Disabled webhooks:    false
Status:               queued
Getting logs from test workflow job 67121ba1122c8cc629d6718d
 (SuccessfulCreate) Created pod: 67121ba1122c8cc629d6718d-ktrfp
• Initializing
 (Pulling) Pulling image "<<cacheurl>>/testkube-tw-init:2.1.37"
 (Pulled) Successfully pulled image "<<cacheurl>>/testkube-tw-init:2.1.37" in 7.684s (7.684s including waiting)
 Creating state... done
 Initializing state... done
 Configuring init process... done
 Configuring toolkit... skipped
 Configuring shell... done
• passed in 8.701s
 (Pulling) Pulling image "<<cacheurl>>/curlimages/curl:latest"
 (Pulled) Successfully pulled image "<<cacheurl>>/curlimages/curl:latest" in 905ms (905ms including waiting)
• (1/1) Test EOF
 Started
Read long line error: unexpected EOF' 
$ Use following command to get test workflow execution details \
	kubectl testkube get twe 67121ba1122c8cc629d6718d
```

**Expected behavior**
The `--watch` flag should detect unexpected EOF and restart the watch.

**Version / Cluster**
- Which testkube version? 
2.1.37
- What Kubernetes cluster?
EKS
- What Kubernetes version?
v1.29.6-eks-1552ad0
 
**Additional context**
This also happens on pulling an image which runs for a long time.
```
• passed in 10.046s
 (Pulling) Pulling image "<< very large image >>"
Read long line error: unexpected EOF' 
$ Use following command to get test workflow execution details \
	kubectl testkube get twe 6710bdcefc0311b3e8a5d983
```
