### ISSUE TITLE
TestWorkflow tries to fetch image even if imagePullPolicy set to (Never|IfNotPresent)

### ISSUE THREAD

**Issue by jake-ciolek** [kubeshop/testkube#6028]
**Describe the bug**
TestKube attempts to download images for inspection regardless of the imagePullPolicy on the step.

The setup is local, using a kind cluster. If we use a TestWorkflow with a step that references an image present in the cluster, TestKube still tries to download it from docker hub. The image was loaded locally via `kind load docker-image`. Vanilla Kubernetes deployment referencing the image works properly.

**To Reproduce**
1. Create a dummy image.
2. Load it into a kind cluster.
3. Reference it in a TestWorkflow with imagePullPolicy set to Never or IfNotPresent:

```yaml
apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: my-custom-test-workflow
  namespace: testkube
  labels:
    app.kubernetes.io/name: my-api
    app.kubernetes.io/part-of: my-yaml
    testkube.io/test-tool: custom
    testkube.io/test-category: version-test
spec:
  container:
    workingDir: /data
  steps:
    - name: Run Custom Test
      run:
        image: my-local-image:v1
        imagePullPolicy: Never 
        env:
          - name: A_VAR
            value: a-value
```

This results in:

> kubectl testkube get twe 6735b35b994b75a9c3150ef4             
> 
> Context:  (2.1.56)   Namespace: testkube
> ----------------------------------------
> Test Workflow Execution:
> Name:                 my-custom-test-workflow
> Execution ID:         6735b35b994b75a9c3150ef4
> Execution name:       my-custom-test-workflow-3
> Execution namespace:  
> Execution number:     3
> Requested at:         2024-11-14 08:22:51.164 +0000 UTC
> Disabled webhooks:    false
> Status:               aborted
> Finished at:          2024-11-14 08:22:51.164 +0000 UTC
> Duration:             0s
> 
> ⨯ Failed to initialize the execution.
> failed to process test workflow: resolving image error: my-custom-test-workflow:v1: inspecting image: 'my-custom-test-workflow:v1' at '' registry: fetching 'my-custom-test-workflow:v1' image from '' registry: reading image "my-custom-test-workflow:v1": GET https://index.docker.io/v2/library/my-custom-test-workflow/manifests/v1: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/my-custom-test-workflow Type:repository]] 💔

**Expected behavior**
TestKube respects the imagePullPolicy and succesfully runs the cluster-local image without attempting to retrieve it from external registries.

**Version / Cluster**
- Which testkube version? 
**2.1.56**
- What Kubernetes cluster? (e.g. GKE, EKS, Openshift etc, local KinD, local Minikube)
**kind v0.25.0 go1.23.3 darwin/arm64**
- What Kubernetes version?
**1.27**

**Comment by rangoo94** [comment]
Unfortunately, that is required. Our instrumentation needs to have information about some of the image information, and that cannot be retrieved from the cluster. If you want to avoid inspecting the image, you can add the introspected properties i.e. in the global template - https://docs.testkube.io/articles/test-workflows-high-level-architecture#avoid-fetching-image-metadata

**Comment by jake-ciolek** [comment]
Thanks @rangoo94 That's the quickest GH issue response I've ever seen! 🚀 

I'll look over the link. I'm curious, shouldn't all the needed data be contained in the OCI image? Anyway, thanks again!

**Comment by rangoo94** [comment]
>  I'm curious, shouldn't all the needed data be contained in the OCI image?

They are contained, but we need to know that information before the Kubernetes will schedule a job. Besides small quality-of-life improvements that uses that (like covering permissions nicely, or improving multi-step performance), the most important part is that we are instrumenting containers to gain control over execution and output.

To do that, we are simply wrapping the command executed in the container with our own [**Init Process**](https://en.wikipedia.org/wiki/Init). There were some requests to Kubernetes to support it natively, but it's not implemented (i.e. [**here**](https://github.com/kubernetes/kubernetes/issues/84210)).

To (not precisely, but simply) explain, we are more/less "wrapping" the executed command, so if you would request `go test` command, we will actually run something more like - `/testkube-init-process go test`, so we can instrument it properly.

The solution works easily when the `command` is provided, but when we have some data missing, i.e.:
```yaml
steps:
- run:
    image: xyz:123
```

We would not be able to add `/testkube-init-process` in front, unless we would have information about the default `ENTRYPOINT` provided by the `xyz:123` image. Kubernetes doesn't have any API for image inspection, so we need to reach directly to the registry.

I hope it explains it shortly 🙂
