### ISSUE TITLE
Running a test from within a k8s job on a self-hosted Testkube instance doesn't work

### ISSUE THREAD

**Issue by aletv8** [kubeshop/testkube#6104]
**Describe the bug**
When launching a Testkube test from within a Kubernetes job on a self-hosted Testkube instance using cluster client configuration, the operation fails with a permission error.

**To Reproduce**
1. Define and apply the following ```job.yaml``` resource:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: testkube-run-tests-1
spec:
  template:
    spec:
      containers:
      - name: run-tests
        image: kubeshop/testkube-cli:2.1.19
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - |
          testkube run test testkube-my-test --client cluster -f
      restartPolicy: Never
  backoffLimit: 2
  ttlSecondsAfterFinished: 120
```
2. Apply the job: ```kubectl -n testkube apply -f job.yaml```
3. See error:
```
error: services "testkube-api-server:8088" is forbidden: User "system:serviceaccount:testkube:default" cannot get resource "services/proxy" in API group "" in the namespace "testkube": Azure does not have opinion for this user.)
```
4. Attempt to provide missing access rights by defining the following ClusterRole and ClusterRoleBinding:
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: testkube-clusterrole-test
rules:
- apiGroups: [""]
  resources: ["services/proxy"]
  resourceNames: ["*"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: binding-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: testkube-clusterrole-test 
subjects:
- kind: ServiceAccount
  name: testkube-ex-sa
  namespace: rag-test
```
5. Re-apply the Job using the service account and observe that the error persists.

**Expected behavior**
The Job should execute the test successfully, leveraging the provided ClusterRole and ClusterRoleBinding for the permissions.

**Version / Cluster**
- Which testkube version? CLI: 2.1.19, Testkube: 1.16.9
- What Kubernetes cluster? Azure Kubernetes Service (AKS)
