### ISSUE TITLE
User should have the flexibility to provide the custom name to JMeter artifacts when uploaded to S3 bucket. As of now it gets uploaded by the name of testkube execution id which is not user friendly.

### ISSUE THREAD

**Issue by akshaydawargithub** [kubeshop/testkube#6148]
**Is your feature request related to a problem? Please describe.**
So when I uploaded the JMeter artifacts to S3 bucket, I found that the key name is the testkube execution id. So, in a day if 10 reports are generated, then on S3 it will show 10 execution IDs and for a user it will be really difficult to you know categorize that when the artifact was uploaded. It does not has and date time appended to it. It's just execution id. To fetch yesterday's report one has to go testkube to look out for execution id and then find in S3 which is very difficult and not at all user friendly.

**Describe the solution you'd like**
There should be a provision to provide custom name including place holders like date and time, so that one can easily see which artifact was uploaded and when.

**Describe alternatives you've considered**
Now alternative is that one can run a post shell script after test execution to copy that key first with a new desired name and then delete the old one. As we cannot rename in S3. For this the POD must have aws cli installed in it.

**Comment by vsukhin** [comment]
thank you @akshaydawargithub ! For @olensmar and  @jmorante-ks to analyze

**Comment by olensmar** [comment]
hi @akshaydawargithub - thanks for this! Ultimately the naming of S3 buckets is an implementation detail that you shouldn't be exposed to or relying on, so I'm curious about why you are going directly to S3 for finding/downloading artifacts instead of using the Testkube CLI to do this? Thanks in advance for any insights you can share on your use-case..

**Comment by akshaydawargithub** [comment]
So, our higher management needs to see those artifacts from their end and they don't use Testkube CLI, it is we the SDETs who are using. 
And when the execution completes, we don't want any manual intervention to first download the artifacts and then upload it manually on S3 so that our managers can see. 
The whole process should be automated as in when the JMeter test has been executed then it should automatically upload the artifacts to S3 with a custom name. Right now the artifacts are getting uploaded to S3  but with the name as testkube execution id

**Comment by rangoo94** [comment]
You can as well just use a custom step to upload some artifacts, for example you could use [**minio/mc**](https://hub.docker.com/r/minio/mc) (Minio Client):

```yaml
- name: Saving artifacts
  condition: always # Perform even if previous steps fail
  retry: # Retry 5 times if save failed
    condition: failed
    count: 5
  run:
    image: minio/mc:latest
    env:
    - name: MINIO_URL
      value: some-url
    - name: MINIO_ACCESSKEY
      value: some-accesskey
    - name: MINIO_SECRETKEY
      value: some-secretkey
    - name: MINIO_BUCKET
      value: some-bucket
    shell: |
      /usr/bin/mc config host add minio "$MINIO_URL" "$MINIO_ACCESSKEY" "$MINIO_SECRETKEY"
      /usr/bin/mc mb "minio/$MINIO_BUCKET" || true
      /usr/bin/mc cp /data/my-artifact.txt "minio/$MINIO_BUCKET/{{workflow.name}}/{{execution.id}}my-artifact.txt"
```

This way, you can customize completely the way you are storing artifact, using both custom and [**built-in data**](https://docs.testkube.io/articles/test-workflows-expressions#selected-variables).
