### ISSUE TITLE
Broken TestWorkflow spec.pod.volumes propagation into Pod definition

### ISSUE THREAD

**Issue by thradec** [kubeshop/testkube#6196]
**Describe the bug**

The definition of volumes in TestWorkflow is not correctly propagated into the Pod definition.

**To Reproduce**

```
apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: mock-test
spec:
  container:
    volumeMounts:
      - name: api-token
        mountPath: /var/run/secrets/tokens
  pod:
    volumes:
      - name: api-token
        projected:
          sources:
            - serviceAccountToken:
                path: api-token
                expirationSeconds: 600
                audience: api
  steps:
    - shell: |
        if [ ! -f /var/run/secrets/tokens/api-token ]; then
          echo "Token not found"
          exit 1
        fi
```

**Expected behavior**

The pod definition should contain given volume:

```
spec:
  volumes:
    - name: api-token
      projected:
        sources:
          - serviceAccountToken:
              audience: api
              expirationSeconds: 600
              path: api-token
```

but there is only

```
spec:
  volumes:
    - name: api-token
      emptyDir: {}
```

**Version / Cluster**

It works fine with testkube 2.1.30, we observed regression after upgrade to 2.1.95. 
Testkube is installed as a standalone agent.
K8s version is 1.31 EKS.
