### ISSUE TITLE
Outdated documentation: https://docs.testkube.io/articles/install/advanced-install#artifact-storage--cleanup

### ISSUE THREAD

**Issue by vpatov** [kubeshop/testkube#6350]
**Describe the bug**
Outdated documentation: https://docs.testkube.io/articles/install/advanced-install#artifact-storage--cleanup

**To Reproduce**
1. Run `helm show values kubeshop/testkube`
2. See that output does not contain cleanup policy keys from documentation:
```
testkube-cloud-api:
  api:
    storage:
      cleanup:
        retentionDays: 90
        maxStorageSizeGb: 10
```

`retentionDays` is nowhere to be found, and it seems that `maxStorageSizeGb` has been moved to `minio.storage`.
