### ISSUE TITLE
authType: header with Bearer token for Bitbucket repo fails with "could not read Username" error

### ISSUE THREAD

**Issue by MatZie71** [kubeshop/testkube#6449]
**Describe the bug**
When using `authType: header` with a Bearer token for cloning a private Bitbucket repository (using Bitbucket HTTP access tokens at repository level), Testkube fails during the Git clone step.
The error indicates it's trying to prompt for a username, which should not be necessary when using a Bearer token.

Using the same Bearer token works correctly via CLI with:

```bash
git -c http.extraHeader="Authorization: Bearer BBDC-xxxxxxxxxxxxxxxxxxxxxxxxxx" \
    clone https://git.company_name.com/scm/cloud/obs-testkube.git
```
**To Reproduce**

1. Create a `TestWorkflow` with a Bitbucket HTTP access token and `authType: header`
2. Token is a valid repo-level Bearer token
3. Run the workflow
4. Observe Git clone step fails with username prompt error

Example TestWorkflow:

```yaml
kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: project1-test
  namespace: testkube
spec: 
  content:
    git:
      uri: https://git.company_name.com/scm/cloud/obs-testkube.git
      authType: header
      token: "BBDC-xxxxxxxxxxxxxxxxxxxxxxxxxx"
  container:
    workingDir: /data/tests/project1-gatling
  steps:
    - name: Run tests
      run:
        image: maven:3.9.6-eclipse-temurin-11-focal
        shell: |
          mvn gatling:test
```

**Expected behavior**
Testkube should:

* Use the provided Bearer token in the `Authorization: Bearer` header
* Not require a username
* Successfully clone the Bitbucket repository

**Version / Cluster**

* Testkube Heln version: 2.1.243
* Kubernetes cluster: AKS (Azure Kubernetes Service)
* Kubernetes version: v1.30

```
--------------------------------------------------
Test Workflow Execution:
Name:                 project1-test
Execution ID:         6842adefff6cda1785657bd0
Execution name:       project1-test-7
Execution namespace:
Execution number:     7
Requested at:         2025-06-06 08:59:27.764 +0000 UTC
Disabled webhooks:    false
Status:               failed
Queued at:            2025-06-06 08:59:27.764 +0000 UTC
Started at:           2025-06-06 08:59:27.764 +0000 UTC
Finished at:          2025-06-06 08:59:31.362 +0000 UTC
Duration:             3.598s
Getting logs for test workflow execution 6842adefff6cda1785657bd0

• Initializing
 (SuccessfulCreate) Created pod: 6842adefff6cda1785657bd0-tkvth
 (Pulled) Container image "docker.io/kubeshop/testkube-tw-toolkit:2.1.154" already present on machine
 Creating state... done
 Initializing state... done
 Configuring init process... done
 Configuring toolkit... done
 Configuring shell... done


• (1/2) Clone Git repository
 📦 Cloning into '/tmp/repo'...
 fatal: could not read Username for 'https://git.company_name.com': terminal prompts disabled
 error, trying again in 100ms (attempt 2/5): exit status 128
 Cloning into '/tmp/repo'...
 fatal: could not read Username for 'https://git.company_name.com': terminal prompts disabled
 error, trying again in 200ms (attempt 3/5): exit status 128
 Cloning into '/tmp/repo'...
 fatal: could not read Username for 'https://git.company_name.com': terminal prompts disabled
 error, trying again in 300ms (attempt 4/5): exit status 128
 Cloning into '/tmp/repo'...
 fatal: could not read Username for 'https://git.company_name.com': terminal prompts disabled
 error, trying again in 400ms (attempt 5/5): exit status 128
 Cloning into '/tmp/repo'...
 fatal: could not read Username for 'https://git.company_name.com': terminal prompts disabled

 cloning repository (error: exit status 128)
...
```

CLI clone (working example):

```bash
 git -c http.extraHeader="Authorization: Bearer BBDC-xxxxxxxxxxxxxxxxxxxxxxxxxx"     clone https://git.company_name.com/scm/cloud/obs-testkube.git
Cloning into 'obs-testkube'...
remote: Enumerating objects: 2827, done.
remote: Counting objects: 100% (2827/2827), done.
remote: Compressing objects: 100% (1376/1376), done.
remote: Total 2827 (delta 2033), reused 1720 (delta 1379), pack-reused 0
Receiving objects: 100% (2827/2827), 2.15 MiB | 770.00 KiB/s, done.
Resolving deltas: 100% (2033/2033), done.
```

**Additional context**

* Bitbucket documentation: [https://confluence.atlassian.com/bitbucketserver/http-access-tokens-939515499.html](https://confluence.atlassian.com/bitbucketserver/http-access-tokens-939515499.html)
* Testkube docs reference: [https://docs.testkube.io/articles/test-workflows-content#using-authorization-header](https://docs.testkube.io/articles/test-workflows-content#using-authorization-header)

Please clarify whether `username` is still required despite `authType: header`, or if this is a bug in how the Bearer token is passed to Git.

Thanks!

**Comment by vsukhin** [comment]
hey @MatZie71 thank you for reporting. defimitely need to check cc @jmorante-ks @olensmar

**Comment by WitoDelnat** [comment]
Hello! Could you try to explicitly add the username as follows and let us know if that resolves the problem?

```diff
kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: project1-test
  namespace: testkube
spec: 
  content:
    git:
      uri: https://git.company_name.com/scm/cloud/obs-testkube.git
+   username: x-token-auth  
      authType: header
      token: "BBDC-xxxxxxxxxxxxxxxxxxxxxxxxxx"
```

**Comment by MatZie71** [comment]
Hey @WitoDelnat 
```
  content:
    git:
      uri: https://git.company_name.com/scm/cloud/obs-testkube.git
      revision: master
      paths: 
        - tests/project_name-gatling
      username: x-token-auth  
      authType: header
      token: "BBDC-xxx"
```

RESULT
```
• (1/5) Clone Git repository
 Cloning into '/tmp/repo'...
 📦 fatal: could not read Password for 'https://x-token-auth@git.company_name.com': terminal prompts disabled
 error, trying again in 100ms (attempt 2/5): exit status 128
 Cloning into '/tmp/repo'...
 fatal: could not read Password for 'https://x-token-auth@git.company_name.com': terminal prompts disabled
 error, trying again in 200ms (attempt 3/5): exit status 128
 Cloning into '/tmp/repo'...
 fatal: could not read Password for 'https://x-token-auth@git.company_name.com': terminal prompts disabled
 error, trying again in 300ms (attempt 4/5): exit status 128
 Cloning into '/tmp/repo'...
 fatal: could not read Password for 'https://x-token-auth@git.company_name.com': terminal prompts disabled
 error, trying again in 400ms (attempt 5/5): exit status 128
 Cloning into '/tmp/repo'...
 fatal: could not read Password for 'https://x-token-auth@git.company_name.com': terminal prompts disabled2025-06-08T07:02:05.644786272Z cloning repository (error: exit status 128)


• failed in 1.766s
```
