### ISSUE TITLE
Test step with stopOnFailure true not showing in result

### ISSUE THREAD

**Issue by olensmar** [kubeshop/testkube#866]
I had set the last step of my test to have stopOnFailure: true:

```
apiVersion: tests.testkube.io/v1
kind: Test
metadata:
  name: petstore-test
  namespace: testkube
spec:
  steps:
    - execute:
        name: petstore-inventory
        namespace: testkube
        stopOnFailure: true
    - delay:
        duration: 1000
    - execute:
        name: petstore-findpetbyid
        namespace: testkube
        stopOnFailure: true
    - delay:
        duration: 1000
    - execute:
        name: cypress-petstore
        namespace: testkube
        stopOnFailure: true
```

but when that step failed the result didn't show in the test execution results at all and the test is stuck in "pending" state 

![image](https://user-images.githubusercontent.com/1917063/151048021-77800a95-0134-4e80-8cf2-484b880bece4.png)

![image](https://user-images.githubusercontent.com/1917063/151047955-94aff6c8-81df-47db-bd9b-627d311595a1.png)
